begin;
drop table liste.nu_materiali;
drop table liste.ra_materia;
drop table liste.ra_tecnica;
CREATE TABLE liste.materia(id serial primary key, tsk integer NOT NULL, value character VARYING unique);
CREATE TABLE liste.tecnica(id serial primary key, tsk integer NOT NULL, value character VARYING unique);
insert into liste.materia(tsk,value) values
(0,'acciaio'),
(2,'acmonital '),
(1,'acquamarina'),
(1,'agata'),
(1,'agata zonata'),
(1,'alabastro'),
(1,'alabastro a pecorella'),
(1,'alabastro a tartaruga'),
(1,'alabastro bianco'),
(1,'alabastro del Gebel Oust'),
(1,'alabastro di Palombara'),
(1,'alabastro dorato'),
(1,'alabastro egiziano'),
(1,'alabastro fiorito'),
(1,'alabastro marino'),
(2,'alluminio '),
(1,'amazzonite'),
(1,'ambra'),
(1,'ametista'),
(1,'ardesia'),
(1,'arenaria'),
(0,'argento'),
(0,'argento dorato'),
(2,'argento suberato '),
(1,'argilla'),
(1,'avorio'),
(1,'barbottina'),
(1,'basalto'),
(1,'basanite'),
(2,'biglione '),
(2,'billone '),
(1,'breccia'),
(2,'bronzital '),
(0,'bronzo'),
(0,'bronzo dorato'),
(1,'bucchero'),
(1,'calcare'),
(1,'calcarenite'),
(1,'calce'),
(1,'calcedonio'),
(1,'calcite'),
(1,'canapa'),
(1,'cappellaccio'),
(1,'carapace'),
(1,'carparo'),
(1,'carparo stuccato'),
(1,'ceralacca'),
(1,'ceramica'),
(1,'cilindretti'),
(1,'clorite'),
(1,'cloritoscisto'),
(1,'cocciopesto'),
(1,'conchiglia'),
(1,'corallo'),
(1,'corindone'),
(1,'corniola'),
(1,'corno'),
(1,'cotone'),
(1,'cristallo'),
(1,'cristallo di rocca'),
(1,'crudo'),
(1,'cuoio'),
(1,'diamante'),
(1,'diaspro'),
(1,'diorite'),
(1,'elettro'),
(1,'eliotropio'),
(1,'ematite'),
(1,'eufotide'),
(1,'faience'),
(0,'ferro'),
(1,'fibra di canapa'),
(1,'fibra di sparto'),
(1,'foglia aurea'),
(1,'galena'),
(1,'gesso'),
(1,'gesso alabastrino'),
(1,'ghiaia'),
(1,'giada'),
(1,'giaietto'),
(1,'gneiss'),
(1,'grafite'),
(1,'granato'),
(1,'granito'),
(1,'granito rosso'),
(1,'intonaco'),
(2,'italma'),
(1,'lamina aurea'),
(1,'lana'),
(1,'lapislazzuli'),
(1,'laterizio'),
(1,'lava basaltica'),
(1,'lavagna'),
(0,'lega'),
(2,'lega di acmonital e nichelio'),
(2,'lega di rame'),
(0,'lega metallica'),
(1,'legno'),
(1,'lino'),
(1,'madreperla'),
(1,'malachite'),
(1,'mano'),
(1,'marmo'),
(1,'marmo africano'),
(1,'marmo asiatico'),
(1,'marmo bardiglio di Carrara'),
(1,'marmo bianco'),
(1,'marmo bianco greco'),
(1,'marmo bianco italico'),
(1,'marmo bianco venato'),
(1,'marmo bigio'),
(1,'marmo bigio antico'),
(1,'marmo bigio morato'),
(1,'marmo broccatello'),
(1,'marmo broccatellone'),
(1,'marmo cipollino'),
(1,'marmo cipollino mandolato'),
(1,'marmo cipollino marino'),
(1,'marmo cipollino rosso'),
(1,'marmo cottanello antico'),
(1,'marmo dell''Imetto'),
(1,'marmo di Carrara'),
(1,'marmo di Proconneso'),
(1,'marmo di Taso'),
(1,'marmo fior di pesco'),
(1,'marmo giallo antico'),
(1,'marmo giallo antico brecciato'),
(1,'marmo giallo tigrato'),
(1,'marmo greco insulare'),
(1,'marmo greco scritto'),
(1,'marmo grigio'),
(1,'marmo grigio brecciato'),
(1,'marmo grigio venato'),
(1,'marmo italico'),
(1,'marmo lumachella'),
(1,'marmo lumachella bigia'),
(1,'marmo lumachella d''Egitto'),
(1,'marmo lumachella pavonazza'),
(1,'marmo lumachella rosea'),
(1,'marmo lumachellone antico'),
(1,'marmo lunense'),
(1,'marmo nero africano'),
(1,'marmo nero antico'),
(1,'marmo occhio di pavone bianco'),
(1,'marmo occhio di pavone bigio'),
(1,'marmo occhio di pavone pavonazzo'),
(1,'marmo occhio di pavone roseo'),
(1,'marmo occhio di pavone rosso'),
(1,'marmo palombino'),
(1,'marmo pario'),
(1,'marmo pavonazzetto'),
(1,'marmo pentelico'),
(1,'marmo policromo'),
(1,'marmo portasanta'),
(1,'marmo proconnesio'),
(1,'marmo rosa'),
(1,'marmo rosso antico'),
(1,'marmo rosso brecciato'),
(1,'marmo semesanto'),
(1,'marmo serpentina moschinata'),
(1,'marmo verde antico'),
(1,'marmo verde rana fibroso'),
(1,'marmo verde rana ondato'),
(1,'marna'),
(1,'materiale litico'),
(0,'metallo'),
(1,'mica'),
(2,'mistura'),
(2,'mistura d''argento'),
(1,'nenfro'),
(0,'nichel'),
(1,'nicolo'),
(1,'occhio di gatto'),
(1,'occhio di pavone bianco'),
(1,'occhio di pavone bigio'),
(1,'occhio di pavone pavonazzo'),
(1,'occhio di pavone roseo'),
(1,'occhio di tigre'),
(1,'ofiolite'),
(1,'olivina'),
(1,'onice'),
(1,'opale'),
(0,'oricalco'),
(0,'oro'),
(1,'ossidiana'),
(1,'osso'),
(2,'ottone'),
(1,'paglia'),
(1,'pasta di talco'),
(1,'pasta silicea'),
(1,'pasta vitrea'),
(2,'peltro'),
(1,'peperino'),
(1,'perla'),
(1,'pettine'),
(1,'pietra'),
(1,'pietra basaltica'),
(1,'pietra braschia'),
(1,'pietra calcarea'),
(1,'pietra d''Istria'),
(1,'pietra dura'),
(1,'pietra lavica'),
(1,'pietra nefritica'),
(1,'pietra ollare'),
(1,'pietra talcosa'),
(1,'pietra tenera'),
(1,'pietra verde'),
(0,'piombo'),
(1,'plasma'),
(1,'platino'),
(1,'porcellana'),
(1,'porfido'),
(1,'porfido bigio'),
(1,'porfido nero'),
(1,'porfido nero grafico'),
(1,'porfido rosso'),
(1,'porfido verde di Laconia'),
(1,'porfido verde egiziano'),
(1,'pozzolana'),
(1,'prasio'),
(1,'puddinga'),
(1,'quarzite'),
(1,'quarzo'),
(1,'quarzo rosa'),
(0,'rame'),
(1,'resina'),
(1,'roccia carbonatica'),
(1,'roccia metamorfica'),
(1,'roccia silicatica'),
(1,'rotella'),
(1,'rubino'),
(1,'sarda'),
(1,'sardonice'),
(1,'scisto'),
(1,'scoria di fusione'),
(1,'scoria silicea'),
(1,'segagione'),
(1,'selce'),
(1,'seme'),
(1,'seta'),
(1,'smalto'),
(1,'smeraldo'),
(1,'sostanze cosmetiche'),
(1,'spatola'),
(1,'spinello'),
(0,'stagno'),
(1,'steatite'),
(1,'stucco'),
(1,'sughero'),
(1,'talco'),
(1,'talcoscisto'),
(1,'tempra'),
(1,'terracotta'),
(1,'terracotta dorata'),
(1,'tessuto'),
(1,'topazio'),
(1,'tormalina'),
(1,'trachite'),
(1,'trachite dei Colli Euganei'),
(1,'travertino'),
(1,'tufo'),
(1,'tufo giallo litoide'),
(1,'tufo grigio'),
(1,'tufo Nocerino'),
(1,'tufo rosso a scorie nere'),
(1,'tufo rosso litoide'),
(1,'tufo Sabazio'),
(1,'tufo trachitico'),
(1,'tufo Vulsinio'),
(1,'turchese'),
(1,'valve conchiglia'),
(1,'vetro'),
(1,'zaffiro'),
(2,'zinco'),
(1,'zircone');

insert into liste.tecnica(tsk,value) values
(1,'abrasione'),
(1,'affilatura'),
(1,'agemina'),
(1,'agemina in argento'),
(1,'agemina in oro'),
(0,'argentatura'),
(1,'basse-taille'),
(0,'battitura'),
(1,'battitura a caldo'),
(1,'battitura a freddo'),
(1,'battitura a stampo'),
(1,'brasatura'),
(1,'brunitura'),
(0,'bulinatura'),
(1,'cabochon'),
(1,'cassaforma'),
(1,'cesellatura'),
(1,'champleve'),
(1,'cloisonne'),
(1,'colatura a stampo'),
(1,'colombino'),
(0,'coniazione'),
(2,'coniazione a freddo'),
(2,'coniazione a macchina'),
(1,'damaschinatura'),
(1,'ditate'),
(1,'doppia matrice'),
(0,'doratura'),
(1,'doratura a foglia'),
(1,'doratura a mercurio'),
(1,'excisione'),
(1,'filatura'),
(1,'filigrana'),
(1,'finitura a stecca'),
(1,'finitura al tornio'),
(1,'foratura'),
(0,'forgiatura'),
(0,'fusione'),
(1,'fusione a cera persa'),
(1,'fusione a matrice'),
(1,'fusione a stampo'),
(1,'godronatura'),
(1,'graffito'),
(1,'granulazione'),
(1,'imbutitura'),
(1,'immersione'),
(1,'impasto'),
(1,'impressione'),
(1,'incastonatura'),
(0,'incisione'),
(1,'incisione a crudo'),
(1,'incrostazione'),
(1,'ingobbiatura'),
(1,'intaglio'),
(1,'intaglio a freddo'),
(1,'intarsio'),
(1,'invetriatura'),
(0,'laminatura'),
(1,'levigatura'),
(1,'limatura'),
(1,'lisciatura'),
(1,'lisciatura a stecca'),
(1,'lucidatura'),
(1,'lucidatura a stecca'),
(1,'martellatura'),
(1,'martellinatura'),
(1,'matrice'),
(1,'modellazione su bastoncino'),
(1,'modellazione su nucleo'),
(1,'molatura'),
(1,'mosaico'),
(1,'niello'),
(1,'opus sectile'),
(1,'opus tessellatum'),
(1,'patinatura'),
(1,'percussione'),
(1,'picchiettatura'),
(1,'pinzatura'),
(1,'pittura a encausto'),
(1,'pittura a fresco'),
(1,'pittura a tempera'),
(1,'plique-a-jour'),
(1,'politura'),
(1,'politura a ruota'),
(1,'puddellaggio'),
(0,'punzonatura'),
(1,'raschiatura'),
(1,'repousse'),
(1,'ribattitura'),
(1,'rifinitura a freddo'),
(1,'rilievo applicato'),
(1,'ritaglio'),
(1,'ritocco a mano'),
(1,'ritocco a stecca'),
(1,'rubricatura'),
(1,'sabbiatura'),
(1,'saldatura'),
(0,'sbalzo'),
(1,'sbozzatura'),
(1,'scalpellatura'),
(1,'scheggiatura'),
(1,'scialbatura'),
(1,'sgraffio'),
(1,'smaltatura'),
(1,'soffiatura'),
(1,'soffiatura a stampo'),
(1,'soffiatura libera'),
(1,'spruzzo'),
(1,'stagnatura'),
(1,'stampaggio'),
(1,'stampo'),
(1,'stecca'),
(1,'stralucido'),
(1,'subbiatura'),
(1,'taglio'),
(1,'taglio a freddo'),
(1,'Tecnica non presente in lista'),
(1,'tessitura a telaio'),
(1,'tornio'),
(1,'tornio idraulico'),
(1,'tornio veloce'),
(0,'traforo'),
(1,'trapano'),
(1,'trapano corrente'),
(1,'unghiate'),
(0,'verniciatura'),
(1,'zigrinatura');

commit;
