begin;
delete from liste.ogto;
insert into liste.ogto(value) values
('Aes rude'),
('Aes signatum'),
('Antoniniano'),
('Aspron trachy'),
('Asse'),
('Aureo'),
('Baiocco'),
('Cistoforo'),
('Corona'),
('Decadrammo'),
('Decanummo'),
('Decusse'),
('Denario'),
('Denaro'),
('Denaro piccolo scodellato'),
('Didrammo'),
('Dinar'),
('Diobolo'),
('Dionkion'),
('Dirham'),
('Distatere'),
('Doppio nomos'),
('Dracma'),
('Ducato'),
('Dupondio'),
('Emidracma'),
('Emilitra'),
('Emiobolo'),
('Follis'),
('frazione di Follis'),
('Fulus'),
('Grosso da 12 denari'),
('Guldengroschen'),
('Hexas'),
('Histamenon'),
('Iperpero'),
('Litra'),
('Medaglione'),
('Medaglione da 5 solidi'),
('mezzo Follis'),
('Miliarense'),
('Multiplo da 5 zecchini'),
('Nomisma'),
('Nomos'),
('Nummo'),
('Obolo'),
('Oncia'),
('Ottodrammo'),
('Pentanummo'),
('Pentadrammo'),
('Pentalitron'),
('Pentonkion'),
('Prutah'),
('Quadrante'),
('Quadrigato'),
('Quartoncia'),
('Quinario'),
('Quincusse'),
('Siclo'),
('Scudo'),
('Semisse'),
('Semoncia'),
('Sestante'),
('Sesterzio'),
('Shekel'),
('Siliqua'),
('Solido'),
('Statere'),
('Tallero'),
('Tarì'),
('Tetarteron'),
('Tetradrammo'),
('Tetras'),
('Tetrobolo'),
('Tornese'),
('Tremisse'),
('Trias'),
('Tridrammo'),
('Triente'),
('Triemiobolo'),
('Triobolo'),
('Tripondio'),
('Vittoriato'),
('0.05 Lek'),
('10 Centesimi'),
('12 Nummi'),
('1/4 di Calco'),
('1/4 di Siliqua'),
('1/8 di Scudo'),
('4 Ducati'),
('5 Lire'),
('5 Nummi'),
('AE1'),
('AE2'),
('AE3'),
('AE4');

COMMIT;
