BEGIN;
CREATE SCHEMA work;
CREATE TABLE work.l5(
  id serial primary key,
  l4 integer,
  def CHARACTER VARYING,
  val CHARACTER VARYING
);
INSERT INTO work.l5(def,val) values
('balteus','fibbia di aggancio'),
('bottone','a calotta'),
('brassard','con custodia'),
('cingulum','borchia'),
('cingulum','fibbia di aggancio'),
('cingulum','lamina'),
('cingulum','pendente'),
('cintura','per la sospensione delle armi'),
('cintura','a fascia'),
('cintura','a losanga'),
('cintura','a placche'),
('cintura','multipla'),
('cintura','affibbiaglio'),
('cintura','borchia'),
('cintura','controplacca'),
('cintura','fibbia'),
('cintura','gancio'),
('cintura','lamina'),
('cintura','linguetta'),
('cintura','passante'),
('cintura','placca'),
('cintura','puntale'),
('cintura','puntale secondario'),
('fibbia','di aggancio'),
('fibbia','ardiglione'),
('fibbia','gancio'),
('fibbia','placca'),
('fibula','a drago'),
('fibula','a losanga'),
('fibula','a navicella'),
('fibula','a occhiali'),
('fibula','a piu'' occhielli e ago diritto'),
('fibula','a placchetta'),
('fibula','a placchette'),
('fibula','a quattro spirali'),
('fibula','a sanguisuga'),
('fibula','a sanguisuga con decorazione plastica'),
('fibula','a tre occhielli e staffa allungata'),
('fibula','ad arco semplice'),
('fibula','ad arco a coste'),
('fibula','ad arco a dischi'),
('fibula','ad arco a occhielli e spirali coniche'),
('fibula','ad arco a ponticello'),
('fibula','ad arco con serie di occhielli'),
('fibula','ad arco di violino'),
('fibula','ad arco di violino a doppia foglia'),
('fibula','ad arco di violino con cappi ad otto'),
('fibula','ad arco di violino con due noduli'),
('fibula','ad arco di violino con quattro noduli'),
('fibula','ad arco di violino asimmetrico'),
('fibula','ad arco di violino con cappi a otto e staffa a disco'),
('fibula','ad arco di violino foliato'),
('fibula','ad arco di violino rialzato'),
('fibula','ad arco foliato'),
('fibula','ad arco ingrossato'),
('fibula','ad arco quadrangolare'),
('fibula','ad arco ingrossato a gomito'),
('fibula','ad arco ingrossato con staffa a disco'),
('fibula','ad arco leggermente ribassato con sezione romboidale'),
('fibula','ad arco ribassato a occhielli'),
('fibula','ad arco ribassato elicoidale'),
('fibula','ad arco ribassato multiplo'),
('fibula','ad arco ribassato ritorto a cordicella'),
('fibula','ad arco rivestito'),
('fibula','ad arco semplice rivestito di perline'),
('fibula','ad arco rivestito a losanga'),
('fibula','ad arco rivestito con staffa a disco'),
('fibula','ad arco schiacciato'),
('fibula','ad arco schiacciato con bottoni laterali'),
('fibula','ad arco semplice a gomito'),
('fibula','ad arco semplice elicoidale'),
('fibula','ad arco scudato'),
('fibula','serpeggiante'),
('fibula','serpeggiante a bastoncelli'),
('fibula','serpeggiante a due pezzi'),
('fibula','serpeggiante a gomito'),
('fibula','serpeggiante a gomito con arco bifido'),
('fibula','serpeggiante a occhiello'),
('fibula','serpeggiante con ago elastico bifido'),
('fibula','serpeggiante con ago a gomito'),
('fibula','serpeggiante con ago a occhielli'),
('fibula','serpeggiante con occhiello a contorno quadrangolare'),
('fibula','serpeggiante con occhiello e ago curvo'),
('fibula','serpeggiante con occhiello e ago dritto'),
('fibula','serpeggiante con occhiello e staffa a disco'),
('fibula','ago'),
('fibula','ago dritto'),
('fibula','ago ad U'),
('fibula','ardiglione'),
('fibula','arco'),
('fibula','cappio a otto'),
('fibula','molla'),
('fibula','occhiello'),
('fibula','sbarretta trasversale'),
('fibula','staffa'),
('fibula','staffa a disco spirale'),
('fibula','staffa a spirale'),
('fibula','vaghi'),
('nastro','per capelli'),
('spillone','ago'),
('spillone','capocchia'),
('spillone','collo'),
('spillone','gambo'),
('spillone','punta'),
('spillone','stelo'),
('spillone','testa'),
('caliga','speculatoria'),
('caliga','chiodo'),
('calzare','fibbia'),
('anello','crinale'),
('anello','da caviglia'),
('anello','digitale'),
('anello','fermatrecce'),
('anello','matrimoniale'),
('anello','portastrigili'),
('anello','pettorale'),
('anello','castone'),
('bracciale','omerale'),
('bracciale','bulla'),
('bracciale','pendente'),
('bulla','da bracciale'),
('bulla','da collana'),
('collana','chiusura'),
('collana','distanziatore'),
('collana','elemento'),
('collana','vago'),
('corona','funeraria'),
('corona','aurea'),
('corona','castrensis'),
('corona','civica'),
('corona','graminea'),
('corona','muralis'),
('corona','navalis'),
('corona','ovalis'),
('corona','triumphalis'),
('corona','vallaris'),
('orecchino','a globo mammellato'),
('orecchino','a sanguisuga'),
('orecchino','pendente'),
('pendente','terminale'),
('vago','globulare'),
('bracae','virgatae'),
('paenula','gausapina'),
('paenula','scortea'),
('paenula','cucullus'),
('tunica','esomide'),
('tunica','cincta'),
('tunica','talaris'),
('tunica','manicata'),
('tunica','recta'),
('tunica','subucula'),
('base','di sostegno'),
('base','onoraria'),
('base','circolare'),
('base','quadrata'),
('base','rettangolare'),
('base','triangolare'),
('cippo','funerario'),
('cippo','di acquedotto'),
('cippo','itinerario'),
('cippo','miliario'),
('cippo','segnaletico'),
('cippo','terminale'),
('cippo','sacro'),
('cippo','votivo'),
('cippo','con tre pilastri'),
('cippo','trono'),
('cippo','base'),
('cippo','coronamento'),
('ghianda','funeraria'),
('labrum','orlo'),
('mensa','mensuaria'),
('mensa','ponderaria'),
('mensa','sepolcrale'),
('stele','commemorativa'),
('stele','funeraria'),
('stele','votiva'),
('stele','frontone'),
('trapezoforo','zoomorfo'),
('trapezoforo','capitello'),
('trono','regale'),
('vasca','di decantazione'),
('vasca','lustrale'),
('sarcofago','a cassa parallelepipeda'),
('sarcofago','a lenos'),
('sarcofago','cassa'),
('sarcofago','fianco'),
('sarcofago','fronte'),
('sarcofago','coperchio'),
('sarcofago','coperchio a doppio spiovente'),
('sarcofago','coperchio a doppio spiovente con acroteri'),
('sarcofago','coperchio a lastra'),
('sarcofago','coperchio a tetto'),
('sarcofago','coperchio a kline'),
('sarcofago','coperchio a botte'),
('urna','cineraria'),
('urna','a cassa'),
('urna','a vaso'),
('urna','circolare'),
('urna','coperchio'),
('altare','funerario'),
('altare','a blocco'),
('altare','a cofano'),
('altare','a mensa'),
('ara','compitale'),
('ara','funeraria'),
('ara','votiva'),
('ara','base'),
('ara','coronamento'),
('ara','pulvino'),
('arula','a cassetta'),
('arula','a clessidra'),
('betilo','conico liscio'),
('betilo','mammellato'),
('betilo','restremato'),
('betilo','torre'),
('croce','astile'),
('croce','d''altare'),
('croce','pensile'),
('ciborio','archivolto'),
('modellino','votivo'),
('letto','da parata'),
('letto','fulcrum'),
('sedia','gamba'),
('sedia','sedile'),
('sedia','spalliera'),
('tavolo','da gioco'),
('baglio','testata'),
('colonna','onoraria'),
('colonna','sepolcrale'),
('colonna','votiva'),
('colonna','dorica'),
('colonna','ionica'),
('colonna','corinzia'),
('colonna','composita'),
('colonna','liscia'),
('colonna','scanalata'),
('colonna','tortile'),
('colonna','base'),
('colonna','capitello'),
('colonna','fusto'),
('colonna','imoscapo'),
('colonna','rocchio'),
('semicolonna','base'),
('semicolonna','fusto'),
('semicolonna','rocchio'),
('sima','angolare'),
('sima','frontonale'),
('sima','laterale'),
('sima','con gocciolatoio'),
('sima','doccione'),
('acroterio','angolare'),
('acroterio','centrale'),
('acroterio','laterale'),
('acroterio','a disco'),
('balaustra','pilastrino'),
('cornice','di frontone'),
('cornice','asiatica'),
('cornice','dorica'),
('cornice','ionica'),
('cornice','con mensole'),
('cornice','mista'),
('cornice','liscia'),
('cornice','inclinata'),
('cornice','pendula'),
('cornice','traforata'),
('cornice','blocco'),
('cornice','cassettone'),
('cornice','corona'),
('cornice','gocciolatoio'),
('cornice','gutta'),
('cornice','mensola'),
('cornice','mutulo'),
('cornice','peduncolo'),
('cornice','sopracornice'),
('cornice','sima'),
('cornice','soffitto'),
('cornice','sottocornice'),
('fontana','bocca'),
('fontana','parapetto'),
('fontana','vasca'),
('fontana','sbocco'),
('lacunare','blocco'),
('lacunare','lastra'),
('lacunare','coronamento'),
('lacunare','fascia'),
('lacunare','pannello'),
('lesena','base'),
('lesena','fusto'),
('transenna','pilastrino'),
('architrave','con coronamento a gola'),
('architrave','con coronamento a ovolo'),
('architrave','con lacunare'),
('architrave','dorico'),
('architrave','ionico'),
('architrave','liscio'),
('architrave','blocco'),
('architrave','gutta'),
('architrave','lastra'),
('architrave','coronamento'),
('architrave','fascia'),
('architrave','lacunare'),
('architrave','incorniciatura'),
('architrave','pannello di lacunare'),
('architrave','regula'),
('architrave','tenia'),
('archivolto','blocco'),
('archivolto','lastra'),
('capitello','d''anta'),
('capitello','di lesena'),
('capitello','di pilastro'),
('capitello','di semicolonna'),
('capitello','corinzio'),
('capitello','ionico'),
('capitello','lotiforme'),
('capitello','sferocubico'),
('capitello','tuscanico'),
('capitello','abaco'),
('capitello','anuli'),
('capitello','astragalo'),
('capitello','calice'),
('capitello','foglia di calice'),
('capitello','calicetto'),
('capitello','caulicolo'),
('capitello','collarino'),
('capitello','echino'),
('capitello','elice'),
('capitello','elice nastro'),
('capitello','fiore'),
('capitello','foglia'),
('capitello','foglia interna'),
('capitello','foglia esterna'),
('capitello','foglia acantizzante'),
('capitello','foglia d''acanto'),
('capitello','foglia liscia'),
('capitello','kalathos'),
('capitello','orlo'),
('capitello','pulvino'),
('capitello','semipalmetta'),
('capitello','stelo'),
('capitello','viticci'),
('capitello','voluta'),
('capitello','voluta corinzia'),
('capitello','voluta ionica'),
('capitello','canale di voluta'),
('capitello','nastro di voluta'),
('capitello','occhio di voluta'),
('fregio','celebrativo'),
('fregio','decorativo'),
('fregio','funerario'),
('fregio','onorario'),
('fregio','storico'),
('fregio','dorico'),
('fregio','ionico'),
('fregio','convesso'),
('fregio','con coronamento'),
('fregio','blocco'),
('fregio','lastra'),
('fregio','metopa'),
('fregio','triglifo'),
('frontone','acroterio'),
('pilastro','base'),
('pilastro','fusto'),
('stilobate','blocco'),
('fistula','acquaria'),
('fistula','bocchettone'),
('rubinetto','chiavetta'),
('fornello','base'),
('fornello','diaframma'),
('fornello','diaframma a bracci'),
('fornello','orlo'),
('fornello','parete'),
('fornello','piastra'),
('coppo','di colmo'),
('mattone','pavimentale'),
('tegola','di gronda'),
('tegola','rettangolare'),
('tegola','rettangolare bollata'),
('tegola','trapezoidale'),
('tegola','mammata'),
('tegola','ala'),
('tegola','listello'),
('tegola','piano'),
('formella','da stufa'),
('lastra','di copertura'),
('lastra','di coronamento'),
('lastra','di rivestimento'),
('lastra','di rivestimento pavimentale'),
('lastra','frontonale'),
('piastrella','da caminetto'),
('tassello','pavimentale'),
('mosaico','pavimentale'),
('mosaico','parietale'),
('bireme','da guerra'),
('caudicaria','da guerra'),
('deceris','da guerra'),
('esareme','da guerra'),
('nave','oneraria'),
('nave','attuaria'),
('nave','ippagoga'),
('nave','speculatoria'),
('nave','albero'),
('nave','chiglia'),
('nave','scafo'),
('quadrireme','da guerra'),
('quinquireme','da guerra'),
('trireme','da guerra'),
('arcera','da viaggio'),
('birota','da viaggio'),
('carpentum','da viaggio'),
('carro','ruota'),
('carro','cerchione'),
('carruca','dormitoria'),
('carruca','da viaggio'),
('covimmus','da viaggio'),
('essedum','da viaggio'),
('petorritum','da parata'),
('pilentum','da cerimonia'),
('plaustrum','onerario'),
('raeda','da viaggio'),
('serracum','per il trasporto delle merci'),
('tensa','da cerimonia'),
('triumphalis currus','da parata'),
('dipinto','parietale'),
('dipinto','opera parietale'),
('dipinto','affresco'),
('gasteropode','guscio'),
('maschera','apotropaica'),
('maschera','di fontana'),
('maschera','votiva'),
('maschera','comica'),
('maschera','tragica'),
('maschera','satiresca'),
('maschera','femminile'),
('maschera','maschile'),
('rilievo','celebrativo'),
('rilievo','funerario'),
('rilievo','onorario'),
('rilievo','storico'),
('rilievo','votivo'),
('busto','funerario'),
('busto','onorario'),
('busto','votivo'),
('busto','femminile'),
('busto','maschile'),
('gruppo statuario','votivo'),
('protome','votiva'),
('scultura','acroteriale'),
('statua','funeraria'),
('statua','onoraria'),
('statua','votiva'),
('statua','acroteriale'),
('statua','frontonale'),
('statua','femminile'),
('statua','iconica'),
('statua','maschile'),
('statua','menhir'),
('statua','arto inferiore'),
('statua','arto inferiore destro'),
('statua','arto inferiore sinistro'),
('statua','arto superiore'),
('statua','arto superiore destro'),
('statua','arto superiore sinistro'),
('statua','base'),
('statua','busto'),
('statua','braccio'),
('statua','braccio destro'),
('statua','braccio sinistro'),
('statua','dito'),
('statua','gamba'),
('statua','gamba destra'),
('statua','gamba sinistra'),
('statua','gomito'),
('statua','mano'),
('statua','mano destra'),
('statua','mano sinistra'),
('statua','piede'),
('statua','piede destro'),
('statua','piede sinistro'),
('statua','plinto'),
('statua','puntello'),
('statua','sostegno'),
('statua','testa'),
('statua','torso'),
('statuetta','funeraria'),
('statuetta','votiva'),
('statuetta','femminile'),
('statuetta','maschile'),
('testa','onoraria'),
('testa','ritratto'),
('testa','(ritratto)'),
('testa','votiva'),
('testa','femminile'),
('testa','maschile'),
('testa','collo'),
('testa','velo'),
('bronzetto','votivo'),
('accetta','rituale'),
('accetta','tallone'),
('ascia','da cerimonia'),
('ascia','da lavoro'),
('ascia','da battaglia'),
('ascia','votiva'),
('ascia','a cannone con due occhielli laterali'),
('ascia','a cannone con un occhiello laterale'),
('ascia','a cannone con spalla'),
('ascia','a cannone priva di spalla'),
('ascia','a margini rialzati'),
('ascia','a occhio'),
('ascia','a occhio a lama massiccia'),
('ascia','a occhio con testa a contorno pentagonale'),
('ascia','a occhio ovale'),
('ascia','a occhio ovale con lama asimmetrica'),
('ascia','a tagli ortogonali'),
('ascia','a tallone con due occhielli laterali'),
('ascia','a tallone con un occhiello laterale'),
('ascia','ad alette'),
('ascia','ad alette a tallone distinto'),
('ascia','ad alette a tallone non distinto'),
('ascia','barbuta'),
('ascia','con immanicatura a cartoccio'),
('ascia','con lama ricurva doppia'),
('ascia','doppia a tagli ortogonali'),
('ascia','doppia a tagli paralleli'),
('ascia','piatta a lama espansa'),
('ascia','piatta a spuntoni'),
('ascia','piatta con due occhielli laterali'),
('ascia','cannone'),
('ascia','costolatura'),
('ascia','fusto'),
('ascia','imboccatura'),
('ascia','immanicatura'),
('ascia','lama'),
('ascia','occhiello laterale'),
('ascia','occhio'),
('ascia','rebbio'),
('ascia','spalla'),
('ascia','taglio'),
('cuneo','asta'),
('cuneo','taglio'),
('cuneo','testa'),
('foculo','per uso cerimoniale'),
('foculo','per uso domestico'),
('fornello','a ferro di cavallo'),
('fornello','traforato'),
('lingotto','ox-hide'),
('martello','testa'),
('matrice','di fusione'),
('matrice','di lucerna'),
('matrice','di piatto'),
('matrice','di statuetta'),
('matrice','di testina'),
('matrice','per bollo'),
('matrice','per bollo in planta pedis'),
('matrice','per focacce'),
('matrice','per utensili'),
('matrice','bivalve'),
('matrice','monovalve'),
('matrice','multipla'),
('matrice','valva'),
('peso','da lenza'),
('peso','da pozzo'),
('peso','da rete'),
('peso','da telaio'),
('peso','di filo a piombo'),
('peso','di stadera'),
('peso','troncopiramidale'),
('peso','troncoconico'),
('piccozza','occhio'),
('pipa','cannello'),
('scalpello','a taglio piatto'),
('scalpello','sgorbia'),
('scalpello','asta'),
('scalpello','immanicatura'),
('scalpello','immanicatura a cannone'),
('scalpello','fermo'),
('sgorbia','asta'),
('sgorbia','immanicatura'),
('sgorbia','immanicatura a cannone'),
('sgorbia','fermo'),
('spiedo','punta'),
('spiedo','stelo'),
('spiedo','testa'),
('spiedo','testa a cubo'),
('spiedo','testa a globo'),
('spiedo','testa a riccio'),
('spiedo','testa a rotolo'),
('strumento','agricolo'),
('strumento','chirurgico'),
('strumento','domestico'),
('strumento','musicale'),
('traino','su due ruote'),
('trapano','a volano'),
('briglia','testiera'),
('briglia','morso'),
('briglia','redini'),
('cinghia','caudale'),
('cinghia','pettorale'),
('finimento','elemento decorativo'),
('finimento','pendente'),
('morso','anello'),
('morso','filetto'),
('morso','montante'),
('morso','tirante'),
('pettorale','equino'),
('sella','a quattro corni'),
('sella','arcione'),
('sella','staffa'),
('sottopancia','fibbia'),
('aratro','bure'),
('aratro','carrello'),
('aratro','catena di aggancio'),
('aratro','coltro'),
('aratro','dentale'),
('aratro','orecchio'),
('aratro','petto'),
('aratro','stegola'),
('aratro','vomere'),
('coltello','da macchia'),
('coltello','codolo'),
('coltello','fodero'),
('coltello','immanicatura'),
('coltello','impugnatura'),
('coltello','lama'),
('coltello','manico'),
('coltello','punta'),
('falce','lama'),
('falce','lama accessoria'),
('falce','dorso'),
('falce','costolatura'),
('falce','sperone'),
('falce','immanicatura a cannone'),
('falce','immanicatura a codolo'),
('falce','immanicatura ad alette'),
('falcetto','lama'),
('falcetto','lama accessoria'),
('falcetto','dorso'),
('falcetto','costolatura'),
('falcetto','sperone'),
('falcetto','immanicatura a cannone'),
('falcetto','immanicatura a codolo'),
('falcetto','immanicatura ad alette'),
('forca','manico'),
('forca','forcella'),
('forcone','rebbio'),
('macina','da mulino'),
('macina','meta'),
('pala','rituale'),
('pala','votiva'),
('pala','a cannone'),
('pala','immanicatura'),
('pala','lama'),
('pala','manico'),
('piccone','braccio'),
('piccone','punta'),
('piccone','occhio'),
('rastrello','manico'),
('rastrello','rebbio'),
('roncola','arboraria'),
('roncola','putatoria'),
('roncola','lama'),
('roncola','lama accessoria'),
('roncola','dorso'),
('roncola','costolatura'),
('roncola','sperone'),
('roncola','immanicatura a cannone'),
('roncola','immanicatura a codolo'),
('roncola','immanicatura ad alette'),
('vanga','lama'),
('vanga','staffale'),
('zappa','lama'),
('zappa','manico'),
('coverta di maglia','testiera'),
('coverta di maglia','collo'),
('coverta di maglia','groppiera'),
('coverta di maglia','girello'),
('paragnatide','con terminale arrotondato'),
('paragnatide','con terminale avvolgente'),
('paragnatide','con terminale a punta trilobata'),
('pettorale','da parata'),
('pettorale','a clessidra'),
('pettorale','regolare'),
('proteggidita','per arco'),
('sprone','a brocco'),
('sprone','a paletto'),
('sprone','a rotella'),
('sprone','a tallone'),
('angone','immanicatura'),
('angone','punta'),
('daga','lama'),
('daga','impugnatura'),
('daga','pomello'),
('falcata','con fodero'),
('falcata','bottone'),
('falcata','cintura di sospensione'),
('falcata','codolo'),
('falcata','dorso'),
('falcata','elsa'),
('falcata','filo'),
('falcata','fodero'),
('falcata','ghiera'),
('falcata','impugnatura'),
('falcata','lama'),
('falcata','immanicatura'),
('falcata','pomo'),
('falcata','punta'),
('falcata','punta ogivata'),
('falcata','punta arrotondata'),
('falcata','sguscio'),
('falcata','sgusciatura'),
('francisca','scure'),
('francisca','collo della scure'),
('francisca','ghiera'),
('francisca','gorbia'),
('francisca','manico'),
('giavellotto','immanicatura'),
('giavellotto','punta'),
('gladio','con fodero'),
('gladio','di tipo Hispaniensis'),
('gladio','di tipo Mainz'),
('gladio','di tipo Pompei'),
('gladio','bottone'),
('gladio','cintura di sospensione'),
('gladio','codolo'),
('gladio','dorso'),
('gladio','elsa'),
('gladio','filo'),
('gladio','fodero'),
('gladio','ghiera'),
('gladio','impugnatura'),
('gladio','lama'),
('gladio','immanicatura'),
('gladio','pomo'),
('gladio','punta'),
('gladio','punta ogivata'),
('gladio','punta arrotondata'),
('gladio','sguscio'),
('gladio','sgusciatura'),
('kopis','bottone'),
('kopis','cintura di sospensione'),
('kopis','codolo'),
('kopis','dorso'),
('kopis','elsa'),
('kopis','filo'),
('kopis','fodero'),
('kopis','ghiera'),
('kopis','impugnatura'),
('kopis','lama'),
('kopis','immanicatura'),
('kopis','pomo'),
('kopis','punta'),
('kopis','punta ogivata'),
('kopis','punta arrotondata'),
('kopis','sguscio'),
('kopis','sgusciatura'),
('lancia','di stendardo'),
('lancia','asta'),
('lancia','immanicatura'),
('lancia','punta'),
('lancia','sauroter'),
('lancia','tallone'),
('lancia','calzuolo'),
('mazza','chiodata'),
('mazza','ferrata'),
('mazza','cuspide'),
('mazza','impugnatura'),
('mazza','manico'),
('mazza','testa'),
('paloscio','con fodero'),
('parazonio','con fodero'),
('parazonio','bottone'),
('parazonio','cintura di sospensione'),
('parazonio','codolo'),
('parazonio','dorso'),
('parazonio','elsa'),
('parazonio','filo'),
('parazonio','fodero'),
('parazonio','ghiera'),
('parazonio','impugnatura'),
('parazonio','lama'),
('parazonio','immanicatura'),
('parazonio','pomo'),
('parazonio','punta'),
('parazonio','punta ogivata'),
('parazonio','punta arrotondata'),
('parazonio','sguscio'),
('parazonio','sgusciatura'),
('pilum','con attacco a codolo largo'),
('pilum','con attacco a manicotto'),
('pilum','con codolo a punta'),
('pilum','con codolo piatto'),
('pilum','canotto di bloccaggio'),
('pugnale','a elsa gammata'),
('pugnale','a lingua da presa'),
('pugnale','con fodero'),
('pugnale','con lama ovale'),
('pugnale','con lama ovale e impugnatura traforata'),
('pugnale','con lama triangolare'),
('pugnale','fodero'),
('pugnale','impugnatura'),
('pugnale','lama'),
('pugnale','pomolo'),
('pugnale','punta'),
('scramasax','corto (Kurzsax)'),
('scramasax','medio-corto'),
('scramasax','medio'),
('scramasax','lungo (Langsax),'),
('spada','da parata'),
('spada','votiva'),
('spada','a lingua da presa'),
('spada','a lingua da presa italica'),
('spada','a manico pieno'),
('spada','a pomo globulare'),
('spada','ad anello'),
('spada','ad antenne'),
('spada','ad antenne di tipo ricurvo'),
('spada','con impugnatura fenestrata'),
('spada','con lama larga a profilo sinuoso'),
('spada','con lama assottigliata in punta'),
('spada','con costolatura centrale marcata'),
('spada','con fodero'),
('spada','vichinga'),
('spada','bottone'),
('spada','cintura di sospensione'),
('spada','codolo'),
('spada','dorso'),
('spada','elsa'),
('spada','filo'),
('spada','fodero'),
('spada','ghiera'),
('spada','impugnatura'),
('spada','lama'),
('spada','immanicatura'),
('spada','pomo'),
('spada','punta'),
('spada','punta ogivata'),
('spada','punta arrotondata'),
('spada','sguscio'),
('spada','sgusciatura'),
('spatha','di tipo Straubing-Nydam'),
('spatha','di tipo Lauriacum'),
('spatha','germanica'),
('spatha','franco-alamanna'),
('spatha','longobarda'),
('spatha','germano-burgunda'),
('spatha','nordica'),
('spatha','franca'),
('spatha','bottone'),
('spatha','cintura di sospensione'),
('spatha','codolo'),
('spatha','dorso'),
('spatha','elsa'),
('spatha','filo'),
('spatha','fodero'),
('spatha','ghiera'),
('spatha','impugnatura'),
('spatha','lama'),
('spatha','immanicatura'),
('spatha','pomo'),
('spatha','punta'),
('spatha','punta ogivata'),
('spatha','punta arrotondata'),
('spatha','sguscio'),
('spatha','sgusciatura'),
('xyphos','con fodero'),
('xyphos','bottone'),
('xyphos','cintura di sospensione'),
('xyphos','codolo'),
('xyphos','dorso'),
('xyphos','elsa'),
('xyphos','filo'),
('xyphos','fodero'),
('xyphos','ghiera'),
('xyphos','impugnatura'),
('xyphos','lama'),
('xyphos','immanicatura'),
('xyphos','pomo'),
('xyphos','punta'),
('xyphos','punta ogivata'),
('xyphos','punta arrotondata'),
('xyphos','sguscio'),
('xyphos','sgusciatura'),
('zagaglia','punta'),
('papilio','palo'),
('papilio','picchetto'),
('testuggine','semplice'),
('testuggine','a rostro'),
('bacinetto','con visiera'),
('barbuta','con camaglio'),
('brunia','scaglia'),
('brunia','placchetta'),
('brunia','rotellina'),
('cappuccio di maglia','bavero'),
('corazza','a corpetto'),
('corazza','a fasce'),
('corazza','a scaglie'),
('corazza','a tre dischi'),
('corazza','ad anelli'),
('corazza','campaniforme'),
('corazza','muscolare'),
('corazza','muscolare bivalve'),
('corazza','trilobata'),
('corazza','anello'),
('corazza','cerniera'),
('corazza','fibbia'),
('corazza','maglie'),
('corazza','pettorale'),
('corazza','piastra'),
('corazza','rinforzo spallare'),
('corazza','valva'),
('elmo','da parata'),
('elmo','gladiatorio'),
('elmo','a bottone (celto-italico)'),
('elmo','a calotta'),
('elmo','a calotta composita'),
('elmo','a calotta composita a doppia cresta'),
('elmo','a calotta sagomata'),
('elmo','a coppa conica'),
('elmo','a campana allungata'),
('elmo','a gola con borchie'),
('elmo','a lamelle'),
('elmo','a maschera'),
('elmo','a nasale'),
('elmo','a testa di ariete'),
('elmo','a pilos'),
('elmo','a pilos ellenistico'),
('elmo','a pseudobandelle'),
('elmo','a spicchi a bandelle'),
('elmo','a visiera'),
('elmo','apulo-corinzio'),
('elmo','attico'),
('elmo','beotico'),
('elmo','beotico protocorinzio'),
('elmo','beotico ellenistico'),
('elmo','calcidese'),
('elmo','celto-italico'),
('elmo','conico'),
('elmo','corinzio'),
('elmo','crestato'),
('elmo','da cavalleria'),
('elmo','della fanteria ausiliaria'),
('elmo','di tipo Agen-Port'),
('elmo','di tipo Buggenum'),
('elmo','di tipo Coolus'),
('elmo','di tipo Montefortino'),
('elmo','di tipo Negau'),
('elmo','euro-orientale a lamelle'),
('elmo','frigio'),
('elmo','frigio alato'),
('elmo','greco-italico'),
('elmo','imperiale gallico'),
('elmo','imperiale italico'),
('elmo','nordgermanico a bandelle'),
('elmo','nordgermanico a maschera'),
('elmo','ostrogoto-franco a spicchi'),
('elmo','piceno-corinzio'),
('elmo','pseudo-attico'),
('elmo','russo a spicchi'),
('elmo','tardoromano a spicchi'),
('elmo','sud-italico calcidese'),
('elmo','tracio'),
('elmo','con aperture aurali'),
('elmo','con paragnatidi'),
('elmo','con paragnatidi a forma di testa di ariete'),
('elmo','con paranuca'),
('elmo','apex'),
('elmo','bandella'),
('elmo','borchia'),
('elmo','calotta'),
('elmo','calotta a giorno'),
('elmo','camaglio'),
('elmo','cerchiatura'),
('elmo','cielo'),
('elmo','coppo'),
('elmo','costola'),
('elmo','cresta'),
('elmo','fermezza'),
('elmo','frontale'),
('elmo','gronda'),
('elmo','guanciale'),
('elmo','guardanuca di maglia'),
('elmo','lamella'),
('elmo','lingua della spranga'),
('elmo','listello'),
('elmo','nasale'),
('elmo','pennacchiera'),
('elmo','piede della spranga'),
('elmo','placchetta di rivestimento'),
('elmo','pomolo'),
('elmo','pseudobandella'),
('elmo','punta'),
('elmo','reggicresta'),
('elmo','ribattino'),
('elmo','semicalotta'),
('elmo','spicchio'),
('elmo','spranga'),
('elmo','supporto per piumaggio'),
('elmo','visiera a maschera'),
('farsetto da armare','gola di maglia'),
('farsetto da armare','ditello'),
('farsetto da armare','sottobraccio'),
('guanto','da presa'),
('guanto','stecca'),
('linothorax','humeralis'),
('maglia','chiodata in mezzo'),
('maglia','chiodata in alto'),
('maglia','a grano d''orzo'),
('maglia','ghiazzerina'),
('piastra','dorsale'),
('piastra','pettorale'),
('piastra','rettangolare'),
('schiniere','con incavo per il piede'),
('schiniere','con ginocchio sagomato'),
('scudo','da cerimonia'),
('scudo','votivo'),
('scudo','ancile'),
('scudo','circolare'),
('scudo','dypilon'),
('scudo','argivo'),
('scudo','alla normanna'),
('scudo','a mandorla'),
('scudo','rettangolare'),
('scudo','triangolare'),
('scudo','attacco per imbracciatura'),
('scudo','borchia'),
('scudo','bordatura'),
('scudo','campo'),
('scudo','custodia'),
('scudo','ferratura'),
('scudo','imbracciatura'),
('scudo','maniglia'),
('scudo','umbone'),
('arco','di tipo composito'),
('arco','di tipo orientale'),
('arco','riflesso'),
('arco','a D'),
('arco','corda'),
('arco','dorso'),
('arco','impugnatura'),
('arco','orecchia'),
('balestra','arco'),
('balestra','corda'),
('balestra','manetta'),
('balestra','noce'),
('balestra','teniere'),
('freccia','d''arco'),
('freccia','di balestra'),
('freccia','di scorpio'),
('freccia','asta'),
('freccia','cannone'),
('freccia','codolo'),
('freccia','impennaggio'),
('freccia','punta'),
('ghianda','missile'),
('proiettile','di fionda'),
('proiettile','a forma biconica'),
('proiettile','a forma ovoidale'),
('proiettile','a forma piramidale'),
('proiettile','a forma amigdaloide'),
('proiettile','fusiforme'),
('proiettile','glandiforme'),
('ago','da rete'),
('amo','da pesca'),
('fiocina','immanicatura'),
('fiocina','ponte'),
('fiocina','aculei'),
('rete','da caccia'),
('rete','da pesca'),
('alabastron','a fondo appuntito'),
('alabastron','con due anse impostate sul corpo'),
('alabastron','con peduccio'),
('alabastron','con un''ansa impostata sul collo'),
('alabastron','collo'),
('alabastron','fondo'),
('alabastron','orlo'),
('alabastron','parete'),
('alabastron','spalla'),
('ampolla','olearia'),
('ampolla','collo'),
('ampolla','fondo'),
('ampolla','orlo'),
('ampolla','parete'),
('ampolla','piede'),
('ampolla','spalla'),
('anfora','da mensa'),
('anfora','da trasporto'),
('anfora','uso funerario'),
('anfora','vinaria'),
('anfora','olearia'),
('anfora','ansa'),
('anfora','collo'),
('anfora','fondo'),
('anfora','orlo'),
('anfora','parete'),
('anfora','puntale'),
('anfora','spalla'),
('anforisco','ansa'),
('anforisco','collo'),
('anforisco','fondo'),
('anforisco','orlo'),
('anforisco','parete'),
('anforisco','piede'),
('anforisco','spalla'),
('aryballos','lenticolare'),
('aryballos','ansa'),
('aryballos','collo'),
('aryballos','fondo'),
('aryballos','orlo'),
('aryballos','parete'),
('aryballos','piede'),
('aryballos','spalla'),
('askos','da parata'),
('askos','a otre adagiato'),
('askos','ansa'),
('askos','beccuccio'),
('askos','bocchello'),
('askos','collo'),
('askos','fondo'),
('askos','orlo'),
('askos','parete'),
('askos','piede'),
('askos','spalla'),
('astuccio','per filatterio'),
('astuccio','portamuleti'),
('astuccio','portapennelli'),
('attingitoio','da bagno'),
('bacile','votivo'),
('bacile','fondo'),
('bacile','orlo'),
('bacile','parete'),
('bacinella','fondo'),
('bacinella','orlo'),
('bacinella','parete'),
('balsamario','corpo a sezione cilindrica'),
('balsamario','corpo a sezione conica'),
('balsamario','corpo a sezione discoidale'),
('balsamario','corpo a sezione lenticolare'),
('balsamario','corpo a sezione ovoidale'),
('balsamario','corpo a sezione piriforme'),
('balsamario','corpo a sezione sferica'),
('balsamario','corpo a sezione tronco-conica'),
('balsamario','corpo a sezione tubolare'),
('balsamario','collo'),
('balsamario','fondo'),
('balsamario','orlo'),
('balsamario','parete'),
('balsamario','piede'),
('balsamario','spalla'),
('bicchiere','a piede'),
('bicchiere','a sacchetto'),
('bicchiere','campaniforme'),
('bicchiere','carenato'),
('bicchiere','cilindrico'),
('bicchiere','conico'),
('bicchiere','con corpo a bulbo'),
('bicchiere','con corpo ovoidale'),
('bicchiere','con corpo parallelepipedo'),
('bicchiere','con decorazione a bugne'),
('bicchiere','con piede a protuberanze'),
('bicchiere','monoansato'),
('bicchiere','(modiolus)'),
('bicchiere','troncoconico'),
('bicchiere','fondo'),
('bicchiere','orlo'),
('bicchiere','parete'),
('bicchiere','piede'),
('bicchiere','spalla'),
('biconico','carena'),
('biconico','coperchio'),
('biconico','fondo'),
('biconico','orlo'),
('biconico','parete'),
('biconico','piede'),
('biconico','spalla'),
('boccale','ansa'),
('boccale','collo'),
('boccale','fondo'),
('boccale','orlo'),
('boccale','parete'),
('boccale','spalla'),
('bombylios','collo'),
('bombylios','fondo'),
('bombylios','orlo'),
('bombylios','parete'),
('bombylios','piede'),
('bombylios','spalla'),
('bottiglia','biansata'),
('bottiglia','corpo a sezione cilindrica'),
('bottiglia','corpo a sezione esagonale'),
('bottiglia','corpo a sezione ottagonale'),
('bottiglia','corpo a sezione quadrata'),
('bottiglia','corpo a sezione rettangolare'),
('bottiglia','frontiniana'),
('bottiglia','mercuriale'),
('bottiglia','monoansata'),
('bottiglia','ansa'),
('bottiglia','collo'),
('bottiglia','fondo'),
('bottiglia','orlo'),
('bottiglia','parete'),
('bottiglia','piede'),
('bottiglia','spalla'),
('braciere','rituale'),
('braciere','per riscaldamento'),
('braciere','per cottura di cibi'),
('brocca','attingitoio'),
('brocca','da farmacia'),
('brocca','poppatoio'),
('brocca','a bulbo'),
('brocca','a ciambella'),
('brocca','askoide'),
('brocca','cilindrica'),
('brocca','conica'),
('brocca','con orlo a fungo'),
('brocca','con orlo trilobato'),
('brocca','globulare'),
('brocca','lenticolare'),
('brocca','ovoidale'),
('brocca','ansa'),
('brocca','collo'),
('brocca','fondo'),
('brocca','orlo'),
('brocca','parete'),
('brocca','piede'),
('brocca','spalla'),
('bruciaprofumi','a doppia vasca'),
('calderone','a spalla piatta'),
('calderone','a fondo arrotondato'),
('calderone','gancio'),
('calice','potorio'),
('calice','fondo'),
('calice','orlo'),
('calice','parete'),
('calice','piede'),
('cassetta','per ushabti'),
('chous','collo'),
('chous','fondo'),
('chous','orlo'),
('chous','parete'),
('chous','piede'),
('chous','spalla'),
('ciotola','carenata'),
('ciotola','triansata'),
('ciotola','su sostegno'),
('ciotola','orlo'),
('ciotola','fondo'),
('ciotola','parete'),
('cofanetto','da cosmesi'),
('cofanetto','antropomorfo'),
('cofanetto','serratura'),
('cofano','su quattro piedi'),
('cofano','su ruote'),
('colino','rituale'),
('coperchio','a calotta'),
('coperchio','a incastro'),
('coperchio','a tetto di capanna'),
('coperchio','conico'),
('coperchio','globulare'),
('coperchio','ansa'),
('coperchio','labbro'),
('coperchio','bottone'),
('coperchio','orlo'),
('coperchio','parete'),
('coperchio','presa'),
('coperchio','tesa'),
('coppa','a conchiglia'),
('coppa','a parete convessa'),
('coppa','a parete verticale'),
('coppa','ad arco di cerchio'),
('coppa','biansata'),
('coppa','biconica'),
('coppa','carenata'),
('coppa','costolata'),
('coppa','diatreta'),
('coppa','emisferica'),
('coppa','monoansata'),
('coppa','ovoidale'),
('coppa','piriforme'),
('coppa','tronco-conica'),
('coppa','collo'),
('coppa','fondo'),
('coppa','orlo'),
('coppa','parete'),
('coppa','piede'),
('cratere','a campana'),
('cratere','a colonnette'),
('cratere','(kelebe)'),
('cratere','ansa'),
('cratere','collo'),
('cratere','fondo'),
('cratere','orlo'),
('cratere','parete'),
('cratere','piede'),
('cratere','spalla'),
('deinos','con anse ad anello'),
('deinos','con anse a rocchetto'),
('deinos','collo'),
('deinos','fondo'),
('deinos','orlo'),
('deinos','parete'),
('deinos','piede'),
('deinos','spalla'),
('doglio','collo'),
('doglio','fondo'),
('doglio','orlo'),
('doglio','parete'),
('doglio','spalla'),
('faretra','fascetta'),
('fiasca','da pellegrino'),
('fiasca','ansa'),
('fiasca','collo'),
('fiasca','fondo'),
('fiasca','orlo'),
('fiasca','parete'),
('fiasca','piede'),
('fiasca','spalla'),
('fodero','borchiapuntale'),
('fodero','guarnizione'),
('fodero','serra-fodero'),
('fodero','staffa a ponticello'),
('glaux','potorio'),
('glaux','ansa'),
('glaux','fondo'),
('glaux','orlo'),
('glaux','parete'),
('glaux','piede'),
('guttus','ansa'),
('guttus','beccuccio'),
('guttus','fondo'),
('guttus','orlo'),
('guttus','parete'),
('guttus','piede'),
('hydria','ansa'),
('hydria','collo'),
('hydria','fondo'),
('hydria','orlo'),
('hydria','parete'),
('hydria','piede'),
('hydria','spalla'),
('hydriska','ansa'),
('hydriska','collo'),
('hydriska','fondo'),
('hydriska','orlo'),
('hydriska','parete'),
('hydriska','piede'),
('hydriska','spalla'),
('kados','per attingere'),
('kalpis','ansa'),
('kalpis','collo'),
('kalpis','fondo'),
('kalpis','orlo'),
('kalpis','parete'),
('kalpis','piede'),
('kalpis','spalla'),
('kantharos','potorio'),
('kantharos','ansa'),
('kantharos','fondo'),
('kantharos','orlo'),
('kantharos','parete'),
('kantharos','piede'),
('kernos','a forma di torricella'),
('kothon','ansa'),
('kothon','collo'),
('kothon','fondo'),
('kothon','orlo'),
('kothon','parete'),
('kothon','piede'),
('kothon','spalla'),
('kotyle','potoria'),
('kotyle','ansa'),
('kotyle','fondo'),
('kotyle','orlo'),
('kotyle','parete'),
('kotyle','piede'),
('kyathos','attingitoio'),
('kyathos','potorio'),
('kyathos','ansa'),
('kyathos','fondo'),
('kyathos','orlo'),
('kyathos','parete'),
('kyathos','piede'),
('kylix','potoria'),
('kylix','ansa'),
('kylix','fondo'),
('kylix','orlo'),
('kylix','parete'),
('kylix','piede'),
('lagynos','ansa'),
('lagynos','collo'),
('lagynos','fondo'),
('lagynos','orlo'),
('lagynos','parete'),
('lagynos','piede'),
('lagynos','spalla'),
('lebete','nuziale'),
('lebete','(lebes gamikos)'),
('lebete','con orlo liscio'),
('lebete','con fondo arrotondato'),
('lebete','con orlo ripiegato'),
('lebete','ansa'),
('lebete','collo'),
('lebete','fondo'),
('lebete','orlo'),
('lebete','parete'),
('lebete','piede'),
('lebete','spalla'),
('lekanis','carenata'),
('lekanis','con pareti tese'),
('lekanis','ansa'),
('lekanis','collo'),
('lekanis','fondo'),
('lekanis','orlo'),
('lekanis','parete'),
('lekanis','piede'),
('lekanis','spalla'),
('lekithos','rituale'),
('lekithos','ansa'),
('lekithos','collo'),
('lekithos','fondo'),
('lekithos','orlo'),
('lekithos','parete'),
('lekithos','piede'),
('lekithos','spalla'),
('loutrophoros','nuziale'),
('loutrophoros','funerario'),
('loutrophoros','ansa'),
('loutrophoros','collo'),
('loutrophoros','orlo'),
('loutrophoros','parete'),
('loutrophoros','piede'),
('loutrophoros','spalla'),
('lydion','collo'),
('lydion','orlo'),
('lydion','parete'),
('lydion','piede'),
('lydion','spalla'),
('mastos','con un''ansa orizzontale e una verticale'),
('mastos','ansa'),
('mastos','orlo'),
('mastos','parete'),
('mastos','spalla'),
('mortaio','per cereali'),
('mortaio','votivo'),
('mortaio','con colatoio'),
('mortaio','con pestello'),
('mortaio','con versatoio'),
('mortaio','tripode'),
('oinochoe','a becco'),
('oinochoe','a becco tipo Schnabelkanne'),
('oinochoe','con corpo biconico'),
('oinochoe','ansa'),
('oinochoe','collo'),
('oinochoe','orlo'),
('oinochoe','parete'),
('oinochoe','piede'),
('oinochoe','spalla'),
('olla','funeraria'),
('olla','votiva'),
('olla','a tesa interna'),
('olla','biansata'),
('olla','biconica'),
('olla','con alto piede svasato'),
('olla','con beccuccio'),
('olla','con bugne tra le anse'),
('olla','con ciotola di copertura'),
('olla','ansa'),
('olla','collo'),
('olla','fondo'),
('olla','orlo'),
('olla','parete'),
('olla','spalla'),
('olpe','per attingere'),
('olpe','a ventre conico'),
('olpe','a ventre ribassato'),
('olpe','a ventre sferoidale'),
('olpe','piriforme'),
('padella','ovale'),
('paiolo','a ventre lenticolare'),
('paiolo','a ventre espanso'),
('patera','a vasca arrotondata'),
('patera','con coperchio'),
('pelike','ansa'),
('pelike','collo'),
('pelike','fondo'),
('pelike','orlo'),
('pelike','parete'),
('pentola','rituale'),
('phiale','ombelicata'),
('piatto','coperchio'),
('piatto','da frutta'),
('piatto','da pesce'),
('piatto','di largizione'),
('piatto','portauovo'),
('piatto','apodo'),
('piatto','circolare con piede ad anello'),
('piatto','tetrapode con protome zoomorfa'),
('pisside','cilindrica'),
('pisside','tripode'),
('pithos','ansa'),
('pithos','collo'),
('pithos','fondo'),
('pithos','orlo'),
('pithos','parete'),
('pithos','piede'),
('pithos','spalla'),
('poculum','fondo'),
('poculum','orlo'),
('poculum','parete'),
('poculum','piede'),
('poculum','spalla'),
('psykter','con anse a occhiello'),
('psykter','con coperchio'),
('psykter','con prese forate'),
('psykter','ansa'),
('psykter','collo'),
('psykter','orlo'),
('psykter','parete'),
('psykter','piede'),
('psykter','spalla'),
('recipiente','forma aperta'),
('recipiente','forma chiusa'),
('recipiente','ansa'),
('recipiente','beccuccio'),
('recipiente','carena'),
('recipiente','collo'),
('recipiente','corpo'),
('recipiente','fondo'),
('recipiente','manico'),
('recipiente','orlo'),
('recipiente','parete'),
('recipiente','piede'),
('recipiente','presa'),
('recipiente','puntale'),
('recipiente','spalla'),
('recipiente','tappo'),
('recipiente','tesa'),
('sarcina','furca'),
('secchio','da pozzo'),
('secchio','coperchio'),
('secchio','manico'),
('situla','cilindrica'),
('situla','con applique'),
('situla','doppia'),
('situla','ovoide'),
('situla','priva di collarino'),
('skyphos','potorio'),
('stamnos','ansa'),
('stamnos','collo'),
('stamnos','fondo'),
('stamnos','orlo'),
('stamnos','parete'),
('stamnos','piede'),
('stamnos','spalla'),
('tazza','attingitoio'),
('tegame','per uova'),
('teglia','con ansa mobile'),
('testo','da pane'),
('testo','orlo'),
('thymiaterion','orlo'),
('thymiaterion','piede'),
('trozzella','ansa'),
('trozzella','collo'),
('trozzella','fondo'),
('trozzella','orlo'),
('trozzella','parete'),
('trozzella','piede'),
('trozzella','spalla'),
('unguentario','con collo allungato'),
('unguentario','con corto collo'),
('unguentario','con piede allungato'),
('unguentario','fusiforme'),
('unguentario','lekythoide'),
('unguentario','piriforme'),
('unguentario','su basso piede'),
('vaso','da cucina'),
('vaso','da fiori'),
('vaso','di misurazione'),
('vaso','funerario'),
('vaso','per spezie'),
('vaso','portaprofumi'),
('vaso','potorio'),
('vaso','silos'),
('vaso','a bollilatte'),
('vaso','a botticella'),
('vaso','a calamaio'),
('vaso','a clessidra'),
('vaso','a paniere'),
('vaso','a ventre ellissoidale'),
('vaso','a ventre ovoidale'),
('vaso','con appendici interne'),
('vaso','cefalomorfo'),
('vaso','con ansa a ponte'),
('vaso','configurato'),
('vaso','con versatoio'),
('vaso','ellittico'),
('vaso','globulare'),
('vaso','ovoidale'),
('vaso','piriforme'),
('vaso','plastico'),
('vaso','quadriansato'),
('vaso','tripode'),
('vaso','troncoconico'),
('vassoio','circolare'),
('vassoio','circolare biansato'),
('vassoio','trilobato'),
('ago','da cucito'),
('ago','da lana'),
('fuseruola','a superficie baccellata'),
('fuseruola','a superficie liscia'),
('fuseruola','a superficie sfaccettata'),
('fuseruola','a superficie strigilata'),
('fuso','disco'),
('pettine','per lino'),
('rocchetto','capocchia'),
('anello','apicale'),
('anello','da presa'),
('anello','da sospensione'),
('anello','distanziatore'),
('anello','reggispiedi'),
('battacchio','piastra'),
('battacchio','snodo'),
('battacchio','testa'),
('battacchio','incudine'),
('catena','portaspada'),
('catena','con anelli punzonati'),
('catena','con maglie a otto'),
('catena','anello'),
('cerniera','perno di snodo'),
('cerniera','lama fissa'),
('cerniera','lama mobile'),
('chiave','da mobile'),
('chiave','da porta'),
('chiave','templare'),
('chiave','a T'),
('chiave','a scorrimento'),
('chiave','impugnatura'),
('chiave','occhiello'),
('chiave','stelo'),
('chiave','mappa'),
('chiave','pettine'),
('chiodo','per caligae'),
('chiodo','a testa conica'),
('chiodo','a testa piramidale'),
('chiodo','testa'),
('chiodo','gambo'),
('lamina','di rivestimento'),
('lamina','votiva'),
('placca','di rivestimento'),
('serratura','da cassone'),
('serratura','da porta'),
('serratura','da portone'),
('serratura','boncinello'),
('serratura','chiavistello'),
('serratura','piastra di copertura'),
('serratura','stanghetta'),
('uncino','punta'),
('molla','da fuoco'),
('paletta','da fonditore'),
('bambola','braccio'),
('bambola','gamba'),
('bambola','testa'),
('dado','da gioco'),
('pedina','da gioco'),
('tavoletta','da gioco'),
('ago','crinale'),
('ago','(acus discriminalis)'),
('fermaglio','per capelli'),
('pinzetta','depilatoria'),
('rasoio','bitagliente'),
('rasoio','bitagliente a lama larga'),
('rasoio','bitagliente a lama stretta'),
('rasoio','lunato'),
('rasoio','lunato con dorso a sperone e ad angolo'),
('rasoio','lunato con dorso a curva interrotta'),
('rasoio','lunato con dorso a curva continua'),
('rasoio','lunato con dorso a linguetta'),
('rasoio','lama'),
('rasoio','linguetta'),
('rasoio','manico'),
('scrigno','cerniera'),
('spatola','da toeletta'),
('tavoletta','per cosmetici'),
('candelabro','braccio'),
('candelabro','cimasa'),
('candelabro','fusto'),
('candelabro','tripode'),
('lampada','a sospensione con anse'),
('lampada','conica'),
('lampada','imbutiforme'),
('lampada','ansa'),
('lucerna','cuoriforme'),
('lucerna','troncoconica'),
('lucerna','ansa'),
('lucerna','becco'),
('lucerna','disco'),
('lucerna','fondo'),
('lucerna','gancio'),
('lucerna','orlo'),
('lucerna','parete'),
('lucerna','presa'),
('lucerna','serbatoio'),
('lucerna','spalla'),
('lucerna','stelo'),
('lucerna','vasca'),
('ancora','ceppo'),
('ancora','contromarra'),
('ancora','gomena'),
('ancora','marra'),
('remo','direzionale'),
('remo','pala'),
('timone','testata'),
('becco','su punta'),
('becco','su troncatura'),
('bifacciale','ad estremità sbiecata'),
('bifacciale','misto'),
('bifacciale','nucleiforme'),
('bifacciale','parziale'),
('bifacciale','piatto'),
('bifacciale','piatto a mandorla'),
('bifacciale','piatto cordiforme'),
('bifacciale','piatto cordiforme allungato'),
('bifacciale','piatto discoide'),
('bifacciale','piatto naviforme'),
('bifacciale','piatto ovalare'),
('bifacciale','piatto subcordiforme'),
('bifacciale','piatto subtriangolare'),
('bifacciale','piatto triangolare'),
('bifacciale','piatto triangolare allungato'),
('bifacciale','spesso'),
('bifacciale','spesso a cuneo'),
('bifacciale','spesso amigdaloide'),
('bifacciale','spesso lageniforme'),
('bifacciale','spesso lanceolato'),
('bifacciale','spesso micocchiano'),
('bifacciale','abbozzo'),
('bifacciale','punta'),
('bulino','per incidere'),
('bulino','semplice ad uno stacco'),
('bulino','semplice a due stacchi laterali'),
('bulino','semplice a due stacchi, laterale e trasversale'),
('bulino','semplice con ritocco d''arresto'),
('bulino','su frattura'),
('bulino','su ritocco trasversale a stacco laterale'),
('bulino','su ritocco laterale a stacco laterale'),
('bulino','su ritocco laterale a stacco trasversale'),
('bulino','su ritocco a ritocco d''arresto'),
('chopper','a punta'),
('chopper','distale'),
('chopper','doppio'),
('chopper','laterale'),
('foliato','a faccia piana'),
('foliato','bifacciale'),
('foliato','a cran'),
('foliato','geometrico'),
('geometrico','a segmento'),
('geometrico','a segmento trapezoidale'),
('geometrico','a trapezio isoscele'),
('geometrico','a trapezio rettangolo'),
('geometrico','a trapezio scaleno'),
('geometrico','a triangolo isoscele'),
('geometrico','a triangolo scaleno'),
('geometrico','romboide'),
('grattatoio','frontale'),
('grattatoio','frontale circolare'),
('grattatoio','frontale corto'),
('grattatoio','frontale corto a ritocco laterale'),
('grattatoio','frontale lungo'),
('grattatoio','frontale lungo a ritocco laterale'),
('grattatoio','a muso'),
('grattatoio','a muso isolato'),
('grattatoio','a muso ogivale'),
('grattatoio','carenato'),
('grattatoio','carenato a muso'),
('grattatoio','carenato frontale'),
('hachereau','a margini divergenti o a V'),
('hachereau','a margini paralleli o ad U'),
('hachereau','a margini convergenti'),
('hachereau','a margine tagliente ristretto'),
('lama','a dorso e troncatura normale'),
('lama','a dorso e troncatura doppia'),
('lama','a dorso e troncatura obliqua formanti angolo acuto'),
('lama','lama a dorso e troncatura obliqua formanti angolo ottuso'),
('lama','lama a dorso e troncatura doppia non simmetrica'),
('lama','a dorso e piquant- trièdre'),
('lama raschiatoio','carenoide'),
('lama raschiatoio','marginale'),
('nucleo','a un piano di percussione'),
('nucleo','a due piani di percussione'),
('nucleo','a lame'),
('nucleo','abbozzo'),
('punta','di freccia'),
('punta','a spalla'),
('punta','carenoide'),
('punta','curva'),
('punta','marginale'),
('punta a dorso','marginale'),
('punta a dorso','parziale rettilineo o convesso'),
('punta a dorso','parziale concavo'),
('punta a dorso','totale'),
('punta a dorso','e cran adiacente'),
('punta a dorso','e cran opposto'),
('punta a dorso','e peduncolo'),
('raschiatoio','carenoide'),
('raschiatoio','laterale'),
('raschiatoio','latero-trasversale'),
('raschiatoio','marginale'),
('raschiatoio','trasversale'),
('scheggia','a ritocco erto'),
('scheggia','bulbo'),
('scheggia','faccia dorsale'),
('scheggia','faccia ventrale'),
('scheggia','tallone'),
('lesina','manico'),
('lesina','punteruolo'),
('lima','codolo'),
('lima','fermo'),
('lisciatoio','con modello di nuraghe'),
('ago','chirurgico'),
('ago','punta'),
('ago','capocchia'),
('bisturi','impugnatura'),
('clessidra','ad acqua'),
('clessidra','a sabbia'),
('groma','ferramentum'),
('groma','rostrum'),
('groma','umbilicus soli'),
('groma','corniculum'),
('groma','perpendiculum'),
('groma','pondus'),
('groma','decussis'),
('stadera','braccio graduato'),
('stadera','catenella'),
('stadera','braccio di sospensione'),
('stadera','peso'),
('stadera','piatto'),
('corno','bocchino'),
('flauto','cilindretto'),
('tibia','capistrum'),
('amuleto','a forma di anatra'),
('amuleto','a forma di ariete'),
('amuleto','a forma di ascia'),
('amuleto','a forma di colonna'),
('amuleto','a forma di conchiglia'),
('amuleto','a forma di corno'),
('amuleto','a forma di corona bianca'),
('amuleto','a forma di corona rossa'),
('amuleto','a forma di faretra'),
('amuleto','a forma di fodero'),
('amuleto','a forma di gatto'),
('amuleto','a forma di leone'),
('amuleto','a forma di maiale'),
('amuleto','a forma di mummia di gatto'),
('amuleto','a forma di nodo'),
('amuleto','a forma di occhio'),
('amuleto','a forma di pesce'),
('amuleto','a forma di piuma'),
('amuleto','a forma di pilastro djed'),
('amuleto','a forma di poggiatesta'),
('amuleto','a forma di pugnale'),
('amuleto','a forma di rana'),
('amuleto','a forma di scarabeo'),
('amuleto','(scarabeo)'),
('amuleto','a forma di serpe'),
('amuleto','a forma di sparviero'),
('amuleto','a forma di statuetta'),
('amuleto','a forma di uccello'),
('amuleto','antropomorfo'),
('amuleto','zoomorfo'),
('corona del rosario','vago'),
('disco','votivo'),
('ex voto','anatomico'),
('ex voto','aniconico'),
('ex voto','vegetale'),
('ex voto','zoomorfo'),
('insegna','araldica'),
('insegna','cerimoniale'),
('insegna','di corte'),
('insegna','votiva'),
('insegna','legionaria'),
('insegna','pretoriana'),
('insegna','puntale'),
('lastrina','votiva'),
('medaglia','devozionale'),
('pinax','votivo'),
('stilo','asticella'),
('coltello','da sacrificio'),
('coltello','da toeletta'),
('coltello','a cannone'),
('coltello','a codolo'),
('coltello','a lingua da presa'),
('coltello','con manico ad anello'),
('coltello','anello terminale'),
('coltello','cannone'),
('coltello','dorso'),
('coltello','lingua da presa'),
('coltello','taglio'),
('cucchiaio','da tavola'),
('forbice','da pastore'),
('forchetta','rebbio'),
('forcone','manico'),
('pestello','da mortaio'),
('posata','manico'),
('simpulum','manico'),
('simpulum','vasca'),
('tintinnabulo','antropomorfo'),
('scarto','di fornace'),
('scarto','di fusione'),
('scarto','di lavorazione');

COMMIT;
