begin;
create table liste.tag(tag character varying primary key);
insert into liste.tag values
  ('abbigliamento'),
  ('animali'),
  ('arredo'),
  ('decoro geometrico'),
  ('divinità'),
  ('edifici'),
  ('figure'),
  ('elementi floreali'),
  ('frutta'),
  ('mezzi di trasporto'),
  ('oggetti'),
  ('personaggi mitologici'),
  ('persone'),
  ('scritte'),
  ('strumenti'),
  ('elementi vegetali');
create table work.tags(
  id serial primary key,
  scheda integer references scheda(id) on delete cascade,
  tag character varying not null,
  unique(scheda,tag)
);
insert into work.tags(scheda, tag) select scheda, 'abbigliamento' from da where fts @@ to_tsquery(
'abbigl:* | abit:* | apex:* | apoptygm:* | armat:* | bend:* | berrett:* | calzar:* | cint:* | clamid:* | copricap:* | crest:* | drapp:* | elmat:* | fiocc:* | frig:* | himation:* | kekryphalos:* | kolpos:* | lemb:* | lemn:* | leont:* | lophos:* | mantell:* | nastrin:* | pannegg:* | pell:* | pennacc:* | pepl:* | pium:* | poderes:* | polos:* | ricam:* | sakkos:* | scoll:* | scollatur:* | sphendon:* | stoff:* | tog:* | vest:*');
insert into work.tags(scheda, tag) select scheda, 'animali' from da where fts @@ to_tsquery('ali:* | animal:* | apex:* | aquil:* | bovin:* | bucran:* | cammell:* | can:* | canin:* | capr:* | caprin:* | caval:* | cavalc:* | cavalier:* | cavall:* | cerbiatt:* | cerv:* | cign:* | cinghial:* | civett:* | cod:* | colomb:* | crinier:* | delfin:* | elef:* | equestr:* | fantin:* | gall:* | galopp:* | giog:* | grif:* | grifon:* | guf:* | ippocamp:* | leon:* | leonin:* | leont:* | lepr:* | lingu:* | lup:* | mus:* | palmiped:* | panter:* | pesc:* | pinn:* | piumagg:* | redin:* | scill:* | scorpion:* | serpent:* | sfing:* | tor:* | uccell:* | volatil:* | zamp:* | zann:* | zoomorf:*');
insert into work.tags(scheda, tag) select scheda, 'arredo' from da where fts @@ to_tsquery('bracciol:* | cavallett:* | curul:* | cuscin:* | diphros:* | schienal:* | sdrai:* | spallier:*');
insert into work.tags(scheda, tag) select scheda, 'decoro geometrico' from da where fts @@ to_tsquery('anthemion:* | cerchiell:* | cerchiett:* | chioccioliform:* | gocc:* | losang:* | onda:* | onde:* | ovol:* | scacchier:* | sigm:* | tondin:* | tremul:* | zag:* | zig:* | zigzag:*');
insert into work.tags(scheda, tag) select scheda, 'divinità' from da where fts @@ to_tsquery('afrod:* | apoll:* | artemid:* | aten:* | bendis:* | cer:* | cupid:* | dian:* | dionis:* | divin:* | eros:* | fulmin:* | giov:* | giunon:* | hermes:* | minerv:* | nettun:* | pan:* | pegas:* | persefon:* | ven:*');
insert into work.tags(scheda, tag) select scheda, 'edifici' from da where fts @@ to_tsquery('archi:* | cas:* | far:* | monument:* | tett:*');
insert into work.tags(scheda, tag) select scheda, 'figure' from da where fts @@ to_tsquery('abbigl:* | abit:* | acant:* | acconciatur:* | addom:* | afrod:* | ala:* | alat:* | ali:* | allor:* | amorin:* | anatom:* | androgin:* | animal:* | anthemion:* | antropomorf:* | apex:* | apoll:* | apoptygm:* | aquil:* | armat:* | artemid:* | arti:* | aten:* | avambracc:* | bacc:* | baff:* | bambin:* | barb:* | barbar:* | barbul:* | bend:* | bendis:* | berrett:* | bocciol:* | bovin:* | bucran:* | calpest:* | calzar:* | cammell:* | can:* | canin:* | cap:* | capell:* | capigliatur:* | cappell:* | capr:* | caprin:* | caval:* | cavalc:* | cavalier:* | cavall:* | centaur:* | cer:* | cerbiatt:* | cerv:* | chignon:* | chiom:* | cign:* | cinghial:* | cint:* | ciocc:* | ciuff:* | civett:* | clamid:* | cod:* | colomb:* | combatt:* | copricap:* | cosc:* | cran:* | crinier:* | crocc:* | cupid:* | danz:* | delfin:* | desultor:* | dian:* | dionis:* | dioscur:* | dit:* | divin:* | donn:* | drapp:* | eder:* | efeb:* | elef:* | elmat:* | equestr:* | eracl:* | ercol:* | eros:* | erot:* | facc:* | fall:* | fanciull:* | fantin:* | felin:* | femminil:* | ferin:* | ficus:* | figur:* | figurin:* | fior:* | fiorellin:* | fitomorf:* | floreal:* | fogliolin:* | frang:* | frig:* | frutt:* | fulmin:* | gall:* | galopp:* | ghign:* | ghirland:* | ginocc:* | giog:* | giov:* | giovan:* | giovanil:* | giunon:* | glute:* | gorgon:* | got:* | grappol:* | gremb:* | grif:* | grifon:* | grottesc:* | guerrier:* | guf:* | hermes:* | himation:* | imberb:* | imbracc:* | incoron:* | individu:* | infant:* | inginocc:* | ippocamp:* | kekryphalos:* | kolpos:* | lemb:* | lemn:* | leon:* | leonin:* | leont:* | lepr:* | libertas:* | lingu:* | lophos:* | lot:* | lup:* | mandorl:* | mant:* | mantell:* | maschil:* | mazzett:* | melon:* | menad:* | ment:* | minerv:* | muliebr:* | mus:* | muscol:* | muscolatur:* | naric:* | nas:* | nastrin:* | nereid:* | nettun:* | nik:* | ninf:* | nud:* | nudit:* | occhi:* | oliv:* | omer:* | oplit:* | orecc:* | orzo:* | palm:* | palmett:* | palmiped:* | palpebr:* | pampin:* | pan:* | pannegg:* | panter:* | pegas:* | pell:* | pepl:* | persefon:* | personagg:* | pesc:* | petal:* | pett:* | pinn:* | pium:* | piumagg:* | poderes:* | polos:* | pols:* | prigionier:* | putt:* | puttin:* | querc:* | ramett:* | ramoscell:* | re:* | recumbent:* | redin:* | ricciol:* | ritratt:* | rom:* | sabin:* | sakkos:* | satir:* | scen:* | schien:* | scill:* | scoll:* | scollatur:* | scorpion:* | scrimin:* | scriminatur:* | sdrai:* | sen:* | serpent:* | sever:* | sfing:* | sguard:* | silen:* | siren:* | sold:* | sopraccigl:* | sopraccigliar:* | sorris:* | sphendon:* | spig:* | stephan:* | suon:* | taras:* | temp:* | testin:* | tog:* | tor:* | torac:* | tralc:* | trecc:* | uccell:* | uliv:* | uman:* | uom:* | uva:* | vegetal:* | ven:* | vest:* | victrix:* | viril:* | vis:* | viticc:* | vittor:* | volatil:* | volt:* | zamp:* | zann:* | zoomorf:*');
insert into work.tags(scheda, tag) select scheda, 'elemeti floreali' from da where fts @@ to_tsquery('anthemion:* | bocciol:* | fior:* | fiorellin:* | floreal:* | ghirland:* | lot:* | mazzett:* | petal:* | ramoscell:* | tralc:*');
insert into work.tags(scheda, tag) select scheda, 'frutta' from da where fts @@ to_tsquery('bacc:* | ficus:* | frutt:* | grappol:* | melon:* | pampin:* | ramoscell:* | tralc:* | uva:* | viticc:*');
insert into work.tags(scheda, tag) select scheda, 'mezzi di trasporto' from da where fts @@ to_tsquery('aphlaston:* | aplustr:* | giog:* | pru:* | quadrig:* | redin:* | trig:*');
insert into work.tags(scheda, tag) select scheda, 'oggetti' from da where fts @@ to_tsquery('abbigl:* | abit:* | apex:* | aphlaston:* | aplustr:* | apoptygm:* | archi:* | armat:* | baston:* | bend:* | berrett:* | bracciol:* | carnyx:* | cas:* | cavallett:* | cint:* | clamid:* | cornucop:* | crest:* | curul:* | cuscin:* | diphros:* | drapp:* | far:* | fiaccol:* | fiocc:* | frig:* | fulmin:* | giog:* | glob:* | globett:* | kekryphalos:* | kolpos:* | lemb:* | lemn:* | leont:* | lophos:* | monument:* | nastrin:* | pell:* | pennacc:* | pepl:* | pium:* | poderes:* | polos:* | pru:* | quadrig:* | redin:* | ricam:* | sakkos:* | schienal:* | scoll:* | scollatur:* | sdrai:* | spallier:* | sphendon:* | stoff:* | suon:* | tenagl:* | tett:* | tirs:* | tog:* | trig:* | vest:*');
insert into work.tags(scheda, tag) select scheda, 'personaggi mitologici' from da where fts @@ to_tsquery('alat:* | centaur:* | dioscur:* | eracl:* | ercol:* | gorgon:* | libertas:* | nereid:* | nik:* | ninf:* | pell:* | rom:* | satir:* | scill:* | sfing:* | silen:* | siren:* | taras:* | victrix:* | vittor:*');
insert into work.tags(scheda, tag) select scheda, 'persone' from da where fts @@ to_tsquery('abbigl:* | abit:* | acconciatur:* | afrod:* | alat:* | amorin:* | anatom:* | androgin:* | antropomorf:* | apoll:* | apoptygm:* | armat:* | artemid:* | aten:* | avambracc:* | baff:* | bambin:* | barb:* | barbar:* | bendis:* | berrett:* | calzar:* | cap:* | capell:* | capigliatur:* | cappell:* | caval:* | cavalc:* | cavalier:* | centaur:* | cer:* | chignon:* | cint:* | ciocc:* | ciuff:* | clamid:* | copricap:* | cosc:* | cran:* | crocc:* | cupid:* | danz:* | desultor:* | dian:* | dionis:* | dioscur:* | divin:* | donn:* | drapp:* | efeb:* | elmat:* | eracl:* | ercol:* | eros:* | erot:* | facc:* | fall:* | fanciull:* | fantin:* | femminil:* | frang:* | frig:* | fulmin:* | ginocc:* | giov:* | giovan:* | giovanil:* | giunon:* | glute:* | gorgon:* | got:* | gremb:* | guerrier:* | hermes:* | himation:* | imberb:* | imbracc:* | incoron:* | individu:* | infant:* | inginocc:* | kekryphalos:* | kolpos:* | lemb:* | lemn:* | leont:* | libertas:* | lophos:* | mandorl:* | mantell:* | maschil:* | menad:* | ment:* | minerv:* | muliebr:* | naric:* | nas:* | nastrin:* | nereid:* | nettun:* | nik:* | ninf:* | nud:* | nudit:* | omer:* | oplit:* | palpebr:* | pan:* | pannegg:* | pegas:* | pell:* | pepl:* | persefon:* | personagg:* | pett:* | pium:* | poderes:* | polos:* | pols:* | prigionier:* | putt:* | puttin:* | re:* | recumbent:* | redin:* | ricciol:* | ritratt:* | rom:* | sabin:* | sakkos:* | satir:* | schien:* | scoll:* | scollatur:* | sdrai:* | sen:* | sever:* | sfing:* | silen:* | siren:* | sold:* | sopraccigl:* | sopraccigliar:* | sorris:* | sphendon:* | stephan:* | suon:* | taras:* | temp:* | testin:* | tog:* | torac:* | trecc:* | uman:* | uom:* | ven:* | vest:* | victrix:* | viril:* | vis:* | vittor:* | volt:*');
insert into work.tags(scheda, tag) select scheda, 'scritte' from da where fts @@ to_tsquery('aed:* | alfabet:* | an:* | anton:* | api:* | cartigl:* | cat:* | co:* | dom:* | iscrizion:* | lettur:* | monogramm:* | scritt:*');
insert into work.tags(scheda, tag) select scheda, 'strumenti' from da where fts @@ to_tsquery('armat:* | baston:* | carnyx:* | cornucop:* | fiaccol:* | fulmin:* | glob:* | globett:* | suon:* | tenagl:* | tirs:*');
insert into work.tags(scheda, tag) select scheda, 'elementi vegetali' from da where fts @@ to_tsquery('acant:* | allor:* | eder:* | fitomorf:* | fogliolin:* | mazzett:* | oliv:* | orzo:* | palm:* | palmett:* | querc:* | ramett:* | ramoscell:* | spig:* | tralc:* | uliv:* | vegetal:*');

create table tag(scheda integer primary key references scheda(id) on delete cascade, tags character varying[]);
insert into tag(scheda, tags) select scheda, array_agg(tag) tag from work.tags group by scheda;
commit;
