BEGIN;
CREATE TABLE liste.ra_tecnica(id serial PRIMARY KEY, value CHARACTER VARYING NOT NULL UNIQUE);
INSERT INTO liste.ra_tecnica(value) VALUES
('abrasione'),
('abrasione su osso'),
('abrasione su pietra ollare'),
('acciaio a sbalzo'),
('affilatura su ferro'),
('affilatura'),
('agemina in argento su acciaio'),
('agemina in argento'),
('agemina in oro su acciaio'),
('agemina in oro'),
('agemina su acciaio'),
('agemina su argento'),
('agemina su bronzo'),
('agemina su ferro'),
('agemina su lega metallica'),
('agemina su metallo'),
('agemina su oro'),
('agemina su rame'),
('agemina'),
('argentatura su bronzo'),
('argentatura su lega metallica'),
('argentatura su rame'),
('argentatura su stagno'),
('argentatura'),
('argento a sbalzo'),
('argilla a mano'),
('argilla a matrice'),
('barbottina su argilla'),
('barbottina su impasto'),
('barbottina'),
('basse-taille su argento'),
('basse-taille su metallo'),
('basse-taille'),
('battitura a caldo su argento'),
('battitura a caldo su ferro'),
('battitura a caldo su metallo'),
('battitura a caldo'),
('battitura a freddo su bronzo'),
('battitura a freddo'),
('battitura a stampo su argento'),
('battitura a stampo su metallo'),
('battitura a stampo'),
('battitura su argento'),
('battitura su bronzo'),
('battitura su elettro'),
('battitura su ferro'),
('battitura su lega metallica'),
('battitura su metallo'),
('battitura su oro'),
('battitura su rame'),
('battitura su stagno'),
('battitura'),
('brasatura su bronzo'),
('brasatura su ferro'),
('brasatura su lega metallica'),
('brasatura'),
('bronzo a matrice'),
('bronzo a sbalzo'),
('brunitura su acciaio'),
('brunitura su argento'),
('brunitura su bronzo'),
('brunitura su ferro'),
('brunitura su lega metallica'),
('brunitura su metallo'),
('brunitura su rame'),
('brunitura'),
('bucchero a mano'),
('bulino su argento'),
('bulino su avorio'),
('bulino su bronzo'),
('bulino su corno'),
('bulino su ferro'),
('bulino su lega metallica'),
('bulino su metallo'),
('bulino su oro'),
('bulino su osso'),
('bulino su piombo'),
('bulino su rame'),
('bulino'),
('cabochon su acquamarina'),
('cabochon su agata zonata'),
('cabochon su agata'),
('cabochon su ambra'),
('cabochon su ametista'),
('cabochon su calcedonio'),
('cabochon su diaspro'),
('cabochon su eliotropio'),
('cabochon su giada'),
('cabochon su giaietto'),
('cabochon su granato'),
('cabochon su malachite'),
('cabochon su occhio di gatto'),
('cabochon su occhio di pavone bianco'),
('cabochon su occhio di tigre'),
('cabochon su olivina'),
('cabochon su onice'),
('cabochon su opale'),
('cabochon su pasta vitrea'),
('cabochon su rubino'),
('cabochon su sardonice'),
('cabochon su smeraldo'),
('cabochon su spinello'),
('cabochon su topazio'),
('cabochon su tormalina'),
('cabochon su turchese'),
('cabochon su zaffiro'),
('cabochon'),
('cassaforma su argilla'),
('cassaforma su laterizio'),
('cassaforma'),
('cesellatura su acciaio'),
('cesellatura su argento'),
('cesellatura su bronzo'),
('cesellatura su lega metallica'),
('cesellatura su metallo'),
('cesellatura su oro'),
('cesellatura su piombo'),
('cesellatura su rame'),
('cesellatura'),
('champleve su bronzo'),
('champleve su ferro'),
('champleve su rame'),
('champleve'),
('cilindretti su argilla'),
('cilindretti su impasto'),
('cilindretti'),
('cloisonne su bronzo'),
('cloisonne su lapislazzuli'),
('cloisonne su oro'),
('cloisonne'),
('colatura a stampo su vetro'),
('colatura a stampo'),
('colombino su argilla'),
('colombino su impasto'),
('colombino'),
('coniazione su argento'),
('coniazione su bronzo'),
('coniazione su elettro'),
('coniazione su lega metallica'),
('coniazione su metallo'),
('coniazione'),
('crudo'),
('damaschinatura su acciaio'),
('damaschinatura su ferro'),
('damaschinatura su lega metallica'),
('damaschinatura su rame'),
('damaschinatura'),
('ditate su argilla'),
('ditate su impasto'),
('ditate'),
('doppia matrice su argilla'),
('doppia matrice'),
('doratura a foglia su argento'),
('doratura a foglia su ferro'),
('doratura a foglia su metallo'),
('doratura a foglia'),
('doratura a mercurio su argento'),
('doratura a mercurio su ferro'),
('doratura a mercurio su metallo'),
('doratura a mercurio'),
('doratura su acciaio'),
('doratura su argento'),
('doratura su bronzo'),
('doratura su ferro'),
('doratura su lega metallica'),
('doratura su metallo'),
('doratura su rame'),
('doratura su stagno'),
('doratura su vetro'),
('doratura'),
('excisione su argilla'),
('excisione su bucchero'),
('excisione'),
('ferro a sbalzo'),
('filatura su argento'),
('filatura su lega metallica'),
('filatura su metallo'),
('filatura su oro'),
('filatura su rame'),
('filatura'),
('filigrana su argento'),
('filigrana su lega metallica'),
('filigrana su metallo'),
('filigrana su oro'),
('filigrana su rame'),
('filigrana'),
('finitura a stecca su pietra ollare'),
('finitura a stecca'),
('finitura al tornio su avorio'),
('finitura al tornio su pietra ollare'),
('finitura al tornio'),
('foratura su acquamarina'),
('foratura su agata zonata'),
('foratura su agata'),
('foratura su amazzonite'),
('foratura su ambra'),
('foratura su ametista'),
('foratura su argento'),
('foratura su avorio'),
('foratura su calcedonio'),
('foratura su conchiglia'),
('foratura su corallo'),
('foratura su corniola'),
('foratura su cristallo di rocca'),
('foratura su diaspro'),
('foratura su eliotropio'),
('foratura su ematite'),
('foratura su faience'),
('foratura su giada'),
('foratura su giaietto'),
('foratura su granato'),
('foratura su lapislazzuli'),
('foratura su malachite'),
('foratura su metallo'),
('foratura su pasta vitrea'),
('foratura su perla'),
('foratura su plasma'),
('foratura su prasio'),
('foratura su quarzo rosa'),
('foratura'),
('forgiatura su argento'),
('forgiatura su bronzo'),
('forgiatura su ferro'),
('forgiatura su lega metallica'),
('forgiatura su metallo'),
('forgiatura su oro'),
('forgiatura su rame'),
('forgiatura'),
('fusione a cera persa su argento'),
('fusione a cera persa su bronzo'),
('fusione a cera persa su lega metallica'),
('fusione a cera persa su metallo'),
('fusione a cera persa su oro'),
('fusione a cera persa'),
('fusione a matrice su piombo'),
('fusione a matrice'),
('fusione a stampo su argento'),
('fusione a stampo su bronzo'),
('fusione a stampo su ferro'),
('fusione a stampo su lega metallica'),
('fusione a stampo su metallo'),
('fusione a stampo su oro'),
('fusione a stampo su piombo'),
('fusione a stampo su rame'),
('fusione a stampo'),
('fusione su acciaio'),
('fusione su argento'),
('fusione su bronzo'),
('fusione su ferro'),
('fusione su metallo'),
('fusione su oro'),
('fusione su piombo'),
('fusione su rame'),
('fusione su stagno'),
('fusione su vetro'),
('fusione'),
('godronatura su argento'),
('godronatura su metallo'),
('godronatura su oro'),
('godronatura su rame'),
('godronatura'),
('gradina su calcare'),
('gradina su marmo africano'),
('gradina su marmo asiatico'),
('gradina su marmo bardiglio di Carrara'),
('gradina su marmo bianco greco'),
('gradina su marmo bianco italico'),
('gradina su marmo bianco venato'),
('gradina su marmo bianco'),
('gradina su marmo bigio antico'),
('gradina su marmo bigio morato'),
('gradina su marmo bigio'),
('gradina su marmo broccatello di Verona'),
('gradina su marmo broccatello'),
('gradina su marmo broccatellone'),
('gradina su marmo cipollino mandolato'),
('gradina su marmo cipollino marino'),
('gradina su marmo cipollino rosso'),
('gradina su marmo cipollino'),
('gradina su marmo cottanello antico'),
('gradina su marmo dell''Imetto'),
('gradina su marmo di Carrara'),
('gradina su marmo di Proconneso'),
('gradina su marmo di Taso'),
('gradina su marmo fior di pesco'),
('gradina su marmo giallo antico brecciato'),
('gradina su marmo giallo antico'),
('gradina su marmo giallo tigrato'),
('gradina su marmo greco insulare'),
('gradina su marmo greco scritto'),
('gradina su marmo grigio brecciato'),
('gradina su marmo grigio venato'),
('gradina su marmo grigio'),
('gradina su marmo italico'),
('gradina su marmo lumachella bigia'),
('gradina su marmo lumachella d''Egitto'),
('gradina su marmo lumachella pavonazza'),
('gradina su marmo lumachella rosea'),
('gradina su marmo lumachella'),
('gradina su marmo lumachellone antico'),
('gradina su marmo lunense'),
('gradina su marmo nero africano'),
('gradina su marmo nero antico'),
('gradina su marmo occhio di pavone bianco'),
('gradina su marmo occhio di pavone bigio'),
('gradina su marmo occhio di pavone pavonazzo'),
('gradina su marmo occhio di pavone roseo'),
('gradina su marmo occhio di pavone rosso'),
('gradina su marmo palombino'),
('gradina su marmo pario'),
('gradina su marmo pavonazzetto'),
('gradina su marmo pentelico'),
('gradina su marmo policromo'),
('gradina su marmo portasanta'),
('gradina su marmo proconnesio'),
('gradina su marmo rosa'),
('gradina su marmo rosso antico'),
('gradina su marmo rosso brecciato'),
('gradina su marmo semesanto'),
('gradina su marmo serpentina moschinata'),
('gradina su marmo verde antico'),
('gradina su marmo verde rana fibroso'),
('gradina su marmo verde rana ondato'),
('gradina su marmo'),
('gradina su pietra ollare'),
('gradina su pietra'),
('gradina su trachite dei Colli Euganei'),
('gradina su trachite'),
('gradina'),
('graffito su argilla'),
('graffito su bucchero'),
('graffito su impasto'),
('graffito su marmo africano'),
('graffito su marmo asiatico'),
('graffito su marmo bardiglio di Carrara'),
('graffito su marmo bianco greco'),
('graffito su marmo bianco italico'),
('graffito su marmo bianco venato'),
('graffito su marmo bianco'),
('graffito su marmo bigio antico'),
('graffito su marmo bigio morato'),
('graffito su marmo bigio'),
('graffito su marmo broccatello di Verona'),
('graffito su marmo broccatello'),
('graffito su marmo broccatellone'),
('graffito su marmo cipollino mandolato'),
('graffito su marmo cipollino marino'),
('graffito su marmo cipollino rosso'),
('graffito su marmo cipollino'),
('graffito su marmo cottanello antico'),
('graffito su marmo dell''Imetto'),
('graffito su marmo di Carrara'),
('graffito su marmo di Proconneso'),
('graffito su marmo di Taso'),
('graffito su marmo fior di pesco'),
('graffito su marmo giallo antico brecciato'),
('graffito su marmo giallo antico'),
('graffito su marmo giallo tigrato'),
('graffito su marmo greco insulare'),
('graffito su marmo greco scritto'),
('graffito su marmo grigio brecciato'),
('graffito su marmo grigio venato'),
('graffito su marmo grigio'),
('graffito su marmo italico'),
('graffito su marmo lumachella bigia'),
('graffito su marmo lumachella d''Egitto'),
('graffito su marmo lumachella pavonazza'),
('graffito su marmo lumachella rosea'),
('graffito su marmo lumachella'),
('graffito su marmo lumachellone antico'),
('graffito su marmo lunense'),
('graffito su marmo nero africano'),
('graffito su marmo nero antico'),
('graffito su marmo occhio di pavone bianco'),
('graffito su marmo occhio di pavone bigio'),
('graffito su marmo occhio di pavone pavonazzo'),
('graffito su marmo occhio di pavone roseo'),
('graffito su marmo occhio di pavone rosso'),
('graffito su marmo palombino'),
('graffito su marmo pario'),
('graffito su marmo pavonazzetto'),
('graffito su marmo pentelico'),
('graffito su marmo policromo'),
('graffito su marmo portasanta'),
('graffito su marmo proconnesio'),
('graffito su marmo rosa'),
('graffito su marmo rosso antico'),
('graffito su marmo rosso brecciato'),
('graffito su marmo semesanto'),
('graffito su marmo serpentina moschinata'),
('graffito su marmo verde antico'),
('graffito su marmo verde rana fibroso'),
('graffito su marmo verde rana ondato'),
('graffito su marmo'),
('graffito su pietra ollare'),
('graffito su pietra'),
('graffito'),
('granulazione su oro'),
('granulazione'),
('imbutitura su argento'),
('imbutitura su ferro'),
('imbutitura su metallo'),
('imbutitura'),
('immersione su argento'),
('immersione su argilla'),
('immersione su metallo'),
('immersione'),
('impasto a mano'),
('impasto a matrice'),
('impressione su argilla'),
('impressione su bronzo'),
('impressione su bucchero'),
('impressione su impasto'),
('impressione su laterizio'),
('impressione su oro'),
('impressione su piombo'),
('impressione su rame'),
('impressione'),
('incastonatura su acquamarina'),
('incastonatura su agata zonata'),
('incastonatura su agata'),
('incastonatura su amazzonite'),
('incastonatura su ambra'),
('incastonatura su ametista'),
('incastonatura su calcedonio'),
('incastonatura su diamante'),
('incastonatura su diaspro'),
('incastonatura su eliotropio'),
('incastonatura su giada'),
('incastonatura su giaietto'),
('incastonatura su granato'),
('incastonatura su lapislazzuli'),
('incastonatura su malachite'),
('incastonatura su occhio di gatto'),
('incastonatura su occhio di pavone bianco'),
('incastonatura su occhio di tigre'),
('incastonatura su olivina'),
('incastonatura su onice'),
('incastonatura su opale'),
('incastonatura su pasta vitrea'),
('incastonatura su perla'),
('incastonatura su plasma'),
('incastonatura su prasio'),
('incastonatura su quarzo rosa'),
('incastonatura su rubino'),
('incastonatura su sardonice'),
('incastonatura su smeraldo'),
('incastonatura su spinello'),
('incastonatura su topazio'),
('incastonatura su tormalina'),
('incastonatura su turchese'),
('incastonatura su zaffiro'),
('incastonatura su zircone'),
('incastonatura'),
('incisione a crudo su argilla'),
('incisione a crudo'),
('incisione su acciaio'),
('incisione su acquamarina'),
('incisione su agata zonata'),
('incisione su agata'),
('incisione su alabastro a pecorella'),
('incisione su alabastro a tartaruga'),
('incisione su alabastro bianco'),
('incisione su alabastro del Gebel Oust'),
('incisione su alabastro di Palombara'),
('incisione su alabastro dorato'),
('incisione su alabastro egiziano'),
('incisione su alabastro fiorito'),
('incisione su alabastro marino'),
('incisione su alabastro'),
('incisione su amazzonite'),
('incisione su ambra'),
('incisione su ametista'),
('incisione su ardesia'),
('incisione su arenaria'),
('incisione su argento'),
('incisione su argilla'),
('incisione su avorio'),
('incisione su basalto'),
('incisione su basanite'),
('incisione su breccia'),
('incisione su bronzo'),
('incisione su bucchero'),
('incisione su calcare'),
('incisione su calcedonio'),
('incisione su corallo'),
('incisione su corniola'),
('incisione su corno'),
('incisione su cristallo di rocca'),
('incisione su diamante'),
('incisione su diaspro'),
('incisione su eliotropio'),
('incisione su ematite'),
('incisione su ferro'),
('incisione su giada'),
('incisione su giaietto'),
('incisione su granato'),
('incisione su granito'),
('incisione su impasto'),
('incisione su lapislazzuli'),
('incisione su lavagna'),
('incisione su legno'),
('incisione su malachite'),
('incisione su marmo africano'),
('incisione su marmo asiatico'),
('incisione su marmo bardiglio di Carrara'),
('incisione su marmo bianco greco'),
('incisione su marmo bianco italico'),
('incisione su marmo bianco venato'),
('incisione su marmo bianco'),
('incisione su marmo bigio antico'),
('incisione su marmo bigio morato'),
('incisione su marmo bigio'),
('incisione su marmo broccatello di Verona'),
('incisione su marmo broccatello'),
('incisione su marmo broccatellone'),
('incisione su marmo cipollino mandolato'),
('incisione su marmo cipollino marino'),
('incisione su marmo cipollino rosso'),
('incisione su marmo cipollino'),
('incisione su marmo cottanello antico'),
('incisione su marmo dell''Imetto'),
('incisione su marmo di Carrara'),
('incisione su marmo di Proconneso'),
('incisione su marmo di Taso'),
('incisione su marmo fior di pesco'),
('incisione su marmo giallo antico brecciato'),
('incisione su marmo giallo antico'),
('incisione su marmo giallo tigrato'),
('incisione su marmo greco insulare'),
('incisione su marmo greco scritto'),
('incisione su marmo grigio brecciato'),
('incisione su marmo grigio venato'),
('incisione su marmo grigio'),
('incisione su marmo italico'),
('incisione su marmo lumachella bigia'),
('incisione su marmo lumachella d''Egitto'),
('incisione su marmo lumachella pavonazza'),
('incisione su marmo lumachella rosea'),
('incisione su marmo lumachella'),
('incisione su marmo lumachellone antico'),
('incisione su marmo lunense'),
('incisione su marmo nero africano'),
('incisione su marmo nero antico'),
('incisione su marmo occhio di pavone bianco'),
('incisione su marmo occhio di pavone bigio'),
('incisione su marmo occhio di pavone pavonazzo'),
('incisione su marmo occhio di pavone roseo'),
('incisione su marmo occhio di pavone rosso'),
('incisione su marmo palombino'),
('incisione su marmo pario'),
('incisione su marmo pavonazzetto'),
('incisione su marmo pentelico'),
('incisione su marmo policromo'),
('incisione su marmo portasanta'),
('incisione su marmo proconnesio'),
('incisione su marmo rosa'),
('incisione su marmo rosso antico'),
('incisione su marmo rosso brecciato'),
('incisione su marmo semesanto'),
('incisione su marmo serpentina moschinata'),
('incisione su marmo verde antico'),
('incisione su marmo verde rana fibroso'),
('incisione su marmo verde rana ondato'),
('incisione su marmo'),
('incisione su metallo'),
('incisione su nenfro'),
('incisione su nicolo'),
('incisione su occhio di gatto'),
('incisione su occhio di pavone bianco'),
('incisione su occhio di tigre'),
('incisione su olivina'),
('incisione su onice'),
('incisione su opale'),
('incisione su oro'),
('incisione su osso'),
('incisione su pasta vitrea'),
('incisione su peperino'),
('incisione su pietra dura'),
('incisione su pietra ollare'),
('incisione su piombo'),
('incisione su plasma'),
('incisione su prasio'),
('incisione su quarzo rosa'),
('incisione su quarzo'),
('incisione su rame'),
('incisione su rubino'),
('incisione su sardonice'),
('incisione su smeraldo'),
('incisione su spinello'),
('incisione su stagno'),
('incisione su topazio'),
('incisione su tormalina'),
('incisione su trachite dei Colli Euganei'),
('incisione su trachite'),
('incisione su travertino'),
('incisione su tufo giallo litoide'),
('incisione su tufo grigio'),
('incisione su tufo Nocerino'),
('incisione su tufo rosso a scorie nere'),
('incisione su tufo rosso litoide'),
('incisione su tufo Sabazio'),
('incisione su tufo trachitico'),
('incisione su tufo Vulsinio'),
('incisione su tufo'),
('incisione su turchese'),
('incisione su vetro'),
('incisione su zaffiro'),
('incisione su zircone'),
('incisione'),
('incrostazione su argilla'),
('incrostazione su impasto'),
('incrostazione'),
('ingobbiatura su argilla'),
('ingobbiatura su impasto'),
('ingobbiatura su laterizio'),
('ingobbiatura'),
('intaglio a freddo su osso'),
('intaglio a freddo'),
('intaglio su acquamarina'),
('intaglio su agata zonata'),
('intaglio su agata'),
('intaglio su alabastro a pecorella'),
('intaglio su alabastro a tartaruga'),
('intaglio su alabastro bianco'),
('intaglio su alabastro del Gebel Oust'),
('intaglio su alabastro di Palombara'),
('intaglio su alabastro dorato'),
('intaglio su alabastro egiziano'),
('intaglio su alabastro fiorito'),
('intaglio su alabastro marino'),
('intaglio su alabastro'),
('intaglio su amazzonite'),
('intaglio su ambra'),
('intaglio su ametista'),
('intaglio su argento'),
('intaglio su argilla'),
('intaglio su avorio'),
('intaglio su basanite'),
('intaglio su calcedonio'),
('intaglio su conchiglia'),
('intaglio su corallo'),
('intaglio su corniola'),
('intaglio su corno'),
('intaglio su cristallo di rocca'),
('intaglio su diaspro'),
('intaglio su eliotropio'),
('intaglio su ematite'),
('intaglio su giada'),
('intaglio su giaietto'),
('intaglio su granato'),
('intaglio su impasto'),
('intaglio su lapislazzuli'),
('intaglio su lega metallica'),
('intaglio su legno'),
('intaglio su malachite'),
('intaglio su marmo africano'),
('intaglio su marmo asiatico'),
('intaglio su marmo bardiglio di Carrara'),
('intaglio su marmo bianco greco'),
('intaglio su marmo bianco italico'),
('intaglio su marmo bianco venato'),
('intaglio su marmo bianco'),
('intaglio su marmo bigio antico'),
('intaglio su marmo bigio morato'),
('intaglio su marmo bigio'),
('intaglio su marmo broccatello di Verona'),
('intaglio su marmo broccatello'),
('intaglio su marmo broccatellone'),
('intaglio su marmo cipollino mandolato'),
('intaglio su marmo cipollino marino'),
('intaglio su marmo cipollino rosso'),
('intaglio su marmo cipollino'),
('intaglio su marmo cottanello antico'),
('intaglio su marmo dell''Imetto'),
('intaglio su marmo di Carrara'),
('intaglio su marmo di Proconneso'),
('intaglio su marmo di Taso'),
('intaglio su marmo fior di pesco'),
('intaglio su marmo giallo antico brecciato'),
('intaglio su marmo giallo antico'),
('intaglio su marmo giallo tigrato'),
('intaglio su marmo greco insulare'),
('intaglio su marmo greco scritto'),
('intaglio su marmo grigio brecciato'),
('intaglio su marmo grigio venato'),
('intaglio su marmo grigio'),
('intaglio su marmo italico'),
('intaglio su marmo lumachella bigia'),
('intaglio su marmo lumachella d''Egitto'),
('intaglio su marmo lumachella pavonazza'),
('intaglio su marmo lumachella rosea'),
('intaglio su marmo lumachella'),
('intaglio su marmo lumachellone antico'),
('intaglio su marmo lunense'),
('intaglio su marmo nero africano'),
('intaglio su marmo nero antico'),
('intaglio su marmo occhio di pavone bianco'),
('intaglio su marmo occhio di pavone bigio'),
('intaglio su marmo occhio di pavone pavonazzo'),
('intaglio su marmo occhio di pavone roseo'),
('intaglio su marmo occhio di pavone rosso'),
('intaglio su marmo palombino'),
('intaglio su marmo pario'),
('intaglio su marmo pavonazzetto'),
('intaglio su marmo pentelico'),
('intaglio su marmo policromo'),
('intaglio su marmo portasanta'),
('intaglio su marmo proconnesio'),
('intaglio su marmo rosa'),
('intaglio su marmo rosso antico'),
('intaglio su marmo rosso brecciato'),
('intaglio su marmo semesanto'),
('intaglio su marmo serpentina moschinata'),
('intaglio su marmo verde antico'),
('intaglio su marmo verde rana fibroso'),
('intaglio su marmo verde rana ondato'),
('intaglio su marmo'),
('intaglio su metallo'),
('intaglio su nenfro'),
('intaglio su nicolo'),
('intaglio su occhio di gatto'),
('intaglio su occhio di pavone bianco'),
('intaglio su occhio di tigre'),
('intaglio su olivina'),
('intaglio su onice'),
('intaglio su opale'),
('intaglio su oro'),
('intaglio su osso'),
('intaglio su pasta vitrea'),
('intaglio su pietra dura'),
('intaglio su pietra ollare'),
('intaglio su plasma'),
('intaglio su prasio'),
('intaglio su quarzo rosa'),
('intaglio su quarzo'),
('intaglio su rame'),
('intaglio su rubino'),
('intaglio su sardonice'),
('intaglio su smeraldo'),
('intaglio su spinello'),
('intaglio su topazio'),
('intaglio su tormalina'),
('intaglio su turchese'),
('intaglio su vetro'),
('intaglio su zaffiro'),
('intaglio su zircone'),
('intaglio'),
('intarsio su acquamarina'),
('intarsio su agata zonata'),
('intarsio su agata'),
('intarsio su ambra'),
('intarsio su ametista'),
('intarsio su argento'),
('intarsio su avorio'),
('intarsio su bronzo'),
('intarsio su calcedonio'),
('intarsio su corallo'),
('intarsio su corno'),
('intarsio su diaspro'),
('intarsio su eliotropio'),
('intarsio su ferro'),
('intarsio su giada'),
('intarsio su giaietto'),
('intarsio su granato'),
('intarsio su lavagna'),
('intarsio su lega metallica'),
('intarsio su marmo africano'),
('intarsio su marmo asiatico'),
('intarsio su marmo bardiglio di Carrara'),
('intarsio su marmo bianco greco'),
('intarsio su marmo bianco italico'),
('intarsio su marmo bianco venato'),
('intarsio su marmo bianco'),
('intarsio su marmo bigio antico'),
('intarsio su marmo bigio morato'),
('intarsio su marmo bigio'),
('intarsio su marmo broccatello di Verona'),
('intarsio su marmo broccatello'),
('intarsio su marmo broccatellone'),
('intarsio su marmo cipollino mandolato'),
('intarsio su marmo cipollino marino'),
('intarsio su marmo cipollino rosso'),
('intarsio su marmo cipollino'),
('intarsio su marmo cottanello antico'),
('intarsio su marmo dell''Imetto'),
('intarsio su marmo di Carrara'),
('intarsio su marmo di Proconneso'),
('intarsio su marmo di Taso'),
('intarsio su marmo fior di pesco'),
('intarsio su marmo giallo antico brecciato'),
('intarsio su marmo giallo antico'),
('intarsio su marmo giallo tigrato'),
('intarsio su marmo greco insulare'),
('intarsio su marmo greco scritto'),
('intarsio su marmo grigio brecciato'),
('intarsio su marmo grigio venato'),
('intarsio su marmo grigio'),
('intarsio su marmo italico'),
('intarsio su marmo lumachella bigia'),
('intarsio su marmo lumachella d''Egitto'),
('intarsio su marmo lumachella pavonazza'),
('intarsio su marmo lumachella rosea'),
('intarsio su marmo lumachella'),
('intarsio su marmo lumachellone antico'),
('intarsio su marmo lunense'),
('intarsio su marmo nero africano'),
('intarsio su marmo nero antico'),
('intarsio su marmo occhio di pavone bianco'),
('intarsio su marmo occhio di pavone bigio'),
('intarsio su marmo occhio di pavone pavonazzo'),
('intarsio su marmo occhio di pavone roseo'),
('intarsio su marmo occhio di pavone rosso'),
('intarsio su marmo palombino'),
('intarsio su marmo pario'),
('intarsio su marmo pavonazzetto'),
('intarsio su marmo pentelico'),
('intarsio su marmo policromo'),
('intarsio su marmo portasanta'),
('intarsio su marmo proconnesio'),
('intarsio su marmo rosa'),
('intarsio su marmo rosso antico'),
('intarsio su marmo rosso brecciato'),
('intarsio su marmo semesanto'),
('intarsio su marmo serpentina moschinata'),
('intarsio su marmo verde antico'),
('intarsio su marmo verde rana fibroso'),
('intarsio su marmo verde rana ondato'),
('intarsio su marmo'),
('intarsio su metallo'),
('intarsio su occhio di gatto'),
('intarsio su occhio di pavone bianco'),
('intarsio su occhio di tigre'),
('intarsio su olivina'),
('intarsio su onice'),
('intarsio su opale'),
('intarsio su osso'),
('intarsio su rame'),
('intarsio su rubino'),
('intarsio su sardonice'),
('intarsio su smeraldo'),
('intarsio su spinello'),
('intarsio su topazio'),
('intarsio su tormalina'),
('intarsio su turchese'),
('intarsio su zaffiro'),
('intarsio su zircone'),
('intarsio'),
('invetriatura su argilla'),
('invetriatura su impasto'),
('invetriatura'),
('laminatura su argento'),
('laminatura su bronzo'),
('laminatura su ferro'),
('laminatura su lega metallica'),
('laminatura su metallo'),
('laminatura su oro'),
('laminatura su piombo'),
('laminatura su rame'),
('laminatura'),
('laterizio a crudo'),
('laterizio a mano'),
('lega metallica a sbalzo'),
('levigatura su alabastro a pecorella'),
('levigatura su alabastro a tartaruga'),
('levigatura su alabastro bianco'),
('levigatura su alabastro del Gebel Oust'),
('levigatura su alabastro di Palombara'),
('levigatura su alabastro dorato'),
('levigatura su alabastro egiziano'),
('levigatura su alabastro fiorito'),
('levigatura su alabastro marino'),
('levigatura su alabastro'),
('levigatura su ambra'),
('levigatura su ametista'),
('levigatura su ardesia'),
('levigatura su arenaria'),
('levigatura su argilla'),
('levigatura su basalto'),
('levigatura su basanite'),
('levigatura su breccia'),
('levigatura su bronzo'),
('levigatura su calcare'),
('levigatura su calcarenite'),
('levigatura su clorite'),
('levigatura su corallo'),
('levigatura su corniola'),
('levigatura su corno'),
('levigatura su faience'),
('levigatura su granito'),
('levigatura su legno'),
('levigatura su marmo africano'),
('levigatura su marmo asiatico'),
('levigatura su marmo bardiglio di Carrara'),
('levigatura su marmo bianco greco'),
('levigatura su marmo bianco italico'),
('levigatura su marmo bianco venato'),
('levigatura su marmo bianco'),
('levigatura su marmo bigio antico'),
('levigatura su marmo bigio morato'),
('levigatura su marmo bigio'),
('levigatura su marmo broccatello di Verona'),
('levigatura su marmo broccatello'),
('levigatura su marmo broccatellone'),
('levigatura su marmo cipollino mandolato'),
('levigatura su marmo cipollino marino'),
('levigatura su marmo cipollino rosso'),
('levigatura su marmo cipollino'),
('levigatura su marmo cottanello antico'),
('levigatura su marmo dell''Imetto'),
('levigatura su marmo di Carrara'),
('levigatura su marmo di Proconneso'),
('levigatura su marmo di Taso'),
('levigatura su marmo fior di pesco'),
('levigatura su marmo giallo antico brecciato'),
('levigatura su marmo giallo antico'),
('levigatura su marmo giallo tigrato'),
('levigatura su marmo greco insulare'),
('levigatura su marmo greco scritto'),
('levigatura su marmo grigio brecciato'),
('levigatura su marmo grigio venato'),
('levigatura su marmo grigio'),
('levigatura su marmo italico'),
('levigatura su marmo lumachella bigia'),
('levigatura su marmo lumachella d''Egitto'),
('levigatura su marmo lumachella pavonazza'),
('levigatura su marmo lumachella rosea'),
('levigatura su marmo lumachella'),
('levigatura su marmo lumachellone antico'),
('levigatura su marmo lunense'),
('levigatura su marmo nero africano'),
('levigatura su marmo nero antico'),
('levigatura su marmo occhio di pavone bianco'),
('levigatura su marmo occhio di pavone bigio'),
('levigatura su marmo occhio di pavone pavonazzo'),
('levigatura su marmo occhio di pavone roseo'),
('levigatura su marmo occhio di pavone rosso'),
('levigatura su marmo palombino'),
('levigatura su marmo pario'),
('levigatura su marmo pavonazzetto'),
('levigatura su marmo pentelico'),
('levigatura su marmo policromo'),
('levigatura su marmo portasanta'),
('levigatura su marmo proconnesio'),
('levigatura su marmo rosa'),
('levigatura su marmo rosso antico'),
('levigatura su marmo rosso brecciato'),
('levigatura su marmo semesanto'),
('levigatura su marmo serpentina moschinata'),
('levigatura su marmo verde antico'),
('levigatura su marmo verde rana fibroso'),
('levigatura su marmo verde rana ondato'),
('levigatura su marmo'),
('levigatura su ofiolite'),
('levigatura su osso'),
('levigatura su pietra ollare'),
('levigatura su pietra'),
('levigatura su porfido bigio'),
('levigatura su porfido nero grafico'),
('levigatura su porfido nero'),
('levigatura su porfido rosso'),
('levigatura su porfido verde di Laconia'),
('levigatura su porfido verde egiziano'),
('levigatura su porfido'),
('levigatura su puddinga'),
('levigatura su scisto'),
('levigatura su selce'),
('levigatura su trachite dei Colli Euganei'),
('levigatura su trachite'),
('levigatura su travertino'),
('levigatura su tufo giallo litoide'),
('levigatura su tufo grigio'),
('levigatura su tufo Nocerino'),
('levigatura su tufo rosso a scorie nere'),
('levigatura su tufo rosso litoide'),
('levigatura su tufo Sabazio'),
('levigatura su tufo trachitico'),
('levigatura su tufo Vulsinio'),
('levigatura su tufo'),
('levigatura'),
('limatura su ferro'),
('limatura'),
('lisciatura a stecca su argilla'),
('lisciatura a stecca su bucchero'),
('lisciatura a stecca su impasto'),
('lisciatura a stecca'),
('lisciatura su ardesia'),
('lisciatura su arenaria'),
('lisciatura su argilla'),
('lisciatura su bucchero'),
('lisciatura su calcare'),
('lisciatura su corno'),
('lisciatura su impasto'),
('lisciatura su marmo africano'),
('lisciatura su marmo asiatico'),
('lisciatura su marmo bardiglio di Carrara'),
('lisciatura su marmo bianco greco'),
('lisciatura su marmo bianco italico'),
('lisciatura su marmo bianco venato'),
('lisciatura su marmo bianco'),
('lisciatura su marmo bigio antico'),
('lisciatura su marmo bigio morato'),
('lisciatura su marmo bigio'),
('lisciatura su marmo broccatello di Verona'),
('lisciatura su marmo broccatello'),
('lisciatura su marmo broccatellone'),
('lisciatura su marmo cipollino mandolato'),
('lisciatura su marmo cipollino marino'),
('lisciatura su marmo cipollino rosso'),
('lisciatura su marmo cipollino'),
('lisciatura su marmo cottanello antico'),
('lisciatura su marmo dell''Imetto'),
('lisciatura su marmo di Carrara'),
('lisciatura su marmo di Proconneso'),
('lisciatura su marmo di Taso'),
('lisciatura su marmo fior di pesco'),
('lisciatura su marmo giallo antico brecciato'),
('lisciatura su marmo giallo antico'),
('lisciatura su marmo giallo tigrato'),
('lisciatura su marmo greco insulare'),
('lisciatura su marmo greco scritto'),
('lisciatura su marmo grigio brecciato'),
('lisciatura su marmo grigio venato'),
('lisciatura su marmo grigio'),
('lisciatura su marmo italico'),
('lisciatura su marmo lumachella bigia'),
('lisciatura su marmo lumachella d''Egitto'),
('lisciatura su marmo lumachella pavonazza'),
('lisciatura su marmo lumachella rosea'),
('lisciatura su marmo lumachella'),
('lisciatura su marmo lumachellone antico'),
('lisciatura su marmo lunense'),
('lisciatura su marmo nero africano'),
('lisciatura su marmo nero antico'),
('lisciatura su marmo occhio di pavone bianco'),
('lisciatura su marmo occhio di pavone bigio'),
('lisciatura su marmo occhio di pavone pavonazzo'),
('lisciatura su marmo occhio di pavone roseo'),
('lisciatura su marmo occhio di pavone rosso'),
('lisciatura su marmo palombino'),
('lisciatura su marmo pario'),
('lisciatura su marmo pavonazzetto'),
('lisciatura su marmo pentelico'),
('lisciatura su marmo policromo'),
('lisciatura su marmo portasanta'),
('lisciatura su marmo proconnesio'),
('lisciatura su marmo rosa'),
('lisciatura su marmo rosso antico'),
('lisciatura su marmo rosso brecciato'),
('lisciatura su marmo semesanto'),
('lisciatura su marmo serpentina moschinata'),
('lisciatura su marmo verde antico'),
('lisciatura su marmo verde rana fibroso'),
('lisciatura su marmo verde rana ondato'),
('lisciatura su marmo'),
('lisciatura su osso'),
('lisciatura su pietra'),
('lisciatura su travertino'),
('lisciatura su tufo giallo litoide'),
('lisciatura su tufo grigio'),
('lisciatura su tufo Nocerino'),
('lisciatura su tufo rosso a scorie nere'),
('lisciatura su tufo rosso litoide'),
('lisciatura su tufo Sabazio'),
('lisciatura su tufo trachitico'),
('lisciatura su tufo Vulsinio'),
('lisciatura su tufo'),
('lisciatura'),
('lucidatura a stecca su impasto'),
('lucidatura a stecca'),
('lucidatura su argento'),
('lucidatura su argilla'),
('lucidatura su bronzo'),
('lucidatura su bucchero'),
('lucidatura su calcare'),
('lucidatura su corallo'),
('lucidatura su corniola'),
('lucidatura su ematite'),
('lucidatura su granito'),
('lucidatura su impasto'),
('lucidatura su metallo'),
('lucidatura su pietra ollare'),
('lucidatura'),
('mano'),
('marmo a mosaico'),
('marmo africano a mosaico'),
('marmo asiatico a mosaico'),
('marmo bardiglio di Carrara a mosaico'),
('marmo bianco a mosaico'),
('marmo bianco greco a mosaico'),
('marmo bianco italico a mosaico'),
('marmo bianco venato a mosaico'),
('marmo bigio a mosaico'),
('marmo bigio antico a mosaico'),
('marmo bigio morato a mosaico'),
('marmo broccatello a mosaico'),
('marmo broccatello di Verona a mosaico'),
('marmo broccatellone a mosaico'),
('marmo cipollino a mosaico'),
('marmo cipollino mandolato a mosaico'),
('marmo cipollino marino a mosaico'),
('marmo cipollino rosso a mosaico'),
('marmo cottanello antico a mosaico'),
('marmo dell''Imetto a mosaico'),
('marmo di Carrara a mosaico'),
('marmo di Proconneso a mosaico'),
('marmo di Taso a mosaico'),
('marmo fior di pesco a mosaico'),
('marmo giallo antico a mosaico'),
('marmo giallo antico brecciato a mosaico'),
('marmo giallo tigrato a mosaico'),
('marmo greco insulare a mosaico'),
('marmo greco scritto a mosaico'),
('marmo grigio a mosaico'),
('marmo grigio brecciato a mosaico'),
('marmo grigio venato a mosaico'),
('marmo italico a mosaico'),
('marmo lumachella a mosaico'),
('marmo lumachella bigia a mosaico'),
('marmo lumachella d''Egitto a mosaico'),
('marmo lumachella pavonazza a mosaico'),
('marmo lumachella rosea a mosaico'),
('marmo lumachellone antico a mosaico'),
('marmo lunense a mosaico'),
('marmo nero africano a mosaico'),
('marmo nero antico a mosaico'),
('marmo occhio di pavone bianco a mosaico'),
('marmo occhio di pavone bigio a mosaico'),
('marmo occhio di pavone pavonazzo a mosaico'),
('marmo occhio di pavone roseo a mosaico'),
('marmo occhio di pavone rosso a mosaico'),
('marmo palombino a mosaico'),
('marmo pario a mosaico'),
('marmo pavonazzetto a mosaico'),
('marmo pentelico a mosaico'),
('marmo policromo a mosaico'),
('marmo portasanta a mosaico'),
('marmo proconnesio a mosaico'),
('marmo rosa a mosaico'),
('marmo rosso antico a mosaico'),
('marmo rosso brecciato a mosaico'),
('marmo semesanto a mosaico'),
('marmo serpentina moschinata a mosaico'),
('marmo verde antico a mosaico'),
('marmo verde rana fibroso a mosaico'),
('marmo verde rana ondato a mosaico'),
('martellatura su argento'),
('martellatura su bronzo'),
('martellatura su ferro'),
('martellatura su lega metallica'),
('martellatura su metallo'),
('martellatura su oro'),
('martellatura su piombo'),
('martellatura su rame'),
('martellatura'),
('martellinatura su calcare'),
('martellinatura su marmo africano'),
('martellinatura su marmo asiatico'),
('martellinatura su marmo bardiglio di Carrara'),
('martellinatura su marmo bianco greco'),
('martellinatura su marmo bianco italico'),
('martellinatura su marmo bianco venato'),
('martellinatura su marmo bianco'),
('martellinatura su marmo bigio antico'),
('martellinatura su marmo bigio morato'),
('martellinatura su marmo bigio'),
('martellinatura su marmo broccatello di Verona'),
('martellinatura su marmo broccatello'),
('martellinatura su marmo broccatellone'),
('martellinatura su marmo cipollino mandolato'),
('martellinatura su marmo cipollino marino'),
('martellinatura su marmo cipollino rosso'),
('martellinatura su marmo cipollino'),
('martellinatura su marmo cottanello antico'),
('martellinatura su marmo dell''Imetto'),
('martellinatura su marmo di Carrara'),
('martellinatura su marmo di Proconneso'),
('martellinatura su marmo di Taso'),
('martellinatura su marmo fior di pesco'),
('martellinatura su marmo giallo antico brecciato'),
('martellinatura su marmo giallo antico'),
('martellinatura su marmo giallo tigrato'),
('martellinatura su marmo greco insulare'),
('martellinatura su marmo greco scritto'),
('martellinatura su marmo grigio brecciato'),
('martellinatura su marmo grigio venato'),
('martellinatura su marmo grigio'),
('martellinatura su marmo italico'),
('martellinatura su marmo lumachella bigia'),
('martellinatura su marmo lumachella d''Egitto'),
('martellinatura su marmo lumachella pavonazza'),
('martellinatura su marmo lumachella rosea'),
('martellinatura su marmo lumachella'),
('martellinatura su marmo lumachellone antico'),
('martellinatura su marmo lunense'),
('martellinatura su marmo nero africano'),
('martellinatura su marmo nero antico'),
('martellinatura su marmo occhio di pavone bianco'),
('martellinatura su marmo occhio di pavone bigio'),
('martellinatura su marmo occhio di pavone pavonazzo'),
('martellinatura su marmo occhio di pavone roseo'),
('martellinatura su marmo occhio di pavone rosso'),
('martellinatura su marmo palombino'),
('martellinatura su marmo pario'),
('martellinatura su marmo pavonazzetto'),
('martellinatura su marmo pentelico'),
('martellinatura su marmo policromo'),
('martellinatura su marmo portasanta'),
('martellinatura su marmo proconnesio'),
('martellinatura su marmo rosa'),
('martellinatura su marmo rosso antico'),
('martellinatura su marmo rosso brecciato'),
('martellinatura su marmo semesanto'),
('martellinatura su marmo serpentina moschinata'),
('martellinatura su marmo verde antico'),
('martellinatura su marmo verde rana fibroso'),
('martellinatura su marmo verde rana ondato'),
('martellinatura su marmo'),
('martellinatura su pietra'),
('martellinatura'),
('matrice'),
('metallo a sbalzo'),
('modellazione su bastoncino su vetro'),
('modellazione su bastoncino'),
('modellazione su nucleo su vetro'),
('modellazione su nucleo'),
('molatura su vetro'),
('molatura'),
('mosaico'),
('niello su acciaio'),
('niello su argento'),
('niello su bronzo'),
('niello su metallo'),
('niello su oro'),
('niello su rame'),
('niello'),
('opus sectile su marmo africano'),
('opus sectile su marmo asiatico'),
('opus sectile su marmo bardiglio di Carrara'),
('opus sectile su marmo bianco greco'),
('opus sectile su marmo bianco italico'),
('opus sectile su marmo bianco venato'),
('opus sectile su marmo bianco'),
('opus sectile su marmo bigio antico'),
('opus sectile su marmo bigio morato'),
('opus sectile su marmo bigio'),
('opus sectile su marmo broccatello di Verona'),
('opus sectile su marmo broccatello'),
('opus sectile su marmo broccatellone'),
('opus sectile su marmo cipollino mandolato'),
('opus sectile su marmo cipollino marino'),
('opus sectile su marmo cipollino rosso'),
('opus sectile su marmo cipollino'),
('opus sectile su marmo cottanello antico'),
('opus sectile su marmo dell''Imetto'),
('opus sectile su marmo di Carrara'),
('opus sectile su marmo di Proconneso'),
('opus sectile su marmo di Taso'),
('opus sectile su marmo fior di pesco'),
('opus sectile su marmo giallo antico brecciato'),
('opus sectile su marmo giallo antico'),
('opus sectile su marmo giallo tigrato'),
('opus sectile su marmo greco insulare'),
('opus sectile su marmo greco scritto'),
('opus sectile su marmo grigio brecciato'),
('opus sectile su marmo grigio venato'),
('opus sectile su marmo grigio'),
('opus sectile su marmo italico'),
('opus sectile su marmo lumachella bigia'),
('opus sectile su marmo lumachella d''Egitto'),
('opus sectile su marmo lumachella pavonazza'),
('opus sectile su marmo lumachella rosea'),
('opus sectile su marmo lumachella'),
('opus sectile su marmo lumachellone antico'),
('opus sectile su marmo lunense'),
('opus sectile su marmo nero africano'),
('opus sectile su marmo nero antico'),
('opus sectile su marmo occhio di pavone bianco'),
('opus sectile su marmo occhio di pavone bigio'),
('opus sectile su marmo occhio di pavone pavonazzo'),
('opus sectile su marmo occhio di pavone roseo'),
('opus sectile su marmo occhio di pavone rosso'),
('opus sectile su marmo palombino'),
('opus sectile su marmo pario'),
('opus sectile su marmo pavonazzetto'),
('opus sectile su marmo pentelico'),
('opus sectile su marmo policromo'),
('opus sectile su marmo portasanta'),
('opus sectile su marmo proconnesio'),
('opus sectile su marmo rosa'),
('opus sectile su marmo rosso antico'),
('opus sectile su marmo rosso brecciato'),
('opus sectile su marmo semesanto'),
('opus sectile su marmo serpentina moschinata'),
('opus sectile su marmo verde antico'),
('opus sectile su marmo verde rana fibroso'),
('opus sectile su marmo verde rana ondato'),
('opus sectile su marmo'),
('opus sectile'),
('opus tessellatum su marmo africano'),
('opus tessellatum su marmo asiatico'),
('opus tessellatum su marmo bardiglio di Carrara'),
('opus tessellatum su marmo bianco greco'),
('opus tessellatum su marmo bianco italico'),
('opus tessellatum su marmo bianco venato'),
('opus tessellatum su marmo bianco'),
('opus tessellatum su marmo bigio antico'),
('opus tessellatum su marmo bigio morato'),
('opus tessellatum su marmo bigio'),
('opus tessellatum su marmo broccatello di Verona'),
('opus tessellatum su marmo broccatello'),
('opus tessellatum su marmo broccatellone'),
('opus tessellatum su marmo cipollino mandolato'),
('opus tessellatum su marmo cipollino marino'),
('opus tessellatum su marmo cipollino rosso'),
('opus tessellatum su marmo cipollino'),
('opus tessellatum su marmo cottanello antico'),
('opus tessellatum su marmo dell''Imetto'),
('opus tessellatum su marmo di Carrara'),
('opus tessellatum su marmo di Proconneso'),
('opus tessellatum su marmo di Taso'),
('opus tessellatum su marmo fior di pesco'),
('opus tessellatum su marmo giallo antico brecciato'),
('opus tessellatum su marmo giallo antico'),
('opus tessellatum su marmo giallo tigrato'),
('opus tessellatum su marmo greco insulare'),
('opus tessellatum su marmo greco scritto'),
('opus tessellatum su marmo grigio brecciato'),
('opus tessellatum su marmo grigio venato'),
('opus tessellatum su marmo grigio'),
('opus tessellatum su marmo italico'),
('opus tessellatum su marmo lumachella bigia'),
('opus tessellatum su marmo lumachella d''Egitto'),
('opus tessellatum su marmo lumachella pavonazza'),
('opus tessellatum su marmo lumachella rosea'),
('opus tessellatum su marmo lumachella'),
('opus tessellatum su marmo lumachellone antico'),
('opus tessellatum su marmo lunense'),
('opus tessellatum su marmo nero africano'),
('opus tessellatum su marmo nero antico'),
('opus tessellatum su marmo occhio di pavone bianco'),
('opus tessellatum su marmo occhio di pavone bigio'),
('opus tessellatum su marmo occhio di pavone pavonazzo'),
('opus tessellatum su marmo occhio di pavone roseo'),
('opus tessellatum su marmo occhio di pavone rosso'),
('opus tessellatum su marmo palombino'),
('opus tessellatum su marmo pario'),
('opus tessellatum su marmo pavonazzetto'),
('opus tessellatum su marmo pentelico'),
('opus tessellatum su marmo policromo'),
('opus tessellatum su marmo portasanta'),
('opus tessellatum su marmo proconnesio'),
('opus tessellatum su marmo rosa'),
('opus tessellatum su marmo rosso antico'),
('opus tessellatum su marmo rosso brecciato'),
('opus tessellatum su marmo semesanto'),
('opus tessellatum su marmo serpentina moschinata'),
('opus tessellatum su marmo verde antico'),
('opus tessellatum su marmo verde rana fibroso'),
('opus tessellatum su marmo verde rana ondato'),
('opus tessellatum su marmo'),
('opus tessellatum'),
('oro a sbalzo'),
('patinatura su bronzo'),
('patinatura'),
('percussione su pietra'),
('percussione su selce'),
('percussione'),
('pettine su argilla'),
('pettine su impasto'),
('pettine'),
('picchiettatura su marmo africano'),
('picchiettatura su marmo asiatico'),
('picchiettatura su marmo bardiglio di Carrara'),
('picchiettatura su marmo bianco greco'),
('picchiettatura su marmo bianco italico'),
('picchiettatura su marmo bianco venato'),
('picchiettatura su marmo bianco'),
('picchiettatura su marmo bigio antico'),
('picchiettatura su marmo bigio morato'),
('picchiettatura su marmo bigio'),
('picchiettatura su marmo broccatello di Verona'),
('picchiettatura su marmo broccatello'),
('picchiettatura su marmo broccatellone'),
('picchiettatura su marmo cipollino mandolato'),
('picchiettatura su marmo cipollino marino'),
('picchiettatura su marmo cipollino rosso'),
('picchiettatura su marmo cipollino'),
('picchiettatura su marmo cottanello antico'),
('picchiettatura su marmo dell''Imetto'),
('picchiettatura su marmo di Carrara'),
('picchiettatura su marmo di Proconneso'),
('picchiettatura su marmo di Taso'),
('picchiettatura su marmo fior di pesco'),
('picchiettatura su marmo giallo antico brecciato'),
('picchiettatura su marmo giallo antico'),
('picchiettatura su marmo giallo tigrato'),
('picchiettatura su marmo greco insulare'),
('picchiettatura su marmo greco scritto'),
('picchiettatura su marmo grigio brecciato'),
('picchiettatura su marmo grigio venato'),
('picchiettatura su marmo grigio'),
('picchiettatura su marmo italico'),
('picchiettatura su marmo lumachella bigia'),
('picchiettatura su marmo lumachella d''Egitto'),
('picchiettatura su marmo lumachella pavonazza'),
('picchiettatura su marmo lumachella rosea'),
('picchiettatura su marmo lumachella'),
('picchiettatura su marmo lumachellone antico'),
('picchiettatura su marmo lunense'),
('picchiettatura su marmo nero africano'),
('picchiettatura su marmo nero antico'),
('picchiettatura su marmo occhio di pavone bianco'),
('picchiettatura su marmo occhio di pavone bigio'),
('picchiettatura su marmo occhio di pavone pavonazzo'),
('picchiettatura su marmo occhio di pavone roseo'),
('picchiettatura su marmo occhio di pavone rosso'),
('picchiettatura su marmo palombino'),
('picchiettatura su marmo pario'),
('picchiettatura su marmo pavonazzetto'),
('picchiettatura su marmo pentelico'),
('picchiettatura su marmo policromo'),
('picchiettatura su marmo portasanta'),
('picchiettatura su marmo proconnesio'),
('picchiettatura su marmo rosa'),
('picchiettatura su marmo rosso antico'),
('picchiettatura su marmo rosso brecciato'),
('picchiettatura su marmo semesanto'),
('picchiettatura su marmo serpentina moschinata'),
('picchiettatura su marmo verde antico'),
('picchiettatura su marmo verde rana fibroso'),
('picchiettatura su marmo verde rana ondato'),
('picchiettatura su marmo'),
('picchiettatura'),
('pietra a mosaico'),
('pinzatura su oro'),
('pinzatura su vetro'),
('pinzatura'),
('piombo a sbalzo'),
('pittura a encausto su intonaco'),
('pittura a encausto'),
('pittura a fresco su intonaco'),
('pittura a fresco'),
('pittura a tempera su intonaco'),
('pittura a tempera'),
('plique-a-jour su metallo'),
('plique-a-jour'),
('politura a ruota su vetro'),
('politura a ruota'),
('politura su alabastro a pecorella'),
('politura su alabastro a tartaruga'),
('politura su alabastro bianco'),
('politura su alabastro del Gebel Oust'),
('politura su alabastro di Palombara'),
('politura su alabastro dorato'),
('politura su alabastro egiziano'),
('politura su alabastro fiorito'),
('politura su alabastro marino'),
('politura su alabastro'),
('politura su ambra'),
('politura su ametista'),
('politura su breccia'),
('politura su osso'),
('politura'),
('puddellaggio su ferro'),
('puddellaggio'),
('punzone su argento'),
('punzone su argilla'),
('punzone su bronzo'),
('punzone su laterizio'),
('punzone su metallo'),
('punzone su oro'),
('punzone'),
('rame a sbalzo'),
('raschiatura su ambra'),
('raschiatura'),
('repousse su argento'),
('repousse su metallo'),
('repousse su oro'),
('repousse'),
('ribattitura su argento'),
('ribattitura su bronzo'),
('ribattitura su ferro'),
('ribattitura su metallo'),
('ribattitura su rame'),
('ribattitura'),
('rifinitura a freddo su bronzo'),
('rifinitura a freddo'),
('rilievo applicato su argilla'),
('rilievo applicato su bucchero'),
('rilievo applicato su impasto'),
('rilievo applicato'),
('ritaglio su bronzo'),
('ritaglio'),
('ritocco a mano su argilla'),
('ritocco a mano su laterizio'),
('ritocco a mano'),
('ritocco a stecca su argilla'),
('ritocco a stecca su impasto'),
('ritocco a stecca su laterizio'),
('ritocco a stecca'),
('rotella su argilla'),
('rotella su bucchero'),
('rotella su impasto'),
('rotella'),
('rubricatura su marmo'),
('rubricatura'),
('sabbiatura su argilla'),
('sabbiatura'),
('saldatura su acciaio'),
('saldatura su argento'),
('saldatura su bronzo'),
('saldatura su ferro'),
('saldatura su lega metallica'),
('saldatura su metallo'),
('saldatura su oro'),
('saldatura su piombo'),
('saldatura su rame'),
('saldatura'),
('sbalzo'),
('sbozzatura su calcare'),
('sbozzatura su corno'),
('sbozzatura su marmo africano'),
('sbozzatura su marmo asiatico'),
('sbozzatura su marmo bardiglio di Carrara'),
('sbozzatura su marmo bianco greco'),
('sbozzatura su marmo bianco italico'),
('sbozzatura su marmo bianco venato'),
('sbozzatura su marmo bianco'),
('sbozzatura su marmo bigio antico'),
('sbozzatura su marmo bigio morato'),
('sbozzatura su marmo bigio'),
('sbozzatura su marmo broccatello di Verona'),
('sbozzatura su marmo broccatello'),
('sbozzatura su marmo broccatellone'),
('sbozzatura su marmo cipollino mandolato'),
('sbozzatura su marmo cipollino marino'),
('sbozzatura su marmo cipollino rosso'),
('sbozzatura su marmo cipollino'),
('sbozzatura su marmo cottanello antico'),
('sbozzatura su marmo dell''Imetto'),
('sbozzatura su marmo di Carrara'),
('sbozzatura su marmo di Proconneso'),
('sbozzatura su marmo di Taso'),
('sbozzatura su marmo fior di pesco'),
('sbozzatura su marmo giallo antico brecciato'),
('sbozzatura su marmo giallo antico'),
('sbozzatura su marmo giallo tigrato'),
('sbozzatura su marmo greco insulare'),
('sbozzatura su marmo greco scritto'),
('sbozzatura su marmo grigio brecciato'),
('sbozzatura su marmo grigio venato'),
('sbozzatura su marmo grigio'),
('sbozzatura su marmo italico'),
('sbozzatura su marmo lumachella bigia'),
('sbozzatura su marmo lumachella d''Egitto'),
('sbozzatura su marmo lumachella pavonazza'),
('sbozzatura su marmo lumachella rosea'),
('sbozzatura su marmo lumachella'),
('sbozzatura su marmo lumachellone antico'),
('sbozzatura su marmo lunense'),
('sbozzatura su marmo nero africano'),
('sbozzatura su marmo nero antico'),
('sbozzatura su marmo occhio di pavone bianco'),
('sbozzatura su marmo occhio di pavone bigio'),
('sbozzatura su marmo occhio di pavone pavonazzo'),
('sbozzatura su marmo occhio di pavone roseo'),
('sbozzatura su marmo occhio di pavone rosso'),
('sbozzatura su marmo palombino'),
('sbozzatura su marmo pario'),
('sbozzatura su marmo pavonazzetto'),
('sbozzatura su marmo pentelico'),
('sbozzatura su marmo policromo'),
('sbozzatura su marmo portasanta'),
('sbozzatura su marmo proconnesio'),
('sbozzatura su marmo rosa'),
('sbozzatura su marmo rosso antico'),
('sbozzatura su marmo rosso brecciato'),
('sbozzatura su marmo semesanto'),
('sbozzatura su marmo serpentina moschinata'),
('sbozzatura su marmo verde antico'),
('sbozzatura su marmo verde rana fibroso'),
('sbozzatura su marmo verde rana ondato'),
('sbozzatura su marmo'),
('sbozzatura su nenfro'),
('sbozzatura su ofiolite'),
('sbozzatura su pietra ollare'),
('sbozzatura su pietra'),
('sbozzatura su tufo giallo litoide'),
('sbozzatura su tufo grigio'),
('sbozzatura su tufo Nocerino'),
('sbozzatura su tufo rosso a scorie nere'),
('sbozzatura su tufo rosso litoide'),
('sbozzatura su tufo Sabazio'),
('sbozzatura su tufo trachitico'),
('sbozzatura su tufo Vulsinio'),
('sbozzatura su tufo'),
('sbozzatura'),
('scalpellatura su alabastro a pecorella'),
('scalpellatura su alabastro a tartaruga'),
('scalpellatura su alabastro bianco'),
('scalpellatura su alabastro del Gebel Oust'),
('scalpellatura su alabastro di Palombara'),
('scalpellatura su alabastro dorato'),
('scalpellatura su alabastro egiziano'),
('scalpellatura su alabastro fiorito'),
('scalpellatura su alabastro marino'),
('scalpellatura su alabastro'),
('scalpellatura su ardesia'),
('scalpellatura su arenaria'),
('scalpellatura su basalto'),
('scalpellatura su basanite'),
('scalpellatura su breccia'),
('scalpellatura su calcare'),
('scalpellatura su calcarenite'),
('scalpellatura su clorite'),
('scalpellatura su granito'),
('scalpellatura su marmo africano'),
('scalpellatura su marmo asiatico'),
('scalpellatura su marmo bardiglio di Carrara'),
('scalpellatura su marmo bianco greco'),
('scalpellatura su marmo bianco italico'),
('scalpellatura su marmo bianco venato'),
('scalpellatura su marmo bianco'),
('scalpellatura su marmo bigio antico'),
('scalpellatura su marmo bigio morato'),
('scalpellatura su marmo bigio'),
('scalpellatura su marmo broccatello di Verona'),
('scalpellatura su marmo broccatello'),
('scalpellatura su marmo broccatellone'),
('scalpellatura su marmo cipollino mandolato'),
('scalpellatura su marmo cipollino marino'),
('scalpellatura su marmo cipollino rosso'),
('scalpellatura su marmo cipollino'),
('scalpellatura su marmo cottanello antico'),
('scalpellatura su marmo dell''Imetto'),
('scalpellatura su marmo di Carrara'),
('scalpellatura su marmo di Proconneso'),
('scalpellatura su marmo di Taso'),
('scalpellatura su marmo fior di pesco'),
('scalpellatura su marmo giallo antico brecciato'),
('scalpellatura su marmo giallo antico'),
('scalpellatura su marmo giallo tigrato'),
('scalpellatura su marmo greco insulare'),
('scalpellatura su marmo greco scritto'),
('scalpellatura su marmo grigio brecciato'),
('scalpellatura su marmo grigio venato'),
('scalpellatura su marmo grigio'),
('scalpellatura su marmo italico'),
('scalpellatura su marmo lumachella bigia'),
('scalpellatura su marmo lumachella d''Egitto'),
('scalpellatura su marmo lumachella pavonazza'),
('scalpellatura su marmo lumachella rosea'),
('scalpellatura su marmo lumachella'),
('scalpellatura su marmo lumachellone antico'),
('scalpellatura su marmo lunense'),
('scalpellatura su marmo nero africano'),
('scalpellatura su marmo nero antico'),
('scalpellatura su marmo occhio di pavone bianco'),
('scalpellatura su marmo occhio di pavone bigio'),
('scalpellatura su marmo occhio di pavone pavonazzo'),
('scalpellatura su marmo occhio di pavone roseo'),
('scalpellatura su marmo occhio di pavone rosso'),
('scalpellatura su marmo palombino'),
('scalpellatura su marmo pario'),
('scalpellatura su marmo pavonazzetto'),
('scalpellatura su marmo pentelico'),
('scalpellatura su marmo policromo'),
('scalpellatura su marmo portasanta'),
('scalpellatura su marmo proconnesio'),
('scalpellatura su marmo rosa'),
('scalpellatura su marmo rosso antico'),
('scalpellatura su marmo rosso brecciato'),
('scalpellatura su marmo semesanto'),
('scalpellatura su marmo serpentina moschinata'),
('scalpellatura su marmo verde antico'),
('scalpellatura su marmo verde rana fibroso'),
('scalpellatura su marmo verde rana ondato'),
('scalpellatura su marmo'),
('scalpellatura su nenfro'),
('scalpellatura su ofiolite'),
('scalpellatura su ossidiana'),
('scalpellatura su osso'),
('scalpellatura su peperino'),
('scalpellatura su pietra ollare'),
('scalpellatura su pietra'),
('scalpellatura su porfido bigio'),
('scalpellatura su porfido nero grafico'),
('scalpellatura su porfido nero'),
('scalpellatura su porfido rosso'),
('scalpellatura su porfido verde di Laconia'),
('scalpellatura su porfido verde egiziano'),
('scalpellatura su porfido'),
('scalpellatura su puddinga'),
('scalpellatura su trachite dei Colli Euganei'),
('scalpellatura su trachite'),
('scalpellatura su travertino'),
('scalpellatura su tufo giallo litoide'),
('scalpellatura su tufo grigio'),
('scalpellatura su tufo Nocerino'),
('scalpellatura su tufo rosso a scorie nere'),
('scalpellatura su tufo rosso litoide'),
('scalpellatura su tufo Sabazio'),
('scalpellatura su tufo trachitico'),
('scalpellatura su tufo Vulsinio'),
('scalpellatura su tufo'),
('scalpellatura'),
('scheggiatura su arenaria'),
('scheggiatura su calcare'),
('scheggiatura su diaspro'),
('scheggiatura su eliotropio'),
('scheggiatura su legno'),
('scheggiatura su ossidiana'),
('scheggiatura su osso'),
('scheggiatura su quarzite'),
('scheggiatura su quarzo'),
('scheggiatura su selce'),
('scheggiatura'),
('scialbatura su argilla'),
('scialbatura su impasto'),
('scialbatura su laterizio'),
('scialbatura su tufo giallo litoide'),
('scialbatura su tufo grigio'),
('scialbatura su tufo Nocerino'),
('scialbatura su tufo rosso a scorie nere'),
('scialbatura su tufo rosso litoide'),
('scialbatura su tufo Sabazio'),
('scialbatura su tufo trachitico'),
('scialbatura su tufo Vulsinio'),
('scialbatura su tufo'),
('scialbatura'),
('segagione su osso'),
('segagione'),
('sgraffio su argilla'),
('sgraffio'),
('smaltatura su acciaio'),
('smaltatura su argento'),
('smaltatura su argilla'),
('smaltatura su bronzo'),
('smaltatura su ferro'),
('smaltatura su lega metallica'),
('smaltatura su metallo'),
('smaltatura su oro'),
('smaltatura su rame'),
('smaltatura su vetro'),
('smaltatura'),
('soffiatura a stampo su vetro'),
('soffiatura a stampo'),
('soffiatura libera su vetro'),
('soffiatura libera'),
('soffiatura su vetro'),
('soffiatura'),
('spatola su stucco'),
('spatola'),
('spruzzo'),
('stagnatura su bronzo'),
('stagnatura'),
('stampaggio su argento'),
('stampaggio su bronzo'),
('stampaggio su metallo'),
('stampaggio su oro'),
('stampaggio su piombo'),
('stampaggio'),
('stampo su argento'),
('stampo su argilla'),
('stampo su bronzo'),
('stampo su bucchero'),
('stampo su ceralacca'),
('stampo su impasto'),
('stampo su metallo'),
('stampo su oro'),
('stampo su rame'),
('stampo'),
('stecca su argilla'),
('stecca'),
('stralucido su argilla'),
('stralucido su bucchero'),
('stralucido su impasto'),
('stralucido'),
('subbiatura su marmo africano'),
('subbiatura su marmo asiatico'),
('subbiatura su marmo bardiglio di Carrara'),
('subbiatura su marmo bianco greco'),
('subbiatura su marmo bianco italico'),
('subbiatura su marmo bianco venato'),
('subbiatura su marmo bianco'),
('subbiatura su marmo bigio antico'),
('subbiatura su marmo bigio morato'),
('subbiatura su marmo bigio'),
('subbiatura su marmo broccatello di Verona'),
('subbiatura su marmo broccatello'),
('subbiatura su marmo broccatellone'),
('subbiatura su marmo cipollino mandolato'),
('subbiatura su marmo cipollino marino'),
('subbiatura su marmo cipollino rosso'),
('subbiatura su marmo cipollino'),
('subbiatura su marmo cottanello antico'),
('subbiatura su marmo dell''Imetto'),
('subbiatura su marmo di Carrara'),
('subbiatura su marmo di Proconneso'),
('subbiatura su marmo di Taso'),
('subbiatura su marmo fior di pesco'),
('subbiatura su marmo giallo antico brecciato'),
('subbiatura su marmo giallo antico'),
('subbiatura su marmo giallo tigrato'),
('subbiatura su marmo greco insulare'),
('subbiatura su marmo greco scritto'),
('subbiatura su marmo grigio brecciato'),
('subbiatura su marmo grigio venato'),
('subbiatura su marmo grigio'),
('subbiatura su marmo italico'),
('subbiatura su marmo lumachella bigia'),
('subbiatura su marmo lumachella d''Egitto'),
('subbiatura su marmo lumachella pavonazza'),
('subbiatura su marmo lumachella rosea'),
('subbiatura su marmo lumachella'),
('subbiatura su marmo lumachellone antico'),
('subbiatura su marmo lunense'),
('subbiatura su marmo nero africano'),
('subbiatura su marmo nero antico'),
('subbiatura su marmo occhio di pavone bianco'),
('subbiatura su marmo occhio di pavone bigio'),
('subbiatura su marmo occhio di pavone pavonazzo'),
('subbiatura su marmo occhio di pavone roseo'),
('subbiatura su marmo occhio di pavone rosso'),
('subbiatura su marmo palombino'),
('subbiatura su marmo pario'),
('subbiatura su marmo pavonazzetto'),
('subbiatura su marmo pentelico'),
('subbiatura su marmo policromo'),
('subbiatura su marmo portasanta'),
('subbiatura su marmo proconnesio'),
('subbiatura su marmo rosa'),
('subbiatura su marmo rosso antico'),
('subbiatura su marmo rosso brecciato'),
('subbiatura su marmo semesanto'),
('subbiatura su marmo serpentina moschinata'),
('subbiatura su marmo verde antico'),
('subbiatura su marmo verde rana fibroso'),
('subbiatura su marmo verde rana ondato'),
('subbiatura su marmo'),
('subbiatura su pietra'),
('subbiatura'),
('taglio a freddo su vetro'),
('taglio a freddo'),
('taglio su corno'),
('taglio su osso'),
('taglio su pietra'),
('taglio su selce'),
('taglio'),
('tempra su ferro'),
('tempra'),
('tessitura a telaio su canapa'),
('tessitura a telaio su cotone'),
('tessitura a telaio su fibra di canapa'),
('tessitura a telaio su fibra di sparto'),
('tessitura a telaio su lana'),
('tessitura a telaio su lino'),
('tessitura a telaio su tessuto'),
('tessitura a telaio'),
('tornio idraulico su pietra ollare'),
('tornio idraulico'),
('tornio su ambra'),
('tornio su argilla'),
('tornio su bucchero'),
('tornio su cloritoscisto'),
('tornio su gesso alabastrino'),
('tornio su osso'),
('tornio su talco'),
('tornio su talcoscisto'),
('tornio veloce su pietra ollare'),
('tornio veloce'),
('tornio'),
('traforo su bronzo'),
('traforo su bucchero'),
('traforo su lega metallica'),
('traforo su osso'),
('traforo'),
('trapano corrente su calcare'),
('trapano corrente su marmo africano'),
('trapano corrente su marmo asiatico'),
('trapano corrente su marmo bardiglio di Carrara'),
('trapano corrente su marmo bianco greco'),
('trapano corrente su marmo bianco italico'),
('trapano corrente su marmo bianco venato'),
('trapano corrente su marmo bianco'),
('trapano corrente su marmo bigio antico'),
('trapano corrente su marmo bigio morato'),
('trapano corrente su marmo bigio'),
('trapano corrente su marmo broccatello di Verona'),
('trapano corrente su marmo broccatello'),
('trapano corrente su marmo broccatellone'),
('trapano corrente su marmo cipollino mandolato'),
('trapano corrente su marmo cipollino marino'),
('trapano corrente su marmo cipollino rosso'),
('trapano corrente su marmo cipollino'),
('trapano corrente su marmo cottanello antico'),
('trapano corrente su marmo dell''Imetto'),
('trapano corrente su marmo di Carrara'),
('trapano corrente su marmo di Proconneso'),
('trapano corrente su marmo di Taso'),
('trapano corrente su marmo fior di pesco'),
('trapano corrente su marmo giallo antico brecciato'),
('trapano corrente su marmo giallo antico'),
('trapano corrente su marmo giallo tigrato'),
('trapano corrente su marmo greco insulare'),
('trapano corrente su marmo greco scritto'),
('trapano corrente su marmo grigio brecciato'),
('trapano corrente su marmo grigio venato'),
('trapano corrente su marmo grigio'),
('trapano corrente su marmo italico'),
('trapano corrente su marmo lumachella bigia'),
('trapano corrente su marmo lumachella d''Egitto'),
('trapano corrente su marmo lumachella pavonazza'),
('trapano corrente su marmo lumachella rosea'),
('trapano corrente su marmo lumachella'),
('trapano corrente su marmo lumachellone antico'),
('trapano corrente su marmo lunense'),
('trapano corrente su marmo nero africano'),
('trapano corrente su marmo nero antico'),
('trapano corrente su marmo occhio di pavone bianco'),
('trapano corrente su marmo occhio di pavone bigio'),
('trapano corrente su marmo occhio di pavone pavonazzo'),
('trapano corrente su marmo occhio di pavone roseo'),
('trapano corrente su marmo occhio di pavone rosso'),
('trapano corrente su marmo palombino'),
('trapano corrente su marmo pario'),
('trapano corrente su marmo pavonazzetto'),
('trapano corrente su marmo pentelico'),
('trapano corrente su marmo policromo'),
('trapano corrente su marmo portasanta'),
('trapano corrente su marmo proconnesio'),
('trapano corrente su marmo rosa'),
('trapano corrente su marmo rosso antico'),
('trapano corrente su marmo rosso brecciato'),
('trapano corrente su marmo semesanto'),
('trapano corrente su marmo serpentina moschinata'),
('trapano corrente su marmo verde antico'),
('trapano corrente su marmo verde rana fibroso'),
('trapano corrente su marmo verde rana ondato'),
('trapano corrente su marmo'),
('trapano corrente su porfido bigio'),
('trapano corrente su porfido nero grafico'),
('trapano corrente su porfido nero'),
('trapano corrente su porfido rosso'),
('trapano corrente su porfido verde di Laconia'),
('trapano corrente su porfido verde egiziano'),
('trapano corrente su porfido'),
('trapano corrente'),
('trapano su ambra'),
('trapano su basanite'),
('trapano su breccia'),
('trapano su calcare'),
('trapano su corno'),
('trapano su granito'),
('trapano su marmo africano'),
('trapano su marmo asiatico'),
('trapano su marmo bardiglio di Carrara'),
('trapano su marmo bianco greco'),
('trapano su marmo bianco italico'),
('trapano su marmo bianco venato'),
('trapano su marmo bianco'),
('trapano su marmo bigio antico'),
('trapano su marmo bigio morato'),
('trapano su marmo bigio'),
('trapano su marmo broccatello di Verona'),
('trapano su marmo broccatello'),
('trapano su marmo broccatellone'),
('trapano su marmo cipollino mandolato'),
('trapano su marmo cipollino marino'),
('trapano su marmo cipollino rosso'),
('trapano su marmo cipollino'),
('trapano su marmo cottanello antico'),
('trapano su marmo dell''Imetto'),
('trapano su marmo di Carrara'),
('trapano su marmo di Proconneso'),
('trapano su marmo di Taso'),
('trapano su marmo fior di pesco'),
('trapano su marmo giallo antico brecciato'),
('trapano su marmo giallo antico'),
('trapano su marmo giallo tigrato'),
('trapano su marmo greco insulare'),
('trapano su marmo greco scritto'),
('trapano su marmo grigio brecciato'),
('trapano su marmo grigio venato'),
('trapano su marmo grigio'),
('trapano su marmo italico'),
('trapano su marmo lumachella bigia'),
('trapano su marmo lumachella d''Egitto'),
('trapano su marmo lumachella pavonazza'),
('trapano su marmo lumachella rosea'),
('trapano su marmo lumachella'),
('trapano su marmo lumachellone antico'),
('trapano su marmo lunense'),
('trapano su marmo nero africano'),
('trapano su marmo nero antico'),
('trapano su marmo occhio di pavone bianco'),
('trapano su marmo occhio di pavone bigio'),
('trapano su marmo occhio di pavone pavonazzo'),
('trapano su marmo occhio di pavone roseo'),
('trapano su marmo occhio di pavone rosso'),
('trapano su marmo palombino'),
('trapano su marmo pario'),
('trapano su marmo pavonazzetto'),
('trapano su marmo pentelico'),
('trapano su marmo policromo'),
('trapano su marmo portasanta'),
('trapano su marmo proconnesio'),
('trapano su marmo rosa'),
('trapano su marmo rosso antico'),
('trapano su marmo rosso brecciato'),
('trapano su marmo semesanto'),
('trapano su marmo serpentina moschinata'),
('trapano su marmo verde antico'),
('trapano su marmo verde rana fibroso'),
('trapano su marmo verde rana ondato'),
('trapano su marmo'),
('trapano su nenfro'),
('trapano su osso'),
('trapano su pietra'),
('trapano su travertino'),
('trapano'),
('unghiate su argilla'),
('unghiate'),
('verniciatura su argilla'),
('verniciatura su avorio'),
('verniciatura su impasto'),
('verniciatura su marmo asiatico'),
('verniciatura su marmo bianco greco'),
('verniciatura su marmo bianco italico'),
('verniciatura su marmo bianco venato'),
('verniciatura su marmo bianco'),
('verniciatura su marmo bigio'),
('verniciatura su marmo'),
('verniciatura'),
('vetro a spruzzo'),
('zigrinatura su argento'),
('zigrinatura su metallo'),
('zigrinatura');

COMMIT;
