BEGIN;
CREATE TABLE liste.dtm_motivazione_cronologia(id serial PRIMARY KEY, value CHARACTER VARYING UNIQUE NOT NULL);
INSERT INTO liste.dtm_motivazione_cronologia(value) VALUES
('analisi chimico-fisica'),
('analisi dei materiali'),
('analisi della stratigrafia'),
('analisi delle strutture murarie'),
('analisi diagnostiche'),
('analisi iconografica'),
('analisi paleografica'),
('analisi stilistica'),
('analisi storica'),
('analisi storico-scientifica'),
('analisi tipologica'),
('arme'),
('bibliografia'),
('bollo'),
('confronto'),
('contesto'),
('data'),
('data consolare'),
('iscrizione'),
('documentazione'),
('esame intervento'),
('firma'),
('fonte archivistica'),
('inventario museale'),
('grafia'),
('marchio'),
('nota manoscritta'),
('pubblicazione di riferimento'),
('punzone'),
('sigla'),
('simbolo'),
('teoria scientifica'),
('tradizione orale');
COMMIT;
