BEGIN;
CREATE TABLE liste.ra_materia(id serial PRIMARY KEY, value CHARACTER VARYING NOT NULL UNIQUE);
INSERT INTO liste.ra_materia(value) VALUES
('abrasione su osso'),
('abrasione su pietra ollare'),
('acciaio a incisione'),
('acciaio a niello'),
('acciaio a sbalzo'),
('acciaio'),
('acquamarina a cabochon'),
('acquamarina a incisione'),
('acquamarina a intaglio'),
('acquamarina a intarsio'),
('acquamarina'),
('affilatura su ferro'),
('agata a cabochon'),
('agata a incisione'),
('agata a intaglio'),
('agata a intarsio'),
('agata zonata a cabochon'),
('agata zonata a incisione'),
('agata zonata a intaglio'),
('agata zonata a intarsio'),
('agata zonata'),
('agata'),
('agemina in argento su acciaio'),
('agemina in oro su acciaio'),
('agemina su acciaio'),
('agemina su argento'),
('agemina su bronzo'),
('agemina su ferro'),
('agemina su lega metallica'),
('agemina su metallo'),
('agemina su oro'),
('agemina su rame'),
('alabastro a incisione'),
('alabastro a intaglio'),
('alabastro a pecorella a incisione'),
('alabastro a pecorella a intaglio'),
('alabastro a pecorella'),
('alabastro a tartaruga a incisione'),
('alabastro a tartaruga a intaglio'),
('alabastro a tartaruga'),
('alabastro bianco a incisione'),
('alabastro bianco a intaglio'),
('alabastro bianco'),
('alabastro del Gebel Oust a incisione'),
('alabastro del Gebel Oust a intaglio'),
('alabastro del Gebel Oust'),
('alabastro di Palombara a incisione'),
('alabastro di Palombara a intaglio'),
('alabastro di Palombara'),
('alabastro dorato a incisione'),
('alabastro dorato a intaglio'),
('alabastro dorato'),
('alabastro egiziano a incisione'),
('alabastro egiziano a intaglio'),
('alabastro egiziano'),
('alabastro fiorito a incisione'),
('alabastro fiorito a intaglio'),
('alabastro fiorito'),
('alabastro marino a incisione'),
('alabastro marino a intaglio'),
('alabastro marino'),
('alabastro'),
('amazzonite a incisione'),
('amazzonite a intaglio'),
('amazzonite'),
('ambra a cabochon'),
('ambra a incisione'),
('ambra a intaglio'),
('ambra a intarsio'),
('ambra a tornio'),
('ambra a trapano'),
('ambra'),
('ametista a cabochon'),
('ametista a incisione'),
('ametista a intaglio'),
('ametista a intarsio'),
('ametista'),
('ardesia a incisione'),
('ardesia'),
('arenaria a incisione'),
('arenaria'),
('argentatura su bronzo'),
('argentatura su lega metallica'),
('argentatura su rame'),
('argentatura su stagno'),
('argento a basse-taille'),
('argento a bulino'),
('argento a immersione'),
('argento a incisione'),
('argento a intaglio'),
('argento a intarsio'),
('argento a niello'),
('argento a punzone'),
('argento a repousse'),
('argento a sbalzo'),
('argento a stampo'),
('argento'),
('argilla a barbottina'),
('argilla a cassaforma'),
('argilla a cilindretti'),
('argilla a colombino'),
('argilla a ditate'),
('argilla a doppia matrice'),
('argilla a excisione'),
('argilla a graffito'),
('argilla a immersione'),
('argilla a impressione'),
('argilla a incisione'),
('argilla a incrostazione'),
('argilla a intaglio'),
('argilla a mano'),
('argilla a matrice'),
('argilla a pettine'),
('argilla a punzone'),
('argilla a rilievo applicato'),
('argilla a rotella'),
('argilla a sgraffio'),
('argilla a stampo'),
('argilla a stecca'),
('argilla a stralucido'),
('argilla a tornio'),
('argilla a unghiate'),
('argilla'),
('avorio a bulino'),
('avorio a incisione'),
('avorio a intaglio'),
('avorio a intarsio'),
('avorio'),
('basalto a incisione'),
('basalto'),
('basanite a incisione'),
('basanite a intaglio'),
('basanite a trapano'),
('basanite'),
('battitura a caldo su argento'),
('battitura a caldo su ferro'),
('battitura a caldo su metallo'),
('battitura a freddo su bronzo'),
('battitura a stampo su argento'),
('battitura a stampo su metallo'),
('battitura su argento'),
('battitura su bronzo'),
('battitura su elettro'),
('battitura su ferro'),
('battitura su lega metallica'),
('battitura su metallo'),
('battitura su oro'),
('battitura su rame'),
('battitura su stagno'),
('brasatura su bronzo'),
('brasatura su ferro'),
('brasatura su lega metallica'),
('breccia a incisione'),
('breccia a trapano'),
('breccia'),
('bronzo a bulino'),
('bronzo a champleve'),
('bronzo a cloisonne'),
('bronzo a impressione'),
('bronzo a incisione'),
('bronzo a intarsio'),
('bronzo a matrice'),
('bronzo a niello'),
('bronzo a punzone'),
('bronzo a ritaglio'),
('bronzo a sbalzo'),
('bronzo a stampo'),
('bronzo a traforo'),
('bronzo'),
('brunitura su acciaio'),
('brunitura su argento'),
('brunitura su bronzo'),
('brunitura su ferro'),
('brunitura su lega metallica'),
('brunitura su metallo'),
('brunitura su rame'),
('bucchero a excisione'),
('bucchero a graffito'),
('bucchero a impressione'),
('bucchero a incisione'),
('bucchero a mano'),
('bucchero a rilievo applicato'),
('bucchero a rotella'),
('bucchero a stampo'),
('bucchero a stralucido'),
('bucchero a tornio'),
('bucchero a traforo'),
('bucchero'),
('calcare a gradina'),
('calcare a incisione'),
('calcare a trapano corrente'),
('calcare a trapano'),
('calcare'),
('calcarenite'),
('calce'),
('calcedonio a cabochon'),
('calcedonio a incisione'),
('calcedonio a intaglio'),
('calcedonio a intarsio'),
('calcedonio'),
('canapa'),
('cappellaccio'),
('ceralacca a stampo'),
('ceralacca'),
('cesellatura su acciaio'),
('cesellatura su argento'),
('cesellatura su bronzo'),
('cesellatura su lega metallica'),
('cesellatura su metallo'),
('cesellatura su oro'),
('cesellatura su piombo'),
('cesellatura su rame'),
('clorite'),
('cloritoscisto a tornio'),
('cloritoscisto'),
('cocciopesto'),
('colatura a stampo su vetro'),
('conchiglia a intaglio'),
('conchiglia'),
('coniazione su argento'),
('coniazione su bronzo'),
('coniazione su elettro'),
('coniazione su lega metallica'),
('coniazione su metallo'),
('corallo a incisione'),
('corallo a intaglio'),
('corallo a intarsio'),
('corallo'),
('corindone'),
('corniola a incisione'),
('corniola a intaglio'),
('corniola'),
('corno a bulino'),
('corno a incisione'),
('corno a intaglio'),
('corno a intarsio'),
('corno a trapano'),
('corno'),
('cotone'),
('cristallo di rocca a incisione'),
('cristallo di rocca a intaglio'),
('cristallo di rocca'),
('cuoio'),
('damaschinatura su acciaio'),
('damaschinatura su ferro'),
('damaschinatura su lega metallica'),
('damaschinatura su rame'),
('diamante a incisione'),
('diamante'),
('diaspro a cabochon'),
('diaspro a incisione'),
('diaspro a intaglio'),
('diaspro a intarsio'),
('diaspro'),
('diorite'),
('doratura a foglia su argento'),
('doratura a foglia su ferro'),
('doratura a foglia su metallo'),
('doratura a mercurio su argento'),
('doratura a mercurio su ferro'),
('doratura a mercurio su metallo'),
('doratura su acciaio'),
('doratura su argento'),
('doratura su bronzo'),
('doratura su ferro'),
('doratura su lega metallica'),
('doratura su metallo'),
('doratura su rame'),
('doratura su stagno'),
('doratura su vetro'),
('elettro'),
('eliotropio a cabochon'),
('eliotropio a incisione'),
('eliotropio a intaglio'),
('eliotropio a intarsio'),
('eliotropio'),
('ematite a incisione'),
('ematite a intaglio'),
('ematite'),
('eufotide'),
('faience'),
('ferro a bulino'),
('ferro a champleve'),
('ferro a incisione'),
('ferro a intarsio'),
('ferro a sbalzo'),
('ferro'),
('fibra di canapa'),
('fibra di sparto'),
('filatura su argento'),
('filatura su lega metallica'),
('filatura su metallo'),
('filatura su oro'),
('filatura su rame'),
('filigrana su argento'),
('filigrana su metallo'),
('filigrana su oro'),
('filigrana su rame'),
('finitura a stecca su pietra ollare'),
('finitura al tornio su avorio'),
('finitura al tornio su pietra ollare'),
('foratura su acquamarina'),
('foratura su agata zonata'),
('foratura su agata'),
('foratura su amazzonite'),
('foratura su ambra'),
('foratura su ametista'),
('foratura su argento'),
('foratura su avorio'),
('foratura su calcedonio'),
('foratura su conchiglia'),
('foratura su corallo'),
('foratura su corniola'),
('foratura su cristallo di rocca'),
('foratura su diaspro'),
('foratura su eliotropio'),
('foratura su ematite'),
('foratura su faience'),
('foratura su giada'),
('foratura su giaietto'),
('foratura su granato'),
('foratura su lapislazzuli'),
('foratura su malachite'),
('foratura su metallo'),
('foratura su pasta vitrea'),
('foratura su perla'),
('foratura su plasma'),
('foratura su prasio'),
('foratura su quarzo rosa'),
('forgiatura su argento'),
('forgiatura su bronzo'),
('forgiatura su ferro'),
('forgiatura su lega metallica'),
('forgiatura su metallo'),
('forgiatura su oro'),
('forgiatura su rame'),
('fusione a cera persa su argento'),
('fusione a cera persa su bronzo'),
('fusione a cera persa su lega metallica'),
('fusione a cera persa su metallo'),
('fusione a cera persa su oro'),
('fusione a matrice su piombo'),
('fusione a stampo su argento'),
('fusione a stampo su bronzo'),
('fusione a stampo su ferro'),
('fusione a stampo su lega metallica'),
('fusione a stampo su metallo'),
('fusione a stampo su oro'),
('fusione a stampo su piombo'),
('fusione a stampo su rame'),
('fusione su acciaio'),
('fusione su argento'),
('fusione su bronzo'),
('fusione su ferro'),
('fusione su metallo'),
('fusione su oro'),
('fusione su piombo'),
('fusione su rame'),
('fusione su stagno'),
('fusione su vetro'),
('galena'),
('gesso alabastrino a tornio'),
('gesso alabastrino'),
('gesso'),
('ghiaia'),
('giada a cabochon'),
('giada a incisione'),
('giada a intaglio'),
('giada a intarsio'),
('giada'),
('giaietto a cabochon'),
('giaietto a incisione'),
('giaietto a intaglio'),
('giaietto a intarsio'),
('giaietto'),
('gneiss'),
('godronatura su argento'),
('godronatura su metallo'),
('godronatura su oro'),
('godronatura su rame'),
('grafite'),
('granato a cabochon'),
('granato a incisione'),
('granato a intaglio'),
('granato a intarsio'),
('granato'),
('granito a incisione'),
('granito a trapano'),
('granito'),
('granulazione su oro'),
('imbutitura su argento'),
('imbutitura su ferro'),
('imbutitura su metallo'),
('impasto a barbottina'),
('impasto a cilindretti'),
('impasto a colombino'),
('impasto a ditate'),
('impasto a graffito'),
('impasto a impressione'),
('impasto a incisione'),
('impasto a incrostazione'),
('impasto a intaglio'),
('impasto a mano'),
('impasto a matrice'),
('impasto a pettine'),
('impasto a rilievo applicato'),
('impasto a rotella'),
('impasto a stampo'),
('impasto a stralucido'),
('impasto'),
('incastonatura su acquamarina'),
('incastonatura su agata zonata'),
('incastonatura su agata'),
('incastonatura su amazzonite'),
('incastonatura su ambra'),
('incastonatura su ametista'),
('incastonatura su calcedonio'),
('incastonatura su diamante'),
('incastonatura su diaspro'),
('incastonatura su eliotropio'),
('incastonatura su giada'),
('incastonatura su giaietto'),
('incastonatura su granato'),
('incastonatura su lapislazzuli'),
('incastonatura su malachite'),
('incastonatura su occhio di gatto'),
('incastonatura su occhio di pavone bianco'),
('incastonatura su occhio di tigre'),
('incastonatura su olivina'),
('incastonatura su onice'),
('incastonatura su opale'),
('incastonatura su pasta vitrea'),
('incastonatura su perla'),
('incastonatura su plasma'),
('incastonatura su prasio'),
('incastonatura su quarzo rosa'),
('incastonatura su rubino'),
('incastonatura su sardonice'),
('incastonatura su smeraldo'),
('incastonatura su spinello'),
('incastonatura su topazio'),
('incastonatura su tormalina'),
('incastonatura su turchese'),
('incastonatura su zaffiro'),
('incastonatura su zircone'),
('incisione a crudo su argilla'),
('ingobbiatura su argilla'),
('ingobbiatura su impasto'),
('ingobbiatura su laterizio'),
('intaglio a freddo su osso'),
('intonaco'),
('invetriatura su argilla'),
('invetriatura su impasto'),
('laminatura su argento'),
('laminatura su bronzo'),
('laminatura su ferro'),
('laminatura su lega metallica'),
('laminatura su metallo'),
('laminatura su oro'),
('laminatura su piombo'),
('laminatura su rame'),
('lana'),
('lapislazzuli a cloisonne'),
('lapislazzuli a incisione'),
('lapislazzuli a intaglio'),
('lapislazzuli'),
('laterizio a cassaforma'),
('laterizio a crudo'),
('laterizio a impressione'),
('laterizio a mano'),
('laterizio a punzone'),
('laterizio'),
('lava basaltica'),
('lavagna a incisione'),
('lavagna a intarsio'),
('lavagna'),
('lega metallica a bulino'),
('lega metallica a filigrana'),
('lega metallica a intaglio'),
('lega metallica a intarsio'),
('lega metallica a sbalzo'),
('lega metallica a traforo'),
('lega metallica'),
('legno a incisione'),
('legno a intaglio'),
('legno'),
('levigatura su alabastro a pecorella'),
('levigatura su alabastro a tartaruga'),
('levigatura su alabastro bianco'),
('levigatura su alabastro del Gebel Oust'),
('levigatura su alabastro di Palombara'),
('levigatura su alabastro dorato'),
('levigatura su alabastro egiziano'),
('levigatura su alabastro fiorito'),
('levigatura su alabastro marino'),
('levigatura su alabastro'),
('levigatura su ambra'),
('levigatura su ametista'),
('levigatura su ardesia'),
('levigatura su arenaria'),
('levigatura su argilla'),
('levigatura su basalto'),
('levigatura su basanite'),
('levigatura su breccia'),
('levigatura su bronzo'),
('levigatura su calcare'),
('levigatura su calcarenite'),
('levigatura su clorite'),
('levigatura su corallo'),
('levigatura su corniola'),
('levigatura su corno'),
('levigatura su faience'),
('levigatura su granito'),
('levigatura su legno'),
('levigatura su marmo africano'),
('levigatura su marmo asiatico'),
('levigatura su marmo bardiglio di Carrara'),
('levigatura su marmo bianco greco'),
('levigatura su marmo bianco italico'),
('levigatura su marmo bianco venato'),
('levigatura su marmo bianco'),
('levigatura su marmo bigio antico'),
('levigatura su marmo bigio morato'),
('levigatura su marmo bigio'),
('levigatura su marmo broccatello di Verona'),
('levigatura su marmo broccatello'),
('levigatura su marmo broccatellone'),
('levigatura su marmo cipollino mandolato'),
('levigatura su marmo cipollino marino'),
('levigatura su marmo cipollino rosso'),
('levigatura su marmo cipollino'),
('levigatura su marmo cottanello antico'),
('levigatura su marmo dell''Imetto'),
('levigatura su marmo di Carrara'),
('levigatura su marmo di Proconneso'),
('levigatura su marmo di Taso'),
('levigatura su marmo fior di pesco'),
('levigatura su marmo giallo antico brecciato'),
('levigatura su marmo giallo antico'),
('levigatura su marmo giallo tigrato'),
('levigatura su marmo greco insulare'),
('levigatura su marmo greco scritto'),
('levigatura su marmo grigio brecciato'),
('levigatura su marmo grigio venato'),
('levigatura su marmo grigio'),
('levigatura su marmo italico'),
('levigatura su marmo lumachella bigia'),
('levigatura su marmo lumachella d''Egitto'),
('levigatura su marmo lumachella pavonazza'),
('levigatura su marmo lumachella rosea'),
('levigatura su marmo lumachella'),
('levigatura su marmo lumachellone antico'),
('levigatura su marmo lunense'),
('levigatura su marmo nero africano'),
('levigatura su marmo nero antico'),
('levigatura su marmo occhio di pavone bianco'),
('levigatura su marmo occhio di pavone bigio'),
('levigatura su marmo occhio di pavone pavonazzo'),
('levigatura su marmo occhio di pavone roseo'),
('levigatura su marmo occhio di pavone rosso'),
('levigatura su marmo palombino'),
('levigatura su marmo pario'),
('levigatura su marmo pavonazzetto'),
('levigatura su marmo pentelico'),
('levigatura su marmo policromo'),
('levigatura su marmo portasanta'),
('levigatura su marmo proconnesio'),
('levigatura su marmo rosa'),
('levigatura su marmo rosso antico'),
('levigatura su marmo rosso brecciato'),
('levigatura su marmo semesanto'),
('levigatura su marmo serpentina moschinata'),
('levigatura su marmo verde antico'),
('levigatura su marmo verde rana fibroso'),
('levigatura su marmo verde rana ondato'),
('levigatura su marmo'),
('levigatura su ofiolite'),
('levigatura su osso'),
('levigatura su pietra ollare'),
('levigatura su pietra'),
('levigatura su porfido bigio'),
('levigatura su porfido nero grafico'),
('levigatura su porfido nero'),
('levigatura su porfido rosso'),
('levigatura su porfido verde di Laconia'),
('levigatura su porfido verde egiziano'),
('levigatura su porfido'),
('levigatura su puddinga'),
('levigatura su scisto'),
('levigatura su selce'),
('levigatura su trachite dei Colli Euganei'),
('levigatura su trachite'),
('levigatura su travertino'),
('levigatura su tufo giallo litoide'),
('levigatura su tufo grigio'),
('levigatura su tufo Nocerino'),
('levigatura su tufo rosso a scorie nere'),
('levigatura su tufo rosso litoide'),
('levigatura su tufo Sabazio'),
('levigatura su tufo trachitico'),
('levigatura su tufo Vulsinio'),
('levigatura su tufo'),
('limatura su ferro'),
('lino'),
('lisciatura a stecca su argilla'),
('lisciatura a stecca su bucchero'),
('lisciatura a stecca su impasto'),
('lisciatura su ardesia'),
('lisciatura su arenaria'),
('lisciatura su argilla'),
('lisciatura su bucchero'),
('lisciatura su calcare'),
('lisciatura su corno'),
('lisciatura su impasto'),
('lisciatura su marmo africano'),
('lisciatura su marmo asiatico'),
('lisciatura su marmo bardiglio di Carrara'),
('lisciatura su marmo bianco greco'),
('lisciatura su marmo bianco italico'),
('lisciatura su marmo bianco venato'),
('lisciatura su marmo bianco'),
('lisciatura su marmo bigio antico'),
('lisciatura su marmo bigio morato'),
('lisciatura su marmo bigio'),
('lisciatura su marmo broccatello di Verona'),
('lisciatura su marmo broccatello'),
('lisciatura su marmo broccatellone'),
('lisciatura su marmo cipollino mandolato'),
('lisciatura su marmo cipollino marino'),
('lisciatura su marmo cipollino rosso'),
('lisciatura su marmo cipollino'),
('lisciatura su marmo cottanello antico'),
('lisciatura su marmo dell''Imetto'),
('lisciatura su marmo di Carrara'),
('lisciatura su marmo di Proconneso'),
('lisciatura su marmo di Taso'),
('lisciatura su marmo fior di pesco'),
('lisciatura su marmo giallo antico brecciato'),
('lisciatura su marmo giallo antico'),
('lisciatura su marmo giallo tigrato'),
('lisciatura su marmo greco insulare'),
('lisciatura su marmo greco scritto'),
('lisciatura su marmo grigio brecciato'),
('lisciatura su marmo grigio venato'),
('lisciatura su marmo grigio'),
('lisciatura su marmo italico'),
('lisciatura su marmo lumachella bigia'),
('lisciatura su marmo lumachella d''Egitto'),
('lisciatura su marmo lumachella pavonazza'),
('lisciatura su marmo lumachella rosea'),
('lisciatura su marmo lumachella'),
('lisciatura su marmo lumachellone antico'),
('lisciatura su marmo lunense'),
('lisciatura su marmo nero africano'),
('lisciatura su marmo nero antico'),
('lisciatura su marmo occhio di pavone bianco'),
('lisciatura su marmo occhio di pavone bigio'),
('lisciatura su marmo occhio di pavone pavonazzo'),
('lisciatura su marmo occhio di pavone roseo'),
('lisciatura su marmo occhio di pavone rosso'),
('lisciatura su marmo palombino'),
('lisciatura su marmo pario'),
('lisciatura su marmo pavonazzetto'),
('lisciatura su marmo pentelico'),
('lisciatura su marmo policromo'),
('lisciatura su marmo portasanta'),
('lisciatura su marmo proconnesio'),
('lisciatura su marmo rosa'),
('lisciatura su marmo rosso antico'),
('lisciatura su marmo rosso brecciato'),
('lisciatura su marmo semesanto'),
('lisciatura su marmo serpentina moschinata'),
('lisciatura su marmo verde antico'),
('lisciatura su marmo verde rana fibroso'),
('lisciatura su marmo verde rana ondato'),
('lisciatura su marmo'),
('lisciatura su osso'),
('lisciatura su pietra'),
('lisciatura su travertino'),
('lisciatura su tufo giallo litoide'),
('lisciatura su tufo grigio'),
('lisciatura su tufo Nocerino'),
('lisciatura su tufo rosso a scorie nere'),
('lisciatura su tufo rosso litoide'),
('lisciatura su tufo Sabazio'),
('lisciatura su tufo trachitico'),
('lisciatura su tufo Vulsinio'),
('lisciatura su tufo'),
('lucidatura a stecca su impasto'),
('lucidatura su argento'),
('lucidatura su argilla'),
('lucidatura su bronzo'),
('lucidatura su bucchero'),
('lucidatura su calcare'),
('lucidatura su corallo'),
('lucidatura su corniola'),
('lucidatura su ematite'),
('lucidatura su granito'),
('lucidatura su impasto'),
('lucidatura su metallo'),
('lucidatura su pietra ollare'),
('madreperla'),
('malachite a cabochon'),
('malachite a incisione'),
('malachite a intaglio'),
('malachite'),
('marmo a gradina'),
('marmo a graffito'),
('marmo a incisione'),
('marmo a intaglio'),
('marmo a intarsio'),
('marmo a mosaico'),
('marmo a trapano corrente'),
('marmo a trapano'),
('marmo africano a gradina'),
('marmo africano a graffito'),
('marmo africano a incisione'),
('marmo africano a intaglio'),
('marmo africano a intarsio'),
('marmo africano a mosaico'),
('marmo africano a trapano corrente'),
('marmo africano a trapano'),
('marmo africano'),
('marmo asiatico a gradina'),
('marmo asiatico a graffito'),
('marmo asiatico a incisione'),
('marmo asiatico a intaglio'),
('marmo asiatico a intarsio'),
('marmo asiatico a mosaico'),
('marmo asiatico a trapano corrente'),
('marmo asiatico a trapano'),
('marmo asiatico'),
('marmo bardiglio di Carrara a gradina'),
('marmo bardiglio di Carrara a graffito'),
('marmo bardiglio di Carrara a incisione'),
('marmo bardiglio di Carrara a intaglio'),
('marmo bardiglio di Carrara a intarsio'),
('marmo bardiglio di Carrara a mosaico'),
('marmo bardiglio di Carrara a trapano corrente'),
('marmo bardiglio di Carrara a trapano'),
('marmo bardiglio di Carrara'),
('marmo bianco a gradina'),
('marmo bianco a graffito'),
('marmo bianco a incisione'),
('marmo bianco a intaglio'),
('marmo bianco a intarsio'),
('marmo bianco a mosaico'),
('marmo bianco a trapano corrente'),
('marmo bianco a trapano'),
('marmo bianco greco a gradina'),
('marmo bianco greco a graffito'),
('marmo bianco greco a incisione'),
('marmo bianco greco a intaglio'),
('marmo bianco greco a intarsio'),
('marmo bianco greco a mosaico'),
('marmo bianco greco a trapano corrente'),
('marmo bianco greco a trapano'),
('marmo bianco greco'),
('marmo bianco italico a gradina'),
('marmo bianco italico a graffito'),
('marmo bianco italico a incisione'),
('marmo bianco italico a intaglio'),
('marmo bianco italico a intarsio'),
('marmo bianco italico a mosaico'),
('marmo bianco italico a trapano corrente'),
('marmo bianco italico a trapano'),
('marmo bianco italico'),
('marmo bianco venato a gradina'),
('marmo bianco venato a graffito'),
('marmo bianco venato a incisione'),
('marmo bianco venato a intaglio'),
('marmo bianco venato a intarsio'),
('marmo bianco venato a mosaico'),
('marmo bianco venato a trapano corrente'),
('marmo bianco venato a trapano'),
('marmo bianco venato'),
('marmo bianco'),
('marmo bigio a gradina'),
('marmo bigio a graffito'),
('marmo bigio a incisione'),
('marmo bigio a intaglio'),
('marmo bigio a intarsio'),
('marmo bigio a mosaico'),
('marmo bigio a trapano corrente'),
('marmo bigio a trapano'),
('marmo bigio antico a gradina'),
('marmo bigio antico a graffito'),
('marmo bigio antico a incisione'),
('marmo bigio antico a intaglio'),
('marmo bigio antico a intarsio'),
('marmo bigio antico a mosaico'),
('marmo bigio antico a trapano corrente'),
('marmo bigio antico a trapano'),
('marmo bigio antico'),
('marmo bigio morato a gradina'),
('marmo bigio morato a graffito'),
('marmo bigio morato a incisione'),
('marmo bigio morato a intaglio'),
('marmo bigio morato a intarsio'),
('marmo bigio morato a mosaico'),
('marmo bigio morato a trapano corrente'),
('marmo bigio morato a trapano'),
('marmo bigio morato'),
('marmo bigio'),
('marmo broccatello a gradina'),
('marmo broccatello a graffito'),
('marmo broccatello a incisione'),
('marmo broccatello a intaglio'),
('marmo broccatello a intarsio'),
('marmo broccatello a mosaico'),
('marmo broccatello a trapano corrente'),
('marmo broccatello a trapano'),
('marmo broccatello di Verona a gradina'),
('marmo broccatello di Verona a graffito'),
('marmo broccatello di Verona a incisione'),
('marmo broccatello di Verona a intaglio'),
('marmo broccatello di Verona a intarsio'),
('marmo broccatello di Verona a mosaico'),
('marmo broccatello di Verona a trapano corrente'),
('marmo broccatello di Verona a trapano'),
('marmo broccatello di Verona'),
('marmo broccatello'),
('marmo broccatellone a gradina'),
('marmo broccatellone a graffito'),
('marmo broccatellone a incisione'),
('marmo broccatellone a intaglio'),
('marmo broccatellone a intarsio'),
('marmo broccatellone a mosaico'),
('marmo broccatellone a trapano corrente'),
('marmo broccatellone a trapano'),
('marmo broccatellone'),
('marmo cipollino a gradina'),
('marmo cipollino a graffito'),
('marmo cipollino a incisione'),
('marmo cipollino a intaglio'),
('marmo cipollino a intarsio'),
('marmo cipollino a mosaico'),
('marmo cipollino a trapano corrente'),
('marmo cipollino a trapano'),
('marmo cipollino mandolato a gradina'),
('marmo cipollino mandolato a graffito'),
('marmo cipollino mandolato a incisione'),
('marmo cipollino mandolato a intaglio'),
('marmo cipollino mandolato a intarsio'),
('marmo cipollino mandolato a mosaico'),
('marmo cipollino mandolato a trapano corrente'),
('marmo cipollino mandolato a trapano'),
('marmo cipollino mandolato'),
('marmo cipollino marino a gradina'),
('marmo cipollino marino a graffito'),
('marmo cipollino marino a incisione'),
('marmo cipollino marino a intaglio'),
('marmo cipollino marino a intarsio'),
('marmo cipollino marino a mosaico'),
('marmo cipollino marino a trapano corrente'),
('marmo cipollino marino a trapano'),
('marmo cipollino marino'),
('marmo cipollino rosso a gradina'),
('marmo cipollino rosso a graffito'),
('marmo cipollino rosso a incisione'),
('marmo cipollino rosso a intaglio'),
('marmo cipollino rosso a intarsio'),
('marmo cipollino rosso a mosaico'),
('marmo cipollino rosso a trapano corrente'),
('marmo cipollino rosso a trapano'),
('marmo cipollino rosso'),
('marmo cipollino'),
('marmo cottanello antico a gradina'),
('marmo cottanello antico a graffito'),
('marmo cottanello antico a incisione'),
('marmo cottanello antico a intaglio'),
('marmo cottanello antico a intarsio'),
('marmo cottanello antico a mosaico'),
('marmo cottanello antico a trapano corrente'),
('marmo cottanello antico a trapano'),
('marmo cottanello antico'),
('marmo dell''Imetto a gradina'),
('marmo dell''Imetto a graffito'),
('marmo dell''Imetto a incisione'),
('marmo dell''Imetto a intaglio'),
('marmo dell''Imetto a intarsio'),
('marmo dell''Imetto a mosaico'),
('marmo dell''Imetto a trapano corrente'),
('marmo dell''Imetto a trapano'),
('marmo dell''Imetto'),
('marmo di Carrara a gradina'),
('marmo di Carrara a graffito'),
('marmo di Carrara a incisione'),
('marmo di Carrara a intaglio'),
('marmo di Carrara a intarsio'),
('marmo di Carrara a mosaico'),
('marmo di Carrara a trapano corrente'),
('marmo di Carrara a trapano'),
('marmo di Carrara'),
('marmo di Proconneso a gradina'),
('marmo di Proconneso a graffito'),
('marmo di Proconneso a incisione'),
('marmo di Proconneso a intaglio'),
('marmo di Proconneso a intarsio'),
('marmo di Proconneso a mosaico'),
('marmo di Proconneso a trapano corrente'),
('marmo di Proconneso a trapano'),
('marmo di Proconneso'),
('marmo di Taso a gradina'),
('marmo di Taso a graffito'),
('marmo di Taso a incisione'),
('marmo di Taso a intaglio'),
('marmo di Taso a intarsio'),
('marmo di Taso a mosaico'),
('marmo di Taso a trapano corrente'),
('marmo di Taso a trapano'),
('marmo di Taso'),
('marmo fior di pesco a gradina'),
('marmo fior di pesco a graffito'),
('marmo fior di pesco a incisione'),
('marmo fior di pesco a intaglio'),
('marmo fior di pesco a intarsio'),
('marmo fior di pesco a mosaico'),
('marmo fior di pesco a trapano corrente'),
('marmo fior di pesco a trapano'),
('marmo fior di pesco'),
('marmo giallo antico a gradina'),
('marmo giallo antico a graffito'),
('marmo giallo antico a incisione'),
('marmo giallo antico a intaglio'),
('marmo giallo antico a intarsio'),
('marmo giallo antico a mosaico'),
('marmo giallo antico a trapano corrente'),
('marmo giallo antico a trapano'),
('marmo giallo antico brecciato a gradina'),
('marmo giallo antico brecciato a graffito'),
('marmo giallo antico brecciato a incisione'),
('marmo giallo antico brecciato a intaglio'),
('marmo giallo antico brecciato a intarsio'),
('marmo giallo antico brecciato a mosaico'),
('marmo giallo antico brecciato a trapano corrente'),
('marmo giallo antico brecciato a trapano'),
('marmo giallo antico brecciato'),
('marmo giallo antico'),
('marmo giallo tigrato a gradina'),
('marmo giallo tigrato a graffito'),
('marmo giallo tigrato a incisione'),
('marmo giallo tigrato a intaglio'),
('marmo giallo tigrato a intarsio'),
('marmo giallo tigrato a mosaico'),
('marmo giallo tigrato a trapano corrente'),
('marmo giallo tigrato a trapano'),
('marmo giallo tigrato'),
('marmo greco insulare a gradina'),
('marmo greco insulare a graffito'),
('marmo greco insulare a incisione'),
('marmo greco insulare a intaglio'),
('marmo greco insulare a intarsio'),
('marmo greco insulare a mosaico'),
('marmo greco insulare a trapano corrente'),
('marmo greco insulare a trapano'),
('marmo greco insulare'),
('marmo greco scritto a gradina'),
('marmo greco scritto a graffito'),
('marmo greco scritto a incisione'),
('marmo greco scritto a intaglio'),
('marmo greco scritto a intarsio'),
('marmo greco scritto a mosaico'),
('marmo greco scritto a trapano corrente'),
('marmo greco scritto a trapano'),
('marmo greco scritto'),
('marmo grigio a gradina'),
('marmo grigio a graffito'),
('marmo grigio a incisione'),
('marmo grigio a intaglio'),
('marmo grigio a intarsio'),
('marmo grigio a mosaico'),
('marmo grigio a trapano corrente'),
('marmo grigio a trapano'),
('marmo grigio brecciato a gradina'),
('marmo grigio brecciato a graffito'),
('marmo grigio brecciato a incisione'),
('marmo grigio brecciato a intaglio'),
('marmo grigio brecciato a intarsio'),
('marmo grigio brecciato a mosaico'),
('marmo grigio brecciato a trapano corrente'),
('marmo grigio brecciato a trapano'),
('marmo grigio brecciato'),
('marmo grigio venato a gradina'),
('marmo grigio venato a graffito'),
('marmo grigio venato a incisione'),
('marmo grigio venato a intaglio'),
('marmo grigio venato a intarsio'),
('marmo grigio venato a mosaico'),
('marmo grigio venato a trapano corrente'),
('marmo grigio venato a trapano'),
('marmo grigio venato'),
('marmo grigio'),
('marmo italico a gradina'),
('marmo italico a graffito'),
('marmo italico a incisione'),
('marmo italico a intaglio'),
('marmo italico a intarsio'),
('marmo italico a mosaico'),
('marmo italico a trapano corrente'),
('marmo italico a trapano'),
('marmo italico'),
('marmo lumachella a gradina'),
('marmo lumachella a graffito'),
('marmo lumachella a incisione'),
('marmo lumachella a intaglio'),
('marmo lumachella a intarsio'),
('marmo lumachella a mosaico'),
('marmo lumachella a trapano corrente'),
('marmo lumachella a trapano'),
('marmo lumachella bigia a gradina'),
('marmo lumachella bigia a graffito'),
('marmo lumachella bigia a incisione'),
('marmo lumachella bigia a intaglio'),
('marmo lumachella bigia a intarsio'),
('marmo lumachella bigia a mosaico'),
('marmo lumachella bigia a trapano corrente'),
('marmo lumachella bigia a trapano'),
('marmo lumachella bigia'),
('marmo lumachella d''Egitto a gradina'),
('marmo lumachella d''Egitto a graffito'),
('marmo lumachella d''Egitto a incisione'),
('marmo lumachella d''Egitto a intaglio'),
('marmo lumachella d''Egitto a intarsio'),
('marmo lumachella d''Egitto a mosaico'),
('marmo lumachella d''Egitto a trapano corrente'),
('marmo lumachella d''Egitto a trapano'),
('marmo lumachella d''Egitto'),
('marmo lumachella pavonazza a gradina'),
('marmo lumachella pavonazza a graffito'),
('marmo lumachella pavonazza a incisione'),
('marmo lumachella pavonazza a intaglio'),
('marmo lumachella pavonazza a intarsio'),
('marmo lumachella pavonazza a mosaico'),
('marmo lumachella pavonazza a trapano corrente'),
('marmo lumachella pavonazza a trapano'),
('marmo lumachella pavonazza'),
('marmo lumachella rosea a gradina'),
('marmo lumachella rosea a graffito'),
('marmo lumachella rosea a incisione'),
('marmo lumachella rosea a intaglio'),
('marmo lumachella rosea a intarsio'),
('marmo lumachella rosea a mosaico'),
('marmo lumachella rosea a trapano corrente'),
('marmo lumachella rosea a trapano'),
('marmo lumachella rosea'),
('marmo lumachella'),
('marmo lumachellone antico a gradina'),
('marmo lumachellone antico a graffito'),
('marmo lumachellone antico a incisione'),
('marmo lumachellone antico a intaglio'),
('marmo lumachellone antico a intarsio'),
('marmo lumachellone antico a mosaico'),
('marmo lumachellone antico a trapano corrente'),
('marmo lumachellone antico a trapano'),
('marmo lumachellone antico'),
('marmo lunense a gradina'),
('marmo lunense a graffito'),
('marmo lunense a incisione'),
('marmo lunense a intaglio'),
('marmo lunense a intarsio'),
('marmo lunense a mosaico'),
('marmo lunense a trapano corrente'),
('marmo lunense a trapano'),
('marmo lunense'),
('marmo nero africano a gradina'),
('marmo nero africano a graffito'),
('marmo nero africano a incisione'),
('marmo nero africano a intaglio'),
('marmo nero africano a intarsio'),
('marmo nero africano a mosaico'),
('marmo nero africano a trapano corrente'),
('marmo nero africano a trapano'),
('marmo nero africano'),
('marmo nero antico a gradina'),
('marmo nero antico a graffito'),
('marmo nero antico a incisione'),
('marmo nero antico a intaglio'),
('marmo nero antico a intarsio'),
('marmo nero antico a mosaico'),
('marmo nero antico a trapano corrente'),
('marmo nero antico a trapano'),
('marmo nero antico'),
('marmo occhio di pavone bianco a gradina'),
('marmo occhio di pavone bianco a graffito'),
('marmo occhio di pavone bianco a incisione'),
('marmo occhio di pavone bianco a intaglio'),
('marmo occhio di pavone bianco a intarsio'),
('marmo occhio di pavone bianco a mosaico'),
('marmo occhio di pavone bianco a trapano corrente'),
('marmo occhio di pavone bianco a trapano'),
('marmo occhio di pavone bianco'),
('marmo occhio di pavone bigio a gradina'),
('marmo occhio di pavone bigio a graffito'),
('marmo occhio di pavone bigio a incisione'),
('marmo occhio di pavone bigio a intaglio'),
('marmo occhio di pavone bigio a intarsio'),
('marmo occhio di pavone bigio a mosaico'),
('marmo occhio di pavone bigio a trapano corrente'),
('marmo occhio di pavone bigio a trapano'),
('marmo occhio di pavone bigio'),
('marmo occhio di pavone pavonazzo a gradina'),
('marmo occhio di pavone pavonazzo a graffito'),
('marmo occhio di pavone pavonazzo a incisione'),
('marmo occhio di pavone pavonazzo a intaglio'),
('marmo occhio di pavone pavonazzo a intarsio'),
('marmo occhio di pavone pavonazzo a mosaico'),
('marmo occhio di pavone pavonazzo a trapano corrente'),
('marmo occhio di pavone pavonazzo a trapano'),
('marmo occhio di pavone pavonazzo'),
('marmo occhio di pavone roseo a gradina'),
('marmo occhio di pavone roseo a graffito'),
('marmo occhio di pavone roseo a incisione'),
('marmo occhio di pavone roseo a intaglio'),
('marmo occhio di pavone roseo a intarsio'),
('marmo occhio di pavone roseo a mosaico'),
('marmo occhio di pavone roseo a trapano corrente'),
('marmo occhio di pavone roseo a trapano'),
('marmo occhio di pavone roseo'),
('marmo occhio di pavone rosso a gradina'),
('marmo occhio di pavone rosso a graffito'),
('marmo occhio di pavone rosso a incisione'),
('marmo occhio di pavone rosso a intaglio'),
('marmo occhio di pavone rosso a intarsio'),
('marmo occhio di pavone rosso a mosaico'),
('marmo occhio di pavone rosso a trapano corrente'),
('marmo occhio di pavone rosso a trapano'),
('marmo occhio di pavone rosso'),
('marmo palombino a gradina'),
('marmo palombino a graffito'),
('marmo palombino a incisione'),
('marmo palombino a intaglio'),
('marmo palombino a intarsio'),
('marmo palombino a mosaico'),
('marmo palombino a trapano corrente'),
('marmo palombino a trapano'),
('marmo palombino'),
('marmo pario a gradina'),
('marmo pario a graffito'),
('marmo pario a incisione'),
('marmo pario a intaglio'),
('marmo pario a intarsio'),
('marmo pario a mosaico'),
('marmo pario a trapano corrente'),
('marmo pario a trapano'),
('marmo pario'),
('marmo pavonazzetto a gradina'),
('marmo pavonazzetto a graffito'),
('marmo pavonazzetto a incisione'),
('marmo pavonazzetto a intaglio'),
('marmo pavonazzetto a intarsio'),
('marmo pavonazzetto a mosaico'),
('marmo pavonazzetto a trapano corrente'),
('marmo pavonazzetto a trapano'),
('marmo pavonazzetto'),
('marmo pentelico a gradina'),
('marmo pentelico a graffito'),
('marmo pentelico a incisione'),
('marmo pentelico a intaglio'),
('marmo pentelico a intarsio'),
('marmo pentelico a mosaico'),
('marmo pentelico a trapano corrente'),
('marmo pentelico a trapano'),
('marmo pentelico'),
('marmo policromo a gradina'),
('marmo policromo a graffito'),
('marmo policromo a incisione'),
('marmo policromo a intaglio'),
('marmo policromo a intarsio'),
('marmo policromo a mosaico'),
('marmo policromo a trapano corrente'),
('marmo policromo a trapano'),
('marmo policromo'),
('marmo portasanta a gradina'),
('marmo portasanta a graffito'),
('marmo portasanta a incisione'),
('marmo portasanta a intaglio'),
('marmo portasanta a intarsio'),
('marmo portasanta a mosaico'),
('marmo portasanta a trapano corrente'),
('marmo portasanta a trapano'),
('marmo portasanta'),
('marmo proconnesio a gradina'),
('marmo proconnesio a graffito'),
('marmo proconnesio a incisione'),
('marmo proconnesio a intaglio'),
('marmo proconnesio a intarsio'),
('marmo proconnesio a mosaico'),
('marmo proconnesio a trapano corrente'),
('marmo proconnesio a trapano'),
('marmo proconnesio'),
('marmo rosa a gradina'),
('marmo rosa a graffito'),
('marmo rosa a incisione'),
('marmo rosa a intaglio'),
('marmo rosa a intarsio'),
('marmo rosa a mosaico'),
('marmo rosa a trapano corrente'),
('marmo rosa a trapano'),
('marmo rosa'),
('marmo rosso antico a gradina'),
('marmo rosso antico a graffito'),
('marmo rosso antico a incisione'),
('marmo rosso antico a intaglio'),
('marmo rosso antico a intarsio'),
('marmo rosso antico a mosaico'),
('marmo rosso antico a trapano corrente'),
('marmo rosso antico a trapano'),
('marmo rosso antico'),
('marmo rosso brecciato a gradina'),
('marmo rosso brecciato a graffito'),
('marmo rosso brecciato a incisione'),
('marmo rosso brecciato a intaglio'),
('marmo rosso brecciato a intarsio'),
('marmo rosso brecciato a mosaico'),
('marmo rosso brecciato a trapano corrente'),
('marmo rosso brecciato a trapano'),
('marmo rosso brecciato'),
('marmo semesanto a gradina'),
('marmo semesanto a graffito'),
('marmo semesanto a incisione'),
('marmo semesanto a intaglio'),
('marmo semesanto a intarsio'),
('marmo semesanto a mosaico'),
('marmo semesanto a trapano corrente'),
('marmo semesanto a trapano'),
('marmo semesanto'),
('marmo serpentina moschinata a gradina'),
('marmo serpentina moschinata a graffito'),
('marmo serpentina moschinata a incisione'),
('marmo serpentina moschinata a intaglio'),
('marmo serpentina moschinata a intarsio'),
('marmo serpentina moschinata a mosaico'),
('marmo serpentina moschinata a trapano corrente'),
('marmo serpentina moschinata a trapano'),
('marmo serpentina moschinata'),
('marmo verde antico a gradina'),
('marmo verde antico a graffito'),
('marmo verde antico a incisione'),
('marmo verde antico a intaglio'),
('marmo verde antico a intarsio'),
('marmo verde antico a mosaico'),
('marmo verde antico a trapano corrente'),
('marmo verde antico a trapano'),
('marmo verde antico'),
('marmo verde rana fibroso a gradina'),
('marmo verde rana fibroso a graffito'),
('marmo verde rana fibroso a incisione'),
('marmo verde rana fibroso a intaglio'),
('marmo verde rana fibroso a intarsio'),
('marmo verde rana fibroso a mosaico'),
('marmo verde rana fibroso a trapano corrente'),
('marmo verde rana fibroso a trapano'),
('marmo verde rana fibroso'),
('marmo verde rana ondato a gradina'),
('marmo verde rana ondato a graffito'),
('marmo verde rana ondato a incisione'),
('marmo verde rana ondato a intaglio'),
('marmo verde rana ondato a intarsio'),
('marmo verde rana ondato a mosaico'),
('marmo verde rana ondato a trapano corrente'),
('marmo verde rana ondato a trapano'),
('marmo verde rana ondato'),
('marmo'),
('marna'),
('martellatura su argento'),
('martellatura su bronzo'),
('martellatura su ferro'),
('martellatura su lega metallica'),
('martellatura su metallo'),
('martellatura su oro'),
('martellatura su piombo'),
('martellatura su rame'),
('martellinatura su calcare'),
('martellinatura su marmo africano'),
('martellinatura su marmo asiatico'),
('martellinatura su marmo bardiglio di Carrara'),
('martellinatura su marmo bianco greco'),
('martellinatura su marmo bianco italico'),
('martellinatura su marmo bianco venato'),
('martellinatura su marmo bianco'),
('martellinatura su marmo bigio antico'),
('martellinatura su marmo bigio morato'),
('martellinatura su marmo bigio'),
('martellinatura su marmo broccatello di Verona'),
('martellinatura su marmo broccatello'),
('martellinatura su marmo broccatellone'),
('martellinatura su marmo cipollino mandolato'),
('martellinatura su marmo cipollino marino'),
('martellinatura su marmo cipollino rosso'),
('martellinatura su marmo cipollino'),
('martellinatura su marmo cottanello antico'),
('martellinatura su marmo dell''Imetto'),
('martellinatura su marmo di Carrara'),
('martellinatura su marmo di Proconneso'),
('martellinatura su marmo di Taso'),
('martellinatura su marmo fior di pesco'),
('martellinatura su marmo giallo antico brecciato'),
('martellinatura su marmo giallo antico'),
('martellinatura su marmo giallo tigrato'),
('martellinatura su marmo greco insulare'),
('martellinatura su marmo greco scritto'),
('martellinatura su marmo grigio brecciato'),
('martellinatura su marmo grigio venato'),
('martellinatura su marmo grigio'),
('martellinatura su marmo italico'),
('martellinatura su marmo lumachella bigia'),
('martellinatura su marmo lumachella d''Egitto'),
('martellinatura su marmo lumachella pavonazza'),
('martellinatura su marmo lumachella rosea'),
('martellinatura su marmo lumachella'),
('martellinatura su marmo lumachellone antico'),
('martellinatura su marmo lunense'),
('martellinatura su marmo nero africano'),
('martellinatura su marmo nero antico'),
('martellinatura su marmo occhio di pavone bianco'),
('martellinatura su marmo occhio di pavone bigio'),
('martellinatura su marmo occhio di pavone pavonazzo'),
('martellinatura su marmo occhio di pavone roseo'),
('martellinatura su marmo occhio di pavone rosso'),
('martellinatura su marmo palombino'),
('martellinatura su marmo pario'),
('martellinatura su marmo pavonazzetto'),
('martellinatura su marmo pentelico'),
('martellinatura su marmo policromo'),
('martellinatura su marmo portasanta'),
('martellinatura su marmo proconnesio'),
('martellinatura su marmo rosa'),
('martellinatura su marmo rosso antico'),
('martellinatura su marmo rosso brecciato'),
('martellinatura su marmo semesanto'),
('martellinatura su marmo serpentina moschinata'),
('martellinatura su marmo verde antico'),
('martellinatura su marmo verde rana fibroso'),
('martellinatura su marmo verde rana ondato'),
('martellinatura su marmo'),
('martellinatura su pietra'),
('materiale litico'),
('metallo a basse-taille'),
('metallo a bulino'),
('metallo a immersione'),
('metallo a incisione'),
('metallo a intaglio'),
('metallo a intarsio'),
('metallo a niello'),
('metallo a plique-a-jour'),
('metallo a punzone'),
('metallo a repousse'),
('metallo a sbalzo'),
('metallo a stampo'),
('metallo'),
('mica'),
('modellazione su bastoncino su vetro'),
('modellazione su nucleo su vetro'),
('molatura su vetro'),
('nenfro a incisione'),
('nenfro a intaglio'),
('nenfro a trapano'),
('nenfro'),
('nichel'),
('nicolo a incisione'),
('nicolo a intaglio'),
('nicolo'),
('occhio di gatto a cabochon'),
('occhio di gatto a incisione'),
('occhio di gatto a intaglio'),
('occhio di gatto a intarsio'),
('occhio di gatto'),
('occhio di pavone bianco a cabochon'),
('occhio di pavone bianco a incisione'),
('occhio di pavone bianco a intaglio'),
('occhio di pavone bianco a intarsio'),
('occhio di pavone bianco'),
('occhio di pavone bigio'),
('occhio di pavone pavonazzo'),
('occhio di pavone roseo'),
('occhio di pavone rosso'),
('occhio di tigre a cabochon'),
('occhio di tigre a incisione'),
('occhio di tigre a intaglio'),
('occhio di tigre a intarsio'),
('occhio di tigre'),
('ofiolite'),
('olivina a cabochon'),
('olivina a incisione'),
('olivina a intaglio'),
('olivina a intarsio'),
('olivina'),
('onice a cabochon'),
('onice a incisione'),
('onice a intaglio'),
('onice a intarsio'),
('onice'),
('opale a cabochon'),
('opale a incisione'),
('opale a intaglio'),
('opale a intarsio'),
('opale'),
('opus sectile su marmo africano'),
('opus sectile su marmo asiatico'),
('opus sectile su marmo bardiglio di Carrara'),
('opus sectile su marmo bianco greco'),
('opus sectile su marmo bianco italico'),
('opus sectile su marmo bianco venato'),
('opus sectile su marmo bianco'),
('opus sectile su marmo bigio antico'),
('opus sectile su marmo bigio morato'),
('opus sectile su marmo bigio'),
('opus sectile su marmo broccatello di Verona'),
('opus sectile su marmo broccatello'),
('opus sectile su marmo broccatellone'),
('opus sectile su marmo cipollino mandolato'),
('opus sectile su marmo cipollino marino'),
('opus sectile su marmo cipollino rosso'),
('opus sectile su marmo cipollino'),
('opus sectile su marmo cottanello antico'),
('opus sectile su marmo dell''Imetto'),
('opus sectile su marmo di Carrara'),
('opus sectile su marmo di Proconneso'),
('opus sectile su marmo di Taso'),
('opus sectile su marmo fior di pesco'),
('opus sectile su marmo giallo antico brecciato'),
('opus sectile su marmo giallo antico'),
('opus sectile su marmo giallo tigrato'),
('opus sectile su marmo greco insulare'),
('opus sectile su marmo greco scritto'),
('opus sectile su marmo grigio brecciato'),
('opus sectile su marmo grigio venato'),
('opus sectile su marmo grigio'),
('opus sectile su marmo italico'),
('opus sectile su marmo lumachella bigia'),
('opus sectile su marmo lumachella d''Egitto'),
('opus sectile su marmo lumachella pavonazza'),
('opus sectile su marmo lumachella rosea'),
('opus sectile su marmo lumachella'),
('opus sectile su marmo lumachellone antico'),
('opus sectile su marmo lunense'),
('opus sectile su marmo nero africano'),
('opus sectile su marmo nero antico'),
('opus sectile su marmo occhio di pavone bianco'),
('opus sectile su marmo occhio di pavone bigio'),
('opus sectile su marmo occhio di pavone pavonazzo'),
('opus sectile su marmo occhio di pavone roseo'),
('opus sectile su marmo occhio di pavone rosso'),
('opus sectile su marmo palombino'),
('opus sectile su marmo pario'),
('opus sectile su marmo pavonazzetto'),
('opus sectile su marmo pentelico'),
('opus sectile su marmo policromo'),
('opus sectile su marmo portasanta'),
('opus sectile su marmo proconnesio'),
('opus sectile su marmo rosa'),
('opus sectile su marmo rosso antico'),
('opus sectile su marmo rosso brecciato'),
('opus sectile su marmo semesanto'),
('opus sectile su marmo serpentina moschinata'),
('opus sectile su marmo verde antico'),
('opus sectile su marmo verde rana fibroso'),
('opus sectile su marmo verde rana ondato'),
('opus sectile su marmo'),
('opus tessellatum su marmo africano'),
('opus tessellatum su marmo asiatico'),
('opus tessellatum su marmo bardiglio di Carrara'),
('opus tessellatum su marmo bianco greco'),
('opus tessellatum su marmo bianco italico'),
('opus tessellatum su marmo bianco venato'),
('opus tessellatum su marmo bianco'),
('opus tessellatum su marmo bigio antico'),
('opus tessellatum su marmo bigio morato'),
('opus tessellatum su marmo bigio'),
('opus tessellatum su marmo broccatello di Verona'),
('opus tessellatum su marmo broccatello'),
('opus tessellatum su marmo broccatellone'),
('opus tessellatum su marmo cipollino mandolato'),
('opus tessellatum su marmo cipollino marino'),
('opus tessellatum su marmo cipollino rosso'),
('opus tessellatum su marmo cipollino'),
('opus tessellatum su marmo cottanello antico'),
('opus tessellatum su marmo dell''Imetto'),
('opus tessellatum su marmo di Carrara'),
('opus tessellatum su marmo di Proconneso'),
('opus tessellatum su marmo di Taso'),
('opus tessellatum su marmo fior di pesco'),
('opus tessellatum su marmo giallo antico brecciato'),
('opus tessellatum su marmo giallo antico'),
('opus tessellatum su marmo giallo tigrato'),
('opus tessellatum su marmo greco insulare'),
('opus tessellatum su marmo greco scritto'),
('opus tessellatum su marmo grigio brecciato'),
('opus tessellatum su marmo grigio venato'),
('opus tessellatum su marmo grigio'),
('opus tessellatum su marmo italico'),
('opus tessellatum su marmo lumachella bigia'),
('opus tessellatum su marmo lumachella d''Egitto'),
('opus tessellatum su marmo lumachella pavonazza'),
('opus tessellatum su marmo lumachella rosea'),
('opus tessellatum su marmo lumachella'),
('opus tessellatum su marmo lumachellone antico'),
('opus tessellatum su marmo lunense'),
('opus tessellatum su marmo nero africano'),
('opus tessellatum su marmo nero antico'),
('opus tessellatum su marmo occhio di pavone bianco'),
('opus tessellatum su marmo occhio di pavone bigio'),
('opus tessellatum su marmo occhio di pavone pavonazzo'),
('opus tessellatum su marmo occhio di pavone roseo'),
('opus tessellatum su marmo occhio di pavone rosso'),
('opus tessellatum su marmo palombino'),
('opus tessellatum su marmo pario'),
('opus tessellatum su marmo pavonazzetto'),
('opus tessellatum su marmo pentelico'),
('opus tessellatum su marmo policromo'),
('opus tessellatum su marmo portasanta'),
('opus tessellatum su marmo proconnesio'),
('opus tessellatum su marmo rosa'),
('opus tessellatum su marmo rosso antico'),
('opus tessellatum su marmo rosso brecciato'),
('opus tessellatum su marmo semesanto'),
('opus tessellatum su marmo serpentina moschinata'),
('opus tessellatum su marmo verde antico'),
('opus tessellatum su marmo verde rana fibroso'),
('opus tessellatum su marmo verde rana ondato'),
('opus tessellatum su marmo'),
('oricalco'),
('oro a bulino'),
('oro a cloisonne'),
('oro a impressione'),
('oro a incisione'),
('oro a intaglio'),
('oro a niello'),
('oro a punzone'),
('oro a repousse'),
('oro a sbalzo'),
('oro a stampo'),
('oro'),
('ossidiana'),
('osso a bulino'),
('osso a incisione'),
('osso a intaglio'),
('osso a intarsio'),
('osso a tornio'),
('osso a traforo'),
('osso a trapano'),
('osso'),
('paglia'),
('pasta di talco'),
('pasta silicea'),
('pasta vitrea a cabochon'),
('pasta vitrea a incisione'),
('pasta vitrea a intaglio'),
('pasta vitrea'),
('patinatura su bronzo'),
('peperino a incisione'),
('peperino'),
('perla'),
('picchiettatura su marmo africano'),
('picchiettatura su marmo asiatico'),
('picchiettatura su marmo bardiglio di Carrara'),
('picchiettatura su marmo bianco greco'),
('picchiettatura su marmo bianco italico'),
('picchiettatura su marmo bianco venato'),
('picchiettatura su marmo bianco'),
('picchiettatura su marmo bigio antico'),
('picchiettatura su marmo bigio morato'),
('picchiettatura su marmo bigio'),
('picchiettatura su marmo broccatello di Verona'),
('picchiettatura su marmo broccatello'),
('picchiettatura su marmo broccatellone'),
('picchiettatura su marmo cipollino mandolato'),
('picchiettatura su marmo cipollino marino'),
('picchiettatura su marmo cipollino rosso'),
('picchiettatura su marmo cipollino'),
('picchiettatura su marmo cottanello antico'),
('picchiettatura su marmo dell''Imetto'),
('picchiettatura su marmo di Carrara'),
('picchiettatura su marmo di Proconneso'),
('picchiettatura su marmo di Taso'),
('picchiettatura su marmo fior di pesco'),
('picchiettatura su marmo giallo antico brecciato'),
('picchiettatura su marmo giallo antico'),
('picchiettatura su marmo giallo tigrato'),
('picchiettatura su marmo greco insulare'),
('picchiettatura su marmo greco scritto'),
('picchiettatura su marmo grigio brecciato'),
('picchiettatura su marmo grigio venato'),
('picchiettatura su marmo grigio'),
('picchiettatura su marmo italico'),
('picchiettatura su marmo lumachella bigia'),
('picchiettatura su marmo lumachella d''Egitto'),
('picchiettatura su marmo lumachella pavonazza'),
('picchiettatura su marmo lumachella rosea'),
('picchiettatura su marmo lumachella'),
('picchiettatura su marmo lumachellone antico'),
('picchiettatura su marmo lunense'),
('picchiettatura su marmo nero africano'),
('picchiettatura su marmo nero antico'),
('picchiettatura su marmo occhio di pavone bianco'),
('picchiettatura su marmo occhio di pavone bigio'),
('picchiettatura su marmo occhio di pavone pavonazzo'),
('picchiettatura su marmo occhio di pavone roseo'),
('picchiettatura su marmo occhio di pavone rosso'),
('picchiettatura su marmo palombino'),
('picchiettatura su marmo pario'),
('picchiettatura su marmo pavonazzetto'),
('picchiettatura su marmo pentelico'),
('picchiettatura su marmo policromo'),
('picchiettatura su marmo portasanta'),
('picchiettatura su marmo proconnesio'),
('picchiettatura su marmo rosa'),
('picchiettatura su marmo rosso antico'),
('picchiettatura su marmo rosso brecciato'),
('picchiettatura su marmo semesanto'),
('picchiettatura su marmo serpentina moschinata'),
('picchiettatura su marmo verde antico'),
('picchiettatura su marmo verde rana fibroso'),
('picchiettatura su marmo verde rana ondato'),
('picchiettatura su marmo'),
('pietra a gradina'),
('pietra a graffito'),
('pietra a mosaico'),
('pietra a percussione'),
('pietra a trapano'),
('pietra braschia'),
('pietra calcarea'),
('pietra d''Istria'),
('pietra dura a incisione'),
('pietra dura a intaglio'),
('pietra dura'),
('pietra lavica'),
('pietra nefritica'),
('pietra ollare a gradina'),
('pietra ollare a graffito'),
('pietra ollare a incisione'),
('pietra ollare a intaglio'),
('pietra ollare a tornio idraulico'),
('pietra ollare a tornio veloce'),
('pietra ollare'),
('pietra'),
('pinzatura su oro'),
('pinzatura su vetro'),
('piombo a bulino'),
('piombo a impressione'),
('piombo a incisione'),
('piombo a sbalzo'),
('piombo'),
('pittura a encausto su intonaco'),
('pittura a fresco su intonaco'),
('pittura a tempera su intonaco'),
('plasma a incisione'),
('plasma a intaglio'),
('plasma'),
('platino'),
('politura a ruota su vetro'),
('politura su alabastro a pecorella'),
('politura su alabastro a tartaruga'),
('politura su alabastro bianco'),
('politura su alabastro del Gebel Oust'),
('politura su alabastro di Palombara'),
('politura su alabastro dorato'),
('politura su alabastro egiziano'),
('politura su alabastro fiorito'),
('politura su alabastro marino'),
('politura su alabastro'),
('politura su ambra'),
('politura su ametista'),
('politura su breccia'),
('politura su osso'),
('porcellana'),
('porfido a trapano corrente'),
('porfido bigio a trapano corrente'),
('porfido bigio'),
('porfido nero a trapano corrente'),
('porfido nero grafico a trapano corrente'),
('porfido nero grafico'),
('porfido nero'),
('porfido rosso a trapano corrente'),
('porfido rosso'),
('porfido verde di Laconia a trapano corrente'),
('porfido verde di Laconia'),
('porfido verde egiziano a trapano corrente'),
('porfido verde egiziano'),
('porfido'),
('pozzolana'),
('prasio a incisione'),
('prasio a intaglio'),
('prasio'),
('puddellaggio su ferro'),
('puddinga'),
('quarzite'),
('quarzo a incisione'),
('quarzo a intaglio'),
('quarzo rosa a incisione'),
('quarzo rosa a intaglio'),
('quarzo rosa'),
('quarzo'),
('rame a bulino'),
('rame a champleve'),
('rame a impressione'),
('rame a incisione'),
('rame a intaglio'),
('rame a intarsio'),
('rame a niello'),
('rame a sbalzo'),
('rame a stampo'),
('rame'),
('raschiatura su ambra'),
('ribattitura su argento'),
('ribattitura su bronzo'),
('ribattitura su ferro'),
('ribattitura su metallo'),
('ribattitura su rame'),
('rifinitura a freddo su bronzo'),
('ritocco a mano su argilla'),
('ritocco a mano su laterizio'),
('ritocco a stecca su argilla'),
('ritocco a stecca su impasto'),
('ritocco a stecca su laterizio'),
('rubino a cabochon'),
('rubino a incisione'),
('rubino a intaglio'),
('rubino a intarsio'),
('rubino'),
('rubricatura su marmo'),
('sabbiatura su argilla'),
('saldatura su acciaio'),
('saldatura su argento'),
('saldatura su bronzo'),
('saldatura su ferro'),
('saldatura su lega metallica'),
('saldatura su metallo'),
('saldatura su oro'),
('saldatura su piombo'),
('saldatura su rame'),
('sarda'),
('sardonice a cabochon'),
('sardonice a incisione'),
('sardonice a intaglio'),
('sardonice a intarsio'),
('sardonice'),
('sbozzatura su calcare'),
('sbozzatura su corno'),
('sbozzatura su marmo africano'),
('sbozzatura su marmo asiatico'),
('sbozzatura su marmo bardiglio di Carrara'),
('sbozzatura su marmo bianco greco'),
('sbozzatura su marmo bianco italico'),
('sbozzatura su marmo bianco venato'),
('sbozzatura su marmo bianco'),
('sbozzatura su marmo bigio antico'),
('sbozzatura su marmo bigio morato'),
('sbozzatura su marmo bigio'),
('sbozzatura su marmo broccatello di Verona'),
('sbozzatura su marmo broccatello'),
('sbozzatura su marmo broccatellone'),
('sbozzatura su marmo cipollino mandolato'),
('sbozzatura su marmo cipollino marino'),
('sbozzatura su marmo cipollino rosso'),
('sbozzatura su marmo cipollino'),
('sbozzatura su marmo cottanello antico'),
('sbozzatura su marmo dell''Imetto'),
('sbozzatura su marmo di Carrara'),
('sbozzatura su marmo di Proconneso'),
('sbozzatura su marmo di Taso'),
('sbozzatura su marmo fior di pesco'),
('sbozzatura su marmo giallo antico brecciato'),
('sbozzatura su marmo giallo antico'),
('sbozzatura su marmo giallo tigrato'),
('sbozzatura su marmo greco insulare'),
('sbozzatura su marmo greco scritto'),
('sbozzatura su marmo grigio brecciato'),
('sbozzatura su marmo grigio venato'),
('sbozzatura su marmo grigio'),
('sbozzatura su marmo italico'),
('sbozzatura su marmo lumachella bigia'),
('sbozzatura su marmo lumachella d''Egitto'),
('sbozzatura su marmo lumachella pavonazza'),
('sbozzatura su marmo lumachella rosea'),
('sbozzatura su marmo lumachella'),
('sbozzatura su marmo lumachellone antico'),
('sbozzatura su marmo lunense'),
('sbozzatura su marmo nero africano'),
('sbozzatura su marmo nero antico'),
('sbozzatura su marmo occhio di pavone bianco'),
('sbozzatura su marmo occhio di pavone bigio'),
('sbozzatura su marmo occhio di pavone pavonazzo'),
('sbozzatura su marmo occhio di pavone roseo'),
('sbozzatura su marmo occhio di pavone rosso'),
('sbozzatura su marmo palombino'),
('sbozzatura su marmo pario'),
('sbozzatura su marmo pavonazzetto'),
('sbozzatura su marmo pentelico'),
('sbozzatura su marmo policromo'),
('sbozzatura su marmo portasanta'),
('sbozzatura su marmo proconnesio'),
('sbozzatura su marmo rosa'),
('sbozzatura su marmo rosso antico'),
('sbozzatura su marmo rosso brecciato'),
('sbozzatura su marmo semesanto'),
('sbozzatura su marmo serpentina moschinata'),
('sbozzatura su marmo verde antico'),
('sbozzatura su marmo verde rana fibroso'),
('sbozzatura su marmo verde rana ondato'),
('sbozzatura su marmo'),
('sbozzatura su nenfro'),
('sbozzatura su ofiolite'),
('sbozzatura su pietra ollare'),
('sbozzatura su pietra'),
('sbozzatura su tufo giallo litoide'),
('sbozzatura su tufo grigio'),
('sbozzatura su tufo Nocerino'),
('sbozzatura su tufo rosso a scorie nere'),
('sbozzatura su tufo rosso litoide'),
('sbozzatura su tufo Sabazio'),
('sbozzatura su tufo trachitico'),
('sbozzatura su tufo Vulsinio'),
('sbozzatura su tufo'),
('scalpellatura su alabastro a pecorella'),
('scalpellatura su alabastro a tartaruga'),
('scalpellatura su alabastro bianco'),
('scalpellatura su alabastro del Gebel Oust'),
('scalpellatura su alabastro di Palombara'),
('scalpellatura su alabastro dorato'),
('scalpellatura su alabastro egiziano'),
('scalpellatura su alabastro fiorito'),
('scalpellatura su alabastro marino'),
('scalpellatura su alabastro'),
('scalpellatura su ardesia'),
('scalpellatura su arenaria'),
('scalpellatura su basalto'),
('scalpellatura su basanite'),
('scalpellatura su breccia'),
('scalpellatura su calcare'),
('scalpellatura su calcarenite'),
('scalpellatura su clorite'),
('scalpellatura su granito'),
('scalpellatura su marmo africano'),
('scalpellatura su marmo asiatico'),
('scalpellatura su marmo bardiglio di Carrara'),
('scalpellatura su marmo bianco greco'),
('scalpellatura su marmo bianco italico'),
('scalpellatura su marmo bianco venato'),
('scalpellatura su marmo bianco'),
('scalpellatura su marmo bigio antico'),
('scalpellatura su marmo bigio morato'),
('scalpellatura su marmo bigio'),
('scalpellatura su marmo broccatello di Verona'),
('scalpellatura su marmo broccatello'),
('scalpellatura su marmo broccatellone'),
('scalpellatura su marmo cipollino mandolato'),
('scalpellatura su marmo cipollino marino'),
('scalpellatura su marmo cipollino rosso'),
('scalpellatura su marmo cipollino'),
('scalpellatura su marmo cottanello antico'),
('scalpellatura su marmo dell''Imetto'),
('scalpellatura su marmo di Carrara'),
('scalpellatura su marmo di Proconneso'),
('scalpellatura su marmo di Taso'),
('scalpellatura su marmo fior di pesco'),
('scalpellatura su marmo giallo antico brecciato'),
('scalpellatura su marmo giallo antico'),
('scalpellatura su marmo giallo tigrato'),
('scalpellatura su marmo greco insulare'),
('scalpellatura su marmo greco scritto'),
('scalpellatura su marmo grigio brecciato'),
('scalpellatura su marmo grigio venato'),
('scalpellatura su marmo grigio'),
('scalpellatura su marmo italico'),
('scalpellatura su marmo lumachella bigia'),
('scalpellatura su marmo lumachella d''Egitto'),
('scalpellatura su marmo lumachella pavonazza'),
('scalpellatura su marmo lumachella rosea'),
('scalpellatura su marmo lumachella'),
('scalpellatura su marmo lumachellone antico'),
('scalpellatura su marmo lunense'),
('scalpellatura su marmo nero africano'),
('scalpellatura su marmo nero antico'),
('scalpellatura su marmo occhio di pavone bianco'),
('scalpellatura su marmo occhio di pavone bigio'),
('scalpellatura su marmo occhio di pavone pavonazzo'),
('scalpellatura su marmo occhio di pavone roseo'),
('scalpellatura su marmo occhio di pavone rosso'),
('scalpellatura su marmo palombino'),
('scalpellatura su marmo pario'),
('scalpellatura su marmo pavonazzetto'),
('scalpellatura su marmo pentelico'),
('scalpellatura su marmo policromo'),
('scalpellatura su marmo portasanta'),
('scalpellatura su marmo proconnesio'),
('scalpellatura su marmo rosa'),
('scalpellatura su marmo rosso antico'),
('scalpellatura su marmo rosso brecciato'),
('scalpellatura su marmo semesanto'),
('scalpellatura su marmo serpentina moschinata'),
('scalpellatura su marmo verde antico'),
('scalpellatura su marmo verde rana fibroso'),
('scalpellatura su marmo verde rana ondato'),
('scalpellatura su marmo'),
('scalpellatura su nenfro'),
('scalpellatura su ofiolite'),
('scalpellatura su ossidiana'),
('scalpellatura su osso'),
('scalpellatura su peperino'),
('scalpellatura su pietra ollare'),
('scalpellatura su pietra'),
('scalpellatura su porfido bigio'),
('scalpellatura su porfido nero grafico'),
('scalpellatura su porfido nero'),
('scalpellatura su porfido rosso'),
('scalpellatura su porfido verde di Laconia'),
('scalpellatura su porfido verde egiziano'),
('scalpellatura su porfido'),
('scalpellatura su puddinga'),
('scalpellatura su trachite dei Colli Euganei'),
('scalpellatura su trachite'),
('scalpellatura su travertino'),
('scalpellatura su tufo giallo litoide'),
('scalpellatura su tufo grigio'),
('scalpellatura su tufo Nocerino'),
('scalpellatura su tufo rosso a scorie nere'),
('scalpellatura su tufo rosso litoide'),
('scalpellatura su tufo Sabazio'),
('scalpellatura su tufo trachitico'),
('scalpellatura su tufo Vulsinio'),
('scalpellatura su tufo'),
('scheggiatura su arenaria'),
('scheggiatura su calcare'),
('scheggiatura su diaspro'),
('scheggiatura su eliotropio'),
('scheggiatura su legno'),
('scheggiatura su ossidiana'),
('scheggiatura su osso'),
('scheggiatura su quarzite'),
('scheggiatura su quarzo'),
('scheggiatura su selce'),
('scialbatura su argilla'),
('scialbatura su impasto'),
('scialbatura su laterizio'),
('scialbatura su tufo giallo litoide'),
('scialbatura su tufo grigio'),
('scialbatura su tufo Nocerino'),
('scialbatura su tufo rosso a scorie nere'),
('scialbatura su tufo rosso litoide'),
('scialbatura su tufo Sabazio'),
('scialbatura su tufo trachitico'),
('scialbatura su tufo Vulsinio'),
('scialbatura su tufo'),
('scisto'),
('scoria di fusione'),
('scoria silicea'),
('segagione su osso'),
('selce a percussione'),
('selce'),
('seme'),
('seta'),
('smaltatura su acciaio'),
('smaltatura su argento'),
('smaltatura su argilla'),
('smaltatura su bronzo'),
('smaltatura su ferro'),
('smaltatura su lega metallica'),
('smaltatura su metallo'),
('smaltatura su oro'),
('smaltatura su rame'),
('smaltatura su vetro'),
('smeraldo a cabochon'),
('smeraldo a incisione'),
('smeraldo a intaglio'),
('smeraldo a intarsio'),
('smeraldo'),
('soffiatura a stampo su vetro'),
('soffiatura libera su vetro'),
('soffiatura su vetro'),
('spinello a cabochon'),
('spinello a incisione'),
('spinello a intaglio'),
('spinello a intarsio'),
('spinello'),
('stagnatura su bronzo'),
('stagno a incisione'),
('stagno'),
('stampaggio su argento'),
('stampaggio su bronzo'),
('stampaggio su metallo'),
('stampaggio su oro'),
('stampaggio su piombo'),
('stucco a spatola'),
('stucco'),
('subbiatura su marmo africano'),
('subbiatura su marmo asiatico'),
('subbiatura su marmo bardiglio di Carrara'),
('subbiatura su marmo bianco greco'),
('subbiatura su marmo bianco italico'),
('subbiatura su marmo bianco venato'),
('subbiatura su marmo bianco'),
('subbiatura su marmo bigio antico'),
('subbiatura su marmo bigio morato'),
('subbiatura su marmo bigio'),
('subbiatura su marmo broccatello di Verona'),
('subbiatura su marmo broccatello'),
('subbiatura su marmo broccatellone'),
('subbiatura su marmo cipollino mandolato'),
('subbiatura su marmo cipollino marino'),
('subbiatura su marmo cipollino rosso'),
('subbiatura su marmo cipollino'),
('subbiatura su marmo cottanello antico'),
('subbiatura su marmo dell''Imetto'),
('subbiatura su marmo di Carrara'),
('subbiatura su marmo di Proconneso'),
('subbiatura su marmo di Taso'),
('subbiatura su marmo fior di pesco'),
('subbiatura su marmo giallo antico brecciato'),
('subbiatura su marmo giallo antico'),
('subbiatura su marmo giallo tigrato'),
('subbiatura su marmo greco insulare'),
('subbiatura su marmo greco scritto'),
('subbiatura su marmo grigio brecciato'),
('subbiatura su marmo grigio venato'),
('subbiatura su marmo grigio'),
('subbiatura su marmo italico'),
('subbiatura su marmo lumachella bigia'),
('subbiatura su marmo lumachella d''Egitto'),
('subbiatura su marmo lumachella pavonazza'),
('subbiatura su marmo lumachella rosea'),
('subbiatura su marmo lumachella'),
('subbiatura su marmo lumachellone antico'),
('subbiatura su marmo lunense'),
('subbiatura su marmo nero africano'),
('subbiatura su marmo nero antico'),
('subbiatura su marmo occhio di pavone bianco'),
('subbiatura su marmo occhio di pavone bigio'),
('subbiatura su marmo occhio di pavone pavonazzo'),
('subbiatura su marmo occhio di pavone roseo'),
('subbiatura su marmo occhio di pavone rosso'),
('subbiatura su marmo palombino'),
('subbiatura su marmo pario'),
('subbiatura su marmo pavonazzetto'),
('subbiatura su marmo pentelico'),
('subbiatura su marmo policromo'),
('subbiatura su marmo portasanta'),
('subbiatura su marmo proconnesio'),
('subbiatura su marmo rosa'),
('subbiatura su marmo rosso antico'),
('subbiatura su marmo rosso brecciato'),
('subbiatura su marmo semesanto'),
('subbiatura su marmo serpentina moschinata'),
('subbiatura su marmo verde antico'),
('subbiatura su marmo verde rana fibroso'),
('subbiatura su marmo verde rana ondato'),
('subbiatura su marmo'),
('subbiatura su pietra'),
('sughero'),
('taglio a freddo su vetro'),
('taglio su corno'),
('taglio su osso'),
('taglio su pietra'),
('taglio su selce'),
('talco a tornio'),
('talco'),
('talcoscisto a tornio'),
('talcoscisto'),
('tempra su ferro'),
('tessitura a telaio su canapa'),
('tessitura a telaio su cotone'),
('tessitura a telaio su fibra di canapa'),
('tessitura a telaio su fibra di sparto'),
('tessitura a telaio su lana'),
('tessitura a telaio su lino'),
('tessitura a telaio su tessuto'),
('tessuto'),
('topazio a cabochon'),
('topazio a incisione'),
('topazio a intaglio'),
('topazio a intarsio'),
('topazio'),
('tormalina a cabochon'),
('tormalina a incisione'),
('tormalina a intaglio'),
('tormalina a intarsio'),
('tormalina'),
('trachite a gradina'),
('trachite a incisione'),
('trachite dei Colli Euganei a gradina'),
('trachite dei Colli Euganei a incisione'),
('trachite dei Colli Euganei'),
('trachite'),
('travertino a incisione'),
('travertino a trapano'),
('travertino'),
('tufo a incisione'),
('tufo giallo litoide a incisione'),
('tufo giallo litoide'),
('tufo grigio a incisione'),
('tufo grigio'),
('tufo Nocerino a incisione'),
('tufo Nocerino'),
('tufo rosso a scorie nere a incisione'),
('tufo rosso a scorie nere'),
('tufo rosso litoide a incisione'),
('tufo rosso litoide'),
('tufo Sabazio a incisione'),
('tufo Sabazio'),
('tufo trachitico a incisione'),
('tufo trachitico'),
('tufo Vulsinio a incisione'),
('tufo Vulsinio'),
('tufo'),
('turchese a cabochon'),
('turchese a incisione'),
('turchese a intaglio'),
('turchese a intarsio'),
('turchese'),
('verniciatura su argilla'),
('verniciatura su avorio'),
('verniciatura su impasto'),
('verniciatura su marmo asiatico'),
('verniciatura su marmo bianco greco'),
('verniciatura su marmo bianco italico'),
('verniciatura su marmo bianco venato'),
('verniciatura su marmo bianco'),
('verniciatura su marmo bigio'),
('verniciatura su marmo'),
('vetro a incisione'),
('vetro a intaglio'),
('vetro a spruzzo'),
('vetro'),
('zaffiro a cabochon'),
('zaffiro a incisione'),
('zaffiro a intaglio'),
('zaffiro a intarsio'),
('zaffiro'),
('zigrinatura su argento'),
('zigrinatura su metallo'),
('zircone a incisione'),
('zircone a intaglio'),
('zircone a intarsio'),
('zircone');
COMMIT;
